<html><title>.:EDITAR 3. EVALUACI&Oacute;N DE PROVEEDORES:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">3. EVALUACI&Oacute;N DE PROVEEDORES</td></tr><input type="hidden" name="encabezado" value="<?php echo(mostrar_valor_campo('encabezado',299,$_REQUEST['iddoc'])); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(299,3496,$_REQUEST['iddoc']);?></tr><tr>
                     <td class="encabezado" width="20%" title="">PROVEEDOR*</td>
                     <?php generar_lista_proveedores(299,3499,$_REQUEST['iddoc']);?></tr><tr id="tr_precio_cotizaciones" >
                     <td class="encabezado" width="20%" title="">PRECIO DE LAS COTIZACIONES*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(299,3493,$_REQUEST['iddoc']);?></td></tr><tr id="tr_matriculado_camara" >
                     <td class="encabezado" width="20%" title="">MATRICULADO*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(299,3492,$_REQUEST['iddoc']);?></td></tr><tr id="tr_atencion" >
                     <td class="encabezado" width="20%" title="">LA ATENCI&Oacute;N A LA SOLICITUD FUE*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(299,3489,$_REQUEST['iddoc']);?></td></tr><tr id="tr_cumplimiento" >
                     <td class="encabezado" width="20%" title="">CUMPLIMIENTO CON LAS ESPECIFICACIONES DEL PRODUCTO REQUERIDO*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(299,3490,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="descripcion_almacenada" value="<?php echo(mostrar_valor_campo('descripcion_almacenada',299,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="idft_evaluacion_proveedores" value="<?php echo(mostrar_valor_campo('idft_evaluacion_proveedores',299,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(mostrar_valor_campo('documento_iddocumento',299,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="firma" value="<?php echo(mostrar_valor_campo('firma',299,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="campo_descripcion" value="<?php echo('3491'); ?>"><input type="hidden" name="formato" value="299"><tr><td colspan='2'><?php submit_formato(299,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>