<html><title>.:ADICIONAR 1. VALORACION CONTROLES RIESGOS:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../riesgos_proceso/../riesgos_proceso/funciones.php"); ?><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">1. VALORACION CONTROLES RIESGOS</td></tr><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5400)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(434,5401);?></tr><tr>
                     <td class="encabezado" width="20%" title="">CONSECUTIVO</td>
                     <?php consecutivo_funcion_control(434,5402);?></tr><tr>
                     <td class="encabezado" width="20%" title="">FECHA VALORACION*</td>
                     <?php fecha_bloqueada_valoracion(434,5403);?></tr><tr>
                     <td class="encabezado" width="20%" title="">DESCRIPCI&Oacute;N DEL CONTROL EXISTENTE*</td>
                     <td class="celda_transparente"><textarea  tabindex='1'  name="descripcion_control" id="descripcion_control" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(5404)); ?></textarea></td>
                    </tr><tr id="tr_tipo_control" >
                     <td class="encabezado" width="20%" title="">EL CONTROL AFECTA?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5405,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="desplazamiento" value="<?php echo(validar_valor_campo(5406)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5408)); ?>"><tr>
                     <td class="encabezado" width="20%" title="" colspan="2" id="herramientas_ejercer_control"><center>HERRAMIENTAS PARA EJERCER EL CONTROL</center></td>
                    </tr><tr id="tr_herramienta_ejercer" >
                     <td class="encabezado" width="20%" title="">1. POSEE UNA HERRAMIENTA PARA EJERCER EL CONTROL?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5410,$_REQUEST['iddoc']);?></td></tr><tr id="tr_procedimiento_herramienta" >
                     <td class="encabezado" width="20%" title="">2. EXISTEN MANUALES, INSTRUCTIVOS O PROCEDIMIENTOS PARA EL MANEJO DE LA HERRAMIENTA?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5411,$_REQUEST['iddoc']);?></td></tr><tr id="tr_herramienta_efectiva" >
                     <td class="encabezado" width="20%" title="">3. EN EL TIEMPO QUE LLEVA LA HERRAMIENTA, HA DEMOSTRADO SER EFECTIVA?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5412,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="" colspan="2" id="seguimiento_al_control"><center>SEGUIMIENTO AL CONTROL</center></td>
                    </tr><tr id="tr_responsables_ejecucion" >
                     <td class="encabezado" width="20%" title="">4. ESTAN DEFINIDOS LOS RESPONSABLES DE LA EJECUCI&Oacute;N DEL CONTROL Y DEL SEGUIMIENTO?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5414,$_REQUEST['iddoc']);?></td></tr><tr id="tr_frecuencia_ejecucion" >
                     <td class="encabezado" width="20%" title="">5. LA FRECUENCIA DE LA EJECUCI&Oacute;N DEL CONTROL Y SEGUIMIENTO ES ADECUADO?*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(434,5415,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="idft_control_riesgos" value="<?php echo(validar_valor_campo(5416)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5417)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5418)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5419)); ?>"><?php validar_edicion_adicion_formatos_riesgo_aprobados(434,NULL);?><?php llenar_orientacion(434,NULL);?><?php validar_tipo_riesgo(434,NULL);?><?php validar_revision_aprobacion_control_riesgos(434,NULL);?><input type="hidden" name="campo_descripcion" value="5404"><tr><td colspan='2'><?php submit_formato(434);?></td></tr></table></form></body></html>