CREATE SEQUENCE  "ACCION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ALMACENAMIENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ANEXOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ASIGNACION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ASIG_ENTIDAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
CREATE SEQUENCE  "ASIGNACION_TERMINAR_SEQ" START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 0 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE  "AUTOGUARDADO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "BINARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "BUZON_ENTRADA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "BUZON_SALIDA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CAJA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CAMPOS_FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "CAMPOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CARACTERISTICAS_CAMPOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "CARGO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CARRUSEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "COMENTARIO_IMG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CONFIGURACION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CONTADOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "CONTENIDOS_CARRUSEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "DATOS_EJECUTOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "DATOS_EJECUTOR_TEMPORAL_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DEPARTAMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DEPENDENCIA_CARGO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DEPENDENCIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DIGITALIZACION_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DOCUMENTO_CALIDAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DOCUMENTO_ETIQUETA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DOCUMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "DOCUMENTO_VERSION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "EJECUTOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ENCABEZADO_FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "ENTIDAD_PRETEXTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ENTIDAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ENTIDAD_SERIE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ESTADISTICAS_SAIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ETIQUETA_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "EVENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "EXPEDIENTE_DOC_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "EXPEDIENTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "FILTRO_GRAFICA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FILTRO_REPORTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FOLDER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "FT_CARTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FT_MEMORANDO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FUNC_FORMATO_ACCION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "FUNCIONARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FUNCIONES_BUSQUEDA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "FUNCIONES_FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "FUNCION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "GRAFICO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "LOG_ACCESO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "MEMORANDO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "MENSAJE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "MODULO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "MUNICIPIO_EXTERIOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "MUNICIPIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PAGINA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PAIS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERFIL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_ANEXO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_DOCUMENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_EXPEDIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_FUNCIONARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_PERFIL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PERMISO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "PRETEXTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "REEMPLAZO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;
CREATE SEQUENCE  "REPORTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "RESERVA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "RESPUESTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "RUTA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SALIDAS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SERIE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SOLICITUD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "TAREA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "VISTA_FORMATO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
--TABLAS
CREATE TABLE "ACCION" ("IDACCION" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "DESCRIPCION" VARCHAR2(3000), "RUTA" VARCHAR2(255), "FUNCION" VARCHAR2(255), "PARAMETROS" VARCHAR2(255) DEFAULT NULL, "BOTON" VARCHAR(255) DEFAULT NULL, "MODULO_IDMODULO" NUMBER(10,0) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ALMACENAMIENTO" ("IDALMACENAMIENTO" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "FOLDER_IDFOLDER" NUMBER(10,0) DEFAULT '0', "SOPORTE" VARCHAR2(255), "NUM_FOLIOS" NUMBER(10,0), "ANEXOS" VARCHAR2(255), "DETERIORO" VARCHAR2(255), "RESPONSABLE" NUMBER(10,0) DEFAULT '0', "REGISTRO_ENTRADA" DATE DEFAULT TO_DATE('01-01-70 00:00:00', 'dd-mm-yy hh24:mi:ss')) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ANEXOS" ("IDANEXOS" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "RUTA" VARCHAR2(100), "TIPO" VARCHAR2(100) DEFAULT 'BASE', "ETIQUETA" VARCHAR2(255) DEFAULT null, "CAMPOS_FORMATO" NUMBER(10,0) DEFAULT null, "FORMATO" NUMBER(10,0) DEFAULT null, "IDBINARIO" NUMBER(10,0) DEFAULT null) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ASIGNACION" ("IDASIGNACION" NUMBER, "TAREA_IDTAREA" NUMBER, "FECHA_INICIAL" DATE DEFAULT sysdate, "FECHA_FINAL" DATE DEFAULT sysdate, "DOCUMENTO_IDDOCUMENTO" NUMBER, "SERIE_IDSERIE" NUMBER, "ESTADO" VARCHAR2(4000), "TIPO_REPROGRAMA" VARCHAR2(255), "LLAVE_ENTIDAD" NUMBER DEFAULT 0, "ENTIDAD_IDENTIDAD" NUMBER DEFAULT 0, "DESCRIPCION" VARCHAR2(255), "REPROGRAMA" VARCHAR2(4)) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 10485760 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ASIGNACION_ENTIDAD" ("IDASIGNACION_ENTIDAD" NUMBER, "ASIGNACION_IDASIGNACION" NUMBER, "ENTIDAD_IDENTIDAD" NUMBER, "LLAVE_ENTIDAD" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ASIGNACION_TERMINAR" ( "IDASIGNACION_TERMINAR" NUMBER (10,1) NOT NULL, "ASIGNACION_IDASIGNACION" NUMBER (10,1) NOT NULL, "JUSTIFICACION" VARCHAR2(255 BYTE) NOT NULL, "FECHA_TERMINACION" date NOT NULL, "FUNCIONARIO_CODIGO" NUMBER(11) NOT NULL, "TAREA_IDTAREA" NUMBER(11) NOT NULL,  "FECHA_INICIAL" date NOT NULL, "FECHA_FINAL" date NOT NULL, "DOCUMENTO_IDDOCUMENTO" NUMBER(11) NOT NULL, "SERIE_IDSERIE" NUMBER(11) NOT NULL, "ESTADO" VARCHAR2(255 BYTE) DEFAULT 'PENDIENTE' NOT NULL, "ENTIDAD_IDENTIDAD" NUMBER(11) NOT NULL, "LLAVE_ENTIDAD" NUMBER(11) NOT NULL, "REPROGRAMA" VARCHAR2(10 BYTE) NULL, "TIPO_REPRGRAMA" VARCHAR2(10 BYTE) NULL,  "DESCRIPCION" VARCHAR2(255 BYTE) NULL, CONSTRAINT ASIGNACION_TERMINAR_PK PRIMARY KEY (IDASIGNACION_TERMINAR));
CREATE TABLE "AUTOGUARDADO" ("IDAUTOGUARDADO" NUMBER, "CONTENIDO" CLOB DEFAULT empty_clob(), "FORMATO" VARCHAR2(255), "USUARIO" VARCHAR2(255), "CAMPO" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "BINARIO" ("IDBINARIO" NUMBER, "NOMBRE_ORIGINAL" VARCHAR2(255 CHAR), "DATOS" BLOB DEFAULT EMPTY_BLOB(), "FECHA_CREACION" DATE DEFAULT SYSDATE, "DESCRIPCION" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("DATOS") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "BUSQUEDA" ("IDBUSQUEDA" NUMBER(10,1), NOT NULL, "NOMBRE" VARCHAR2 (255 BYTE) NULL, "ETIQUETA" VARCHAR2(255 BYTE) NULL, "ESTADO" NUMBER(10,1) DEFAULT '1' NULL, "ANCHO" NUMBER(10,1) DEFAULT '200' NULL, "CAMPOS" VARCHAR2(255 BYTE) NULL, "LLAVE" VARCHAR2(255 BYTE) NULL, "TABLAS" VARCHAR2(255 BYTE) NULL, "RUTA_LIBRERIA" VARCHAR2(255 BYTE) NULL, "RUTA_LIBRERIA_PANTALLA" VARCHAR2(255 BYTE) NULL, "CANTIDAD_REGISTROS" NUMBER(10,1) DEFAULT '30' NULL, "TIEMPO_REFRESCAR" NUMBER(11) DEFAULT '500' NULL, "RUTA_VISUALIZACION" VARCHAR2(255 BYTE) DEFAULT 'pantallas/busqueda/componentes_busqueda.php' NULL, "TIPO_BUSQUEDA" NUMBER(11) DEFAULT '1' NULL, CONSTRAINT BUSQUEDA_PK PRIMARY KEY (IDBUSQUEDA);
CREATE TABLE "BUZON_ENTRADA" ("IDTRANSFERENCIA" NUMBER(10,0), "ARCHIVO_IDARCHIVO" NUMBER(10,0) DEFAULT '0', "NOMBRE" VARCHAR2(4000) DEFAULT 'RECEPCION', "DESTINO" VARCHAR2(20), "TIPO_DESTINO" NUMBER(10,0), "FECHA" DATE DEFAULT SYSDATE, "RESPUESTA" DATE, "ORIGEN" VARCHAR2(255), "TIPO_ORIGEN" NUMBER(10,0), "NOTAS" CLOB, "TRANSFERENCIA_DESCRIPCION" CLOB, "TIPO" VARCHAR2(4000) DEFAULT 'ARCHIVO', "ACTIVO" NUMBER(3,0) DEFAULT '0', "RUTA_IDRUTA" NUMBER(10,0) DEFAULT '0', "VER_NOTAS" VARCHAR2(1)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 310378496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("NOTAS") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("TRANSFERENCIA_DESCRIPCION") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "BUZON_SALIDA" ("IDTRANSFERENCIA" NUMBER(10,0), "ARCHIVO_IDARCHIVO" NUMBER(10,0) DEFAULT '0', "NOMBRE" VARCHAR2(4000) DEFAULT 'RECEPCION', "DESTINO" VARCHAR2(20), "TIPO_DESTINO" NUMBER(10,0), "FECHA" DATE DEFAULT SYSDATE, "RESPUESTA" DATE, "ORIGEN" VARCHAR2(255), "TIPO_ORIGEN" NUMBER(10,0), "NOTAS" CLOB, "TRANSFERENCIA_DESCRIPCION" CLOB, "TIPO" VARCHAR2(4000) DEFAULT 'ARCHIVO', "RUTA_IDRUTA" NUMBER(10,0) DEFAULT '0', "VER_NOTAS" VARCHAR2(1) DEFAULT null) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 293601280 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("NOTAS") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("TRANSFERENCIA_DESCRIPCION") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "CAJA" ("IDCAJA" NUMBER(10,0), "NUMERO" NUMBER(10,0) DEFAULT '0', "UBICACION" VARCHAR2(255), "ESTANTERIA" VARCHAR2(255), "NIVEL" NUMBER(10,0) DEFAULT '0', "PANEL" NUMBER(10,0) DEFAULT '0', "MATERIAL" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CAMPOS" ("IDCAMPOS" NUMBER(10,3), "NOMBRE" VARCHAR2(255), "ALIAS" VARCHAR2(255), "TABLA" VARCHAR2(255), "TIPO" VARCHAR2(255), "VALOR" VARCHAR2(255), "AYUDA" VARCHAR2(255), "VISIBLE" NUMBER(10,3) DEFAULT 1, "SELECCIONADO" VARCHAR2(1) DEFAULT 1, "TIPO_DATO" VARCHAR2(255) DEFAULT 'varchar') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CAMPOS_FORMATO" ("IDCAMPOS_FORMATO" NUMBER, "FORMATO_IDFORMATO" NUMBER, "NOMBRE" VARCHAR2(255 CHAR) DEFAULT '', "ETIQUETA" VARCHAR2(255 CHAR) DEFAULT '', "TIPO_DATO" VARCHAR2(255 CHAR) DEFAULT '', "LONGITUD" VARCHAR2(255 CHAR), "OBLIGATORIEDAD" NUMBER DEFAULT 0, "VALOR" VARCHAR2(2000), "ACCIONES" VARCHAR2(10 CHAR) DEFAULT 'a,e', "AYUDA" VARCHAR2(1000), "PREDETERMINADO" VARCHAR2(255 CHAR), "BANDERAS" VARCHAR2(50 CHAR), "ORDEN" NUMBER DEFAULT 0, "ETIQUETA_HTML" VARCHAR2(255 CHAR) DEFAULT 'text', "MASCARA" VARCHAR2(255), "ADICIONALES" VARCHAR2(255), "AUTOGUARDADO" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CARACTERISTICAS_CAMPOS" ("IDCARACTERISTICAS_CAMPOS" NUMBER, "TIPO_CARACTERISTICA" VARCHAR2(255) DEFAULT 'validacion', "VALOR" VARCHAR2(255) DEFAULT NULL, "IDCAMPOS_FORMATO" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CARGO" ("IDCARGO" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "ESTADO" NUMBER(3,0) DEFAULT '1', "COD_PADRE" NUMBER DEFAULT null, "TIPO" NUMBER DEFAULT 1, "CODIGO_CARGO" NUMBER DEFAULT null) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CARRUSEL" ("IDCARRUSEL" NUMBER(11,0), "NOMBRE" VARCHAR2(255), "AUTOPLAY" VARCHAR2(255) DEFAULT 'true', "DELAY" VARCHAR2(255) DEFAULT '3000', "STARTSTOPPED" VARCHAR2(255) DEFAULT 'false', "ANIMATIONTIME" VARCHAR2(255) DEFAULT '600', "BUILDNAVIGATION" VARCHAR2(255) DEFAULT 'true', "PAUSEONHOVER" VARCHAR2(255) DEFAULT 'true', "STARTTEXT" VARCHAR2(255) DEFAULT 'Iniciar', "STOPTEXT" VARCHAR2(255) DEFAULT 'Detener', "EASING" VARCHAR2(255) DEFAULT 'easeInOutExpo', "FECHA_INICIO" DATE, "FECHA_FIN" DATE, "ANCHO" NUMBER(11,0), "ALTO" NUMBER(11,0), "CSS" VARCHAR2(2000)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "COMENTARIO_IMG" ("IDCOMENTARIO_IMG" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "TIPO" VARCHAR2(4000) DEFAULT 'PAGINA', "PAGINA" NUMBER(10,0) DEFAULT '0', "COMENTARIO" CLOB, "POSX" NUMBER(10,0) DEFAULT '0', "POSY" NUMBER(10,0) DEFAULT '0', "FUNCIONARIO" VARCHAR2(255), "FECHA" DATE DEFAULT sysdate) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("COMENTARIO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "CONFIGURACION" ("IDCONFIGURACION" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "VALOR" VARCHAR2(255), "TIPO" VARCHAR2(255), "FECHA" DATE DEFAULT SYSDATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CONTADOR" ("IDCONTADOR" NUMBER(10,0), "CONSECUTIVO" NUMBER(10,0) DEFAULT '1', "NOMBRE" VARCHAR2(100), "REINICIAR_CAMBIO_ANIO" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "CONTENIDOS_CARRUSEL" ("IDCONTENIDOS_CARRUSEL" NUMBER(11,0), "CARRUSEL_IDCARRUSEL" NUMBER(11,0), "CONTENIDO" CLOB DEFAULT empty_clob(), "NOMBRE" VARCHAR2(255), "ORDEN" NUMBER(11,0) DEFAULT '0', "FECHA_INICIO" DATE, "FECHA_FIN" DATE, "PREVIEW" CLOB DEFAULT empty_clob(), "IMAGEN" BLOB DEFAULT empty_blob(), "ALIGN" VARCHAR2(20) DEFAULT 'left') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("PREVIEW") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("IMAGEN") STORE AS "SYS_LOB0000143683C00009$$"( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "DATOS_EJECUTOR" ("IDDATOS_EJECUTOR" NUMBER, "EJECUTOR_IDEJECUTOR" NUMBER, "DIRECCION" VARCHAR2(255) DEFAULT NULL, "TELEFONO" VARCHAR2(50) DEFAULT NULL, "CARGO" VARCHAR2(255) DEFAULT NULL, "CIUDAD" VARCHAR2(255) DEFAULT NULL, "TITULO" VARCHAR2(50) DEFAULT NULL, "EMPRESA" VARCHAR2(255) DEFAULT NULL, "FECHA" DATE DEFAULT SYSDATE, "EMAIL" VARCHAR2(255) DEFAULT NULL, "ID_VIEJO" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DEPARTAMENTO" ("NOMBRE" VARCHAR2(255), "IDDEPARTAMENTO" NUMBER(10,0), "PAIS_IDPAIS" NUMBER DEFAULT 1) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DEPENDENCIA" ("IDDEPENDENCIA" NUMBER(10,0), "CODIGO" VARCHAR2(50), "NOMBRE" VARCHAR2(255), "FECHA_INGRESO" DATE DEFAULT SYSDATE, "COD_PADRE" NUMBER(10,0), "TIPO" NUMBER(10,0) DEFAULT '1', "ESTADO" NUMBER(3,0) DEFAULT '1', "EXTENSION" VARCHAR2(10), "CODIGO_TABLA" VARCHAR2(50), "LOGO" BLOB DEFAULT EMPTY_BLOB()) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("LOGO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "DEPENDENCIA_CARGO" ("IDDEPENDENCIA_CARGO" NUMBER(10,0), "FUNCIONARIO_IDFUNCIONARIO" NUMBER(10,0) DEFAULT '0', "DEPENDENCIA_IDDEPENDENCIA" NUMBER(10,0) DEFAULT '0', "CARGO_IDCARGO" NUMBER(10,0) DEFAULT '0', "ESTADO" NUMBER(3,0) DEFAULT '1', "FECHA_INICIAL" DATE DEFAULT TO_DATE('2007-01-01','yyyy-mm-dd'), "FECHA_FINAL" DATE DEFAULT TO_DATE('2008-01-01','yyyy-mm-dd'), "FECHA_INGRESO" DATE DEFAULT SYSDATE, "TIPO" VARCHAR2(1) DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DIGITALIZACION" ("IDDIGITALIZACION" NUMBER, "DOCUMENTO_IDDOCUMENTO" NUMBER, "FECHA" DATE DEFAULT SYSDATE, "ACCION" VARCHAR2(255), "FUNCIONARIO" VARCHAR2(255), "JUSTIFICACION" VARCHAR2(4000)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 14680064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DOCUMENTO" ("IDDOCUMENTO" NUMBER(10,0), "NUMERO" VARCHAR2(255), "SERIE" NUMBER(10,0) DEFAULT '0', "FECHA" DATE DEFAULT SYSDATE, "EJECUTOR" NUMBER(15,0) DEFAULT '0', "DESCRIPCION" VARCHAR2(4000), "PAGINAS" NUMBER(10,0) DEFAULT '1', "MUNICIPIO_IDMUNICIPIO" NUMBER(10,0) DEFAULT 658, "PDF" VARCHAR2(255), "TIPO_RADICADO" NUMBER(10,0) DEFAULT '0', "ESTADO" VARCHAR2(4000) DEFAULT 'INICIADO', "FECHA_OFICIO" DATE, "OFICIO" VARCHAR2(20), "ANEXO" VARCHAR2(4000), "DESCRIPCION_ANEXO" VARCHAR2(4000), "DIAS" NUMBER(3,0), "ALMACENADO" NUMBER(3,0) DEFAULT '0', "PLANTILLA" VARCHAR2(30), "RESPONSABLE" NUMBER(10,0), "TIPO_DESPACHO" NUMBER(3,0) DEFAULT 0, "FECHA_CREACION" DATE DEFAULT SYSDATE, "ACTIVA_ADMIN" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 39845888 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DOCUMENTO_CALIDAD" ("IDDOCUMENTO_CALIDAD" NUMBER(10,3), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,3), "EST_CALIDAD_IDEST_CALIDAD" NUMBER(10,3)) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DOCUMENTO_ETIQUETA" ("IDDOCUMENTO_ETIQUETA" NUMBER(11,0), "ETIQUETA_IDETIQUETA" NUMBER(11,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(11,0), "FECHA" DATE DEFAULT sysdate) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "DOCUMENTO_VERSION" ("IDDOCUMENTO_VERSION" NUMBER(10,3), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,3), "NUMERO_VERSION" NUMBER(10,3) DEFAULT 0, "PREFIJO" VARCHAR2(50), "SUFIJO" VARCHAR2(50)) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "EJECUTOR" ("IDEJECUTOR" NUMBER(10,0), "IDENTIFICACION" VARCHAR2(50), "NOMBRE" VARCHAR2(255), "FECHA_INGRESO" DATE DEFAULT SYSDATE, "IDVIEJO" NUMBER) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ENCABEZADO_FORMATO" ("IDENCABEZADO_FORMATO" NUMBER, "CONTENIDO" CLOB DEFAULT EMPTY_CLOB(), "ETIQUETA" VARCHAR2(255) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "ENTIDAD" ("IDENTIDAD" NUMBER(10,0), "NOMBRE" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ENTIDAD_PRETEXTO" ("IDENTIDAD_PRETEXTO" NUMBER(10,0), "PRETEXTO_IDPRETEXTO" NUMBER(10,0), "ENTIDAD_IDENTIDAD" NUMBER(10,0) DEFAULT '0', "LLAVE_ENTIDAD" NUMBER(10,0) DEFAULT '1', "ESTADO" NUMBER(3,0), "FECHA" DATE DEFAULT SYSDATE) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ENTIDAD_SERIE" ("IDENTIDAD_SERIE" NUMBER(10,3), "ENTIDAD_IDENTIDAD" NUMBER(10,3), "SERIE_IDSERIE" NUMBER(10,3), "LLAVE_ENTIDAD" NUMBER(10,3), "ESTADO" VARCHAR2(255), "TIPO" VARCHAR2(1) DEFAULT '0', "FECHA" DATE DEFAULT SYSDATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ENTIDAD_TAREA" ("IDENTIDAD_TAREA" NUMBER, "ENTIDAD_IDENTIDAD" NUMBER DEFAULT '0', "LLAVE_ENTIDAD" NUMBER DEFAULT '0', "TAREA_IDTAREA" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ESTADISTICAS_SAIA" ("IDESTADISTICAS_SAIA" NUMBER(10,0), "FUNCIONARIO_IDFUNCIONARIO" NUMBER(10,0), "DEPENDENCIA_IDDEPENDENCIA" NUMBER(10,0), "CARGO_IDCARGO" NUMBER(10,0), "FECHA" DATE DEFAULT sysdate, "DATOS_ESTADISTICAS" VARCHAR2(4000) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ESTRUCTURA_CALIDAD" ("IDESTRUCTURA_CALIDAD" NUMBER(10,3), "NOMBRE" VARCHAR2(255), "COD_PADRE" NUMBER(10,3), "NIVEL" NUMBER(10,2) DEFAULT 0, "MOSTRAR" NUMBER(10,2) DEFAULT 1, "CODIGO" VARCHAR2(255) DEFAULT 0) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "ETIQUETA" ("IDETIQUETA" NUMBER(11,0), "NOMBRE" VARCHAR2(255), "FUNCIONARIO" VARCHAR2(255), "PRIVADA_SAIA" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "EVENTO" ("IDEVENTO" NUMBER(10,0), "FUNCIONARIO_CODIGO" VARCHAR2(20), "FECHA" DATE DEFAULT SYSDATE, "EVENTO" VARCHAR2(4000) DEFAULT 'ADICIONAR', "ESTADO" CHAR(1), "DETALLE" CLOB DEFAULT empty_clob(), "REGISTRO_ID" NUMBER(10,0), "TABLA_E" VARCHAR2(30), "CODIGO_SQL" CLOB DEFAULT empty_clob()) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 402653184 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("DETALLE") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("CODIGO_SQL") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "EXPEDIENTE" ("IDEXPEDIENTE" NUMBER, "NOMBRE" VARCHAR2(255), "FECHA" DATE DEFAULT SYSDATE, "DESCRIPCION" CLOB DEFAULT EMPTY_CLOB(), "CODIGO" VARCHAR2(255), "COD_PADRE" VARCHAR2(20)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("DESCRIPCION") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "EXPEDIENTE_DOC" ("IDEXPEDIENTE_DOC" NUMBER, "EXPEDIENTE_IDEXPEDIENTE" NUMBER DEFAULT '0', "DOCUMENTO_IDDOCUMENTO" NUMBER DEFAULT '0', "FECHA" DATE DEFAULT SYSDATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FILTRO_GRAFICA" ("IDFILTRO_GRAFICA" NUMBER, "GRAFICA_IDGRAFICA" NUMBER, "CAMPO" VARCHAR2(255), "ETIQUETA_HTML" VARCHAR2(255), "CODIGO_SQL" VARCHAR2(2000), "ETIQUETA" VARCHAR2(255), "TIPO_DATO" VARCHAR2(255) DEFAULT 'varchar') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FILTRO_REPORTE" ("IDFILTRO_REPORTE" NUMBER, "REPORTE_IDREPORTE" NUMBER, "CAMPO" VARCHAR2(255), "ETIQUETA_HTML" VARCHAR2(255), "CODIGO_SQL" VARCHAR2(2000), "ETIQUETA" VARCHAR2(255), "TIPO_DATO" VARCHAR2(255) DEFAULT 'varchar') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FOLDER" ("IDFOLDER" NUMBER(10,0), "CAJA_IDCAJA" NUMBER(10,0) DEFAULT '0', "SERIE_IDSERIE" NUMBER(10,0) DEFAULT '0', "ETIQUETA" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FORMATO" ("IDFORMATO" NUMBER, "NOMBRE" VARCHAR2(255), "ETIQUETA" VARCHAR2(255), "COD_PADRE" NUMBER DEFAULT 0, "CONTADOR_IDCONTADOR" NUMBER DEFAULT 0, "NOMBRE_TABLA" VARCHAR2(255), "RUTA_MOSTRAR" VARCHAR2(255), "RUTA_EDITAR" VARCHAR2(255), "RUTA_ADICIONAR" VARCHAR2(255), "LIBRERIAS" VARCHAR2(255) DEFAULT null, "ESTILOS" VARCHAR2(255) DEFAULT null, "JAVASCRIPT" VARCHAR2(255) DEFAULT null, "ENCABEZADO" VARCHAR2(4000), "PIE_PAGINA" VARCHAR2(4000), "MARGENES" VARCHAR2(50) DEFAULT '30,30,30,30', "ORIENTACION" VARCHAR2(50), "PAPEL" VARCHAR2(50) DEFAULT 'letter', "EXPORTAR" VARCHAR2(255) DEFAULT 'pdf', "FUNCIONARIO_IDFUNCIONARIO" NUMBER DEFAULT 0, "FECHA" DATE DEFAULT sysdate, "MOSTRAR" VARCHAR2(1) DEFAULT 1, "IMAGEN" VARCHAR2(1), "DETALLE" VARCHAR2(1) DEFAULT 0, "TIPO_EDICION" VARCHAR2(1) DEFAULT 0, "ITEM" VARCHAR2(1) DEFAULT 0, "SERIE_IDSERIE" NUMBER DEFAULT 0, "AYUDA" VARCHAR2(400), "CUERPO" CLOB DEFAULT empty_clob(), "FONT_SIZE" VARCHAR2(5) DEFAULT '12', "BANDERAS" VARCHAR2(255) DEFAULT 'm', "TIEMPO_AUTOGUARDADO" VARCHAR2(20) DEFAULT 300000, "MOSTRAR_PDF" NUMBER DEFAULT 1, "RESPUESTA_WEB" CLOB DEFAULT empty_clob(), "VIGENCIA_LOGO" NUMBER DEFAULT 1) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CUERPO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("RESPUESTA_WEB") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "FT_CARTA" ("IDFT_CARTA" NUMBER(11,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(11,0) DEFAULT '0', "DEPENDENCIA" NUMBER(11,0) DEFAULT '0', "DESTINOS" VARCHAR2(2000), "ASUNTO" VARCHAR2(1000), "CONTENIDO" CLOB DEFAULT empty_clob(), "DESPEDIDA" VARCHAR2(255), "FIRMA" NUMBER(11,0) DEFAULT '1', "INICIALES" VARCHAR2(255), "FECHA_AUX" VARCHAR2(20), "SERIE_IDSERIE" NUMBER(11,0) DEFAULT '0', "ENCABEZADO" VARCHAR2(1), "ANEXOS_FISICOS" VARCHAR2(2000), "COPIA" VARCHAR2(2000), "COPIAINTERNA" VARCHAR2(2000) DEFAULT null, "VERCOPIAINTERNA" NUMBER(*,0) DEFAULT 1, "ANEXOS_DIGITALES" VARCHAR2(2000) DEFAULT null, "FECHA_CARTA" DATE DEFAULT SYSDATE, "SALUDO" NUMBER(11,0), "OTRO_SALUDO" VARCHAR2(2000)) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 63963136 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "FT_MEMORANDO" ("IDFT_MEMORANDO" NUMBER(11,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(11,0) DEFAULT '0', "ORIGEN" NUMBER(10,0) DEFAULT '0', "DESTINO" VARCHAR2(2000), "ASUNTO" VARCHAR2(2000), "CONTENIDO" CLOB DEFAULT empty_clob(), "FIRMA" NUMBER(11,0) DEFAULT '1', "ENCABEZADO" VARCHAR2(1), "DEPENDENCIA" NUMBER(11,0), "FECHA_MEMO" VARCHAR2(100) DEFAULT SYSDATE, "DESPEDIDA" VARCHAR2(255), "ANEXOS_FISICOS" VARCHAR2(2000), "COPIA" VARCHAR2(2000), "INICIALES" VARCHAR2(255), "FECHA_MEMORANDO" DATE DEFAULT SYSDATE, "SERIE_IDSERIE" NUMBER(11,0), "ANEXOS" VARCHAR2(255)) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 38797312 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "FUNCION" ("IDFUNCION" NUMBER, "COMPONENTE_PANTALLA_IDPANTALLA" NUMBER DEFAULT '0', "COMPONENTE_IDCOMPONENTE" NUMBER DEFAULT '0', "PANTALLA_IDPANTALLA" NUMBER DEFAULT '0', "NOMBRE" VARCHAR2(255) DEFAULT '', "PARAMETROS" VARCHAR2(255) DEFAULT NULL, "RETORNO" VARCHAR2(255) DEFAULT NULL, "CLASE" VARCHAR2(255) DEFAULT '', "ACCION" VARCHAR2(100) DEFAULT '') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FUNCIONARIO" ("IDFUNCIONARIO" NUMBER(10,0), "FUNCIONARIO_CODIGO" NUMBER DEFAULT '0', "LOGIN" VARCHAR2(255), "NOMBRES" VARCHAR2(255), "APELLIDOS" VARCHAR2(255), "FIRMA" BLOB DEFAULT EMPTY_BLOB(), "ESTADO" NUMBER(10,0) DEFAULT '1', "FECHA_INGRESO" DATE DEFAULT SYSDATE, "CLAVE" VARCHAR2(255), "NIT" VARCHAR2(100), "PERFIL" NUMBER(3,0) DEFAULT '6', "DEBE_FIRMAR" NUMBER(3,0) DEFAULT '1', "TIPO" VARCHAR2(1) DEFAULT '0', "COD_PADRE" NUMBER DEFAULT 0, "SISTEMA" NUMBER(3,0) DEFAULT 1, "EMAIL" VARCHAR2(255) DEFAULT null, "MENSAJERIA" CHAR(1) DEFAULT null, "CLAVE_CORREO" VARCHAR2(255), "ORDENADOR_GASTO" NUMBER DEFAULT 0, "ACCESO_WEB" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("FIRMA") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "FUNCIONES_BUSQUEDA" ("IDFUNCIONES_BUSQUEDA" NUMBER(10,3), "ETIQUETA" VARCHAR2(255), "BUSQUEDAS_IDBUSQUEDA" NUMBER(10,3) DEFAULT 0, "PAGINA" VARCHAR2(255), "PARAMETROS" VARCHAR2(255), "TIPO" VARCHAR2(255) DEFAULT 'link', "ORDEN" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FUNCIONES_FORMATO" ("IDFUNCIONES_FORMATO" NUMBER, "NOMBRE" VARCHAR2(255) DEFAULT '', "NOMBRE_FUNCION" VARCHAR2(255) DEFAULT '', "PARAMETROS" VARCHAR2(255) DEFAULT NULL, "ETIQUETA" VARCHAR2(255) DEFAULT '', "DESCRIPCION" VARCHAR2(255) DEFAULT '', "RUTA" VARCHAR2(255) DEFAULT '', "FORMATO" VARCHAR2(255) DEFAULT '', "ACCIONES" VARCHAR2(10) DEFAULT 'm') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "FUNCIONES_FORMATO_ACCION" ("IDFUNCIONES_FORMATO_ACCION" NUMBER(11,0), "IDFUNCIONES_FORMATO" NUMBER(11,0), "ACCION_IDACCION" NUMBER(11,0), "FORMATO_IDFORMATO" NUMBER(11,0), "MOMENTO" VARCHAR2(20) DEFAULT 'ANTERIOR', "ESTADO" NUMBER(1,0) DEFAULT '1', "ORDEN" NUMBER(11,0) DEFAULT '1') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "GRAFICO" ("IDGRAFICO" NUMBER, "ETIQUETA" VARCHAR2(255), "ETIQUETAX" VARCHAR2(255) DEFAULT NULL, "ETIQUETAY" VARCHAR2(255) DEFAULT NULL, "SQL_GRAFICO" CLOB DEFAULT EMPTY_CLOB(), "TIPO_GRAFICO" VARCHAR2(255) DEFAULT 'barra', "ANCHO" NUMBER DEFAULT 300, "ALTO" NUMBER DEFAULT 400, "MASCARAS" VARCHAR2(4000) DEFAULT NULL, "PRESICION_DATO" NUMBER DEFAULT 2, "PREFIJO" VARCHAR2(255) DEFAULT NULL, "ESTADO" NUMBER DEFAULT 1, "NOMBRE" VARCHAR2(255) DEFAULT '', "MODULO_IDMODULO" NUMBER DEFAULT NULL, "DIRECCION_TITULO" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("SQL_GRAFICO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "LOG_ACCESO" ("IDLOG_ACCESO" NUMBER, "IPLOCAL" VARCHAR2(255), "IPREMOTA" VARCHAR2(255), "LOGIN" VARCHAR2(255), "EXITO" NUMBER(1,0), "IDSESION_PHP" VARCHAR2(255), "SESION_PHP" VARCHAR2(2000), "FECHA" DATE, "FECHA_CIERRE" DATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 23068672 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "MENSAJE" ("IDMENSAJE" NUMBER(10,0), "ASUNTO" VARCHAR2(100), "REMITENTE" VARCHAR2(100) DEFAULT '', "FECHA_MENSAJE" DATE, "CONTENIDO" CLOB, "DESTINATARIO" CLOB, "COPIA" CLOB, "DOCUMENTO_IDDOCUMENTO" NUMBER(10,2), "DEPENDENCIA" NUMBER(10,2) DEFAULT 0, "ENCABEZADO" VARCHAR2(1) DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("DESTINATARIO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))  LOB ("COPIA") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "MIGRACION" ("IDMIGRACION" NUMBER, "EXTENSIONES_VALIDAS" VARCHAR2(255), "RUTA_INICIAL" VARCHAR2(255), "LIBRERIAS" VARCHAR2(255), "FUNCIONES_ARCHIVO" VARCHAR2(255), "FUNCIONES_DIRECTORIO" VARCHAR2(255), "FUNCION_FINALIZACION" VARCHAR2(255), "FORMATO_IDFORMATO" NUMBER, "ETIQUETA" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "MODULO" ("IDMODULO" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "TIPO" VARCHAR2(255) DEFAULT 'secundario', "IMAGEN" VARCHAR2(255) DEFAULT 'botones/configuracion/default.gif', "ETIQUETA" VARCHAR2(255), "ENLACE" VARCHAR2(255), "DESTINO" VARCHAR2(255) DEFAULT 'centro', "COD_PADRE" NUMBER(10,0), "ORDEN" NUMBER(3,0) DEFAULT '1', "PARAMETROS" VARCHAR2(255), "BUSQUEDA_IDBUSQUEDA" NUMBER DEFAULT null, "AYUDA" CLOB DEFAULT NULL, "PERMISO_ADMIN" NUMBER) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("AYUDA") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "MUNICIPIO" ("IDMUNICIPIO" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "DEPARTAMENTO_IDDEPARTAMENTO" NUMBER(10,0) DEFAULT '0') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "MUNICIPIO_EXTERIOR" ("IDMUNICIPIO_EXTERIOR" NUMBER, "NOMBRE" VARCHAR2(255) DEFAULT '', "DEPARTAMENTO_IDDEPARTAMENTO" NUMBER DEFAULT '0') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PAGINA" ("CONSECUTIVO" NUMBER(10,0), "ID_DOCUMENTO" NUMBER(10,0) DEFAULT '0', "IMAGEN" VARCHAR2(255), "PAGINA" NUMBER(10,0) DEFAULT '1', "RUTA" VARCHAR2(255), "IDBINARIO_PAG" NUMBER(10,0) DEFAULT null, "IDBINARIO_MIN" NUMBER(10,0) DEFAULT null) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 33554432 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PAIS" ("IDPAIS" NUMBER, "NOMBRE" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERFIL" ("IDPERFIL" NUMBER(10,0), "NOMBRE" VARCHAR2(4000) DEFAULT 'ADMINISTRADOR') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO" ("IDPERMISO" NUMBER(10,0), "FUNCIONARIO_IDFUNCIONARIO" NUMBER(10,0) DEFAULT '0', "ACCION" VARCHAR2(50), "MODULO_IDMODULO" NUMBER(10,0) DEFAULT '0', "CARACTERISTICA_PROPIO" VARCHAR2(15), "CARACTERISTICA_GRUPO" VARCHAR2(15), "CARACTERISTICA_TOTAL" VARCHAR2(15), "TIPO" VARCHAR2(1) DEFAULT 1) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO_ANEXO" ("IDPERMISO_ANEXO" NUMBER, "ANEXOS_IDANEXOS" NUMBER DEFAULT '0', "IDPROPIETARIO" NUMBER DEFAULT '0', "CARACTERISTICA_PROPIO" VARCHAR2(8), "CARACTERISTICA_DEPENDENCIA" VARCHAR2(8) DEFAULT NULL, "CARACTERISTICA_CARGO" VARCHAR2(8) DEFAULT NULL, "CARACTERISTICA_TOTAL" VARCHAR2(8) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO_DOCUMENTO" ("IDPERMISO_DOCUMENTO" NUMBER(10,0), "FUNCIONARIO" NUMBER(11,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(11,0), "PERMISOS" VARCHAR2(20), "FECHA" DATE DEFAULT sysdate) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO_EXPEDIENTE" ("IDPERMISO_EXPEDIENTE" NUMBER(22,0), "EXPEDIENTE_IDEXPEDIENTE" NUMBER(22,0) DEFAULT 0, "IDPROPIETARIO" NUMBER(22,0) DEFAULT 0, "CARACTERISTICA_PROPIO" VARCHAR2(8) DEFAULT NULL, "CARACTERISTICA_DEPENDENCIA" VARCHAR2(8) DEFAULT NULL, "CARACTERISTICA_CARGO" VARCHAR2(8) DEFAULT NULL, "CARACTERISTICA_TOTAL" VARCHAR2(8) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO_FUNCIONARIO" ("IDPERMISO_FUNCIONARIO" NUMBER(11,0), "ENTIDAD_PROPIETARIA" NUMBER(11,0), "LLAVE_PROPIETARIA" NUMBER(11,0) DEFAULT NULL, "ENTIDAD_COMPARTIDA" NUMBER(11,0), "LLAVE_COMPARTIDA" VARCHAR2(255), "FECHA" DATE, "ASIGNADO_POR" NUMBER(11,0), "VIGENCIA_INICIAL" DATE, "VIGENCIA_FINAL" DATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PERMISO_PERFIL" ("IDPERMISO_PERFIL" NUMBER(10,0), "MODULO_IDMODULO" NUMBER(10,0) DEFAULT '0', "PERFIL_IDPERFIL" NUMBER(10,0) DEFAULT '0', "CARACTERISTICA_PROPIO" VARCHAR2(15), "CARACTERISTICA_GRUPO" VARCHAR2(15), "CARACTERISTICA_TOTAL" VARCHAR2(15)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "PRETEXTO" ("IDPRETEXTO" NUMBER(10,0), "AYUDA" VARCHAR2(1000), "IMAGEN" VARCHAR2(255), "ASUNTO" VARCHAR2(1000), "CATEGORIA" VARCHAR2(255), "CONTENIDO" CLOB DEFAULT empty_clob()) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CONTENIDO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "REEMPLAZO" ("IDREEMPLAZO" NUMBER, "ANTIGUO" NUMBER DEFAULT '0', "NUEVO" NUMBER DEFAULT '0', "FECHA_INICIO" DATE DEFAULT SYSDATE, "FECHA_FIN" DATE DEFAULT NULL, "CARGO_NUEVO" NUMBER DEFAULT '0', "ACTIVO" VARCHAR2(1) DEFAULT '1', "RESPONSABLE" VARCHAR2(255)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "REPORTE" ("IDREPORTE" NUMBER DEFAULT NULL, "NOMBRE" VARCHAR2(255) DEFAULT '', "SQL_REPORTE" VARCHAR2(3000), "NOMBRE_ARCHIVO" VARCHAR2(255) DEFAULT 'reporte', "ESTADO" NUMBER DEFAULT '1', "MASCARAS" VARCHAR2(3000), "MODULO_IDMODULO" NUMBER DEFAULT 0, "FILTRO_OBLIGATORIO" NUMBER DEFAULT 0) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "RESERVA" ("IDRESERVA" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "SOLICITUD_IDSOLICITUD" NUMBER(10,0) DEFAULT '0', "INVESTIGADOR_IDINVESTIGADOR" NUMBER(10,0) DEFAULT '0', "FECHA_INICIAL" DATE DEFAULT SYSDATE, "FECHA_FINAL" DATE) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "RESPUESTA" ("IDRESPUESTA" NUMBER(10,0), "FECHA" DATE DEFAULT SYSDATE, "DESTINO" NUMBER(10,0) DEFAULT '0', "ORIGEN" NUMBER(10,0) DEFAULT '0', "IDBUZON" NUMBER(10,0) DEFAULT '0', "PLANTILLA" VARCHAR2(30) DEFAULT 'CARTA') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "RUTA" ("IDRUTA" NUMBER(10,0), "ORIGEN" NUMBER(30,0) DEFAULT '0', "TIPO" VARCHAR2(4000) DEFAULT 'ACTIVO', "DESTINO" NUMBER(30,0) DEFAULT '0', "IDTIPO_DOCUMENTAL" NUMBER(10,0), "CONDICION_TRANSFERENCIA" VARCHAR2(4000), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0), "FECHA" DATE DEFAULT SYSDATE, "TRANSFERENCIA_IDTRANSFERENCIA" NUMBER(10,0), "ORDEN" NUMBER(10,0) DEFAULT '0', "TIPO_ORIGEN" NUMBER(10,0) DEFAULT '0', "TIPO_DESTINO" NUMBER(10,0) DEFAULT '0', "OBLIGATORIO" NUMBER(3,0) DEFAULT '1', "RESTRICTIVO" NUMBER(3,0) DEFAULT '0', "IDENLACE_NODO" NUMBER, "CLASE" NUMBER(1,0) DEFAULT '1') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 11534336 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "SALIDAS" ("IDSALIDA" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "NUMERO_GUIA" VARCHAR2(50) DEFAULT 0, "EMPRESA" NUMBER(10,0) DEFAULT '0', "RESPONSABLE" NUMBER(10,0) DEFAULT '0', "FECHA_DESPACHO" DATE, "TIPO_DESPACHO" VARCHAR2(255) DEFAULT NULL) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "SERIE" ("IDSERIE" NUMBER(10,0), "NOMBRE" VARCHAR2(255), "COD_PADRE" NUMBER(10,0), "DIAS_ENTREGA" NUMBER(10,0) DEFAULT '8', "CODIGO" VARCHAR2(20), "RETENCION_GESTION" NUMBER(3,0), "RETENCION_CENTRAL" NUMBER(3,0), "CONSERVACION" VARCHAR2(4000), "DIGITALIZACION" NUMBER(3,0), "SELECCION" NUMBER(3,0), "OTRO" VARCHAR2(255), "PROCEDIMIENTO" CLOB, "COPIA" NUMBER(3,0) DEFAULT 0, "MAX_PRESTAMO" NUMBER(10,0) DEFAULT 4, "TIPO" NUMBER(4,0) DEFAULT 1, "ESTADO" NUMBER(3,0) DEFAULT 1, "TIPO_ENTIDAD" NUMBER DEFAULT null, "CATEGORIA" VARCHAR2(20) DEFAULT 2) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("PROCEDIMIENTO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));
CREATE TABLE "SOLICITUD" ("IDSOLICITUD" NUMBER(10,0), "DOCUMENTO_IDDOCUMENTO" NUMBER(10,0) DEFAULT '0', "INVESTIGADOR_IDINVESTIGADOR" NUMBER(10,0) DEFAULT '0', "FECHA" DATE, "ESTADO_DOCUMENTO" VARCHAR2(255), "DESCRIPCION" VARCHAR2(255), "SOLICITAR_A" NUMBER(10,0) DEFAULT '0', "ESTADO" VARCHAR2(255), "IDALMACENAMIENTO" NUMBER(10,0), "RESERVADO" NUMBER(1,0) DEFAULT null) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "TAREA" ("IDTAREA" NUMBER(10,0), "NOMBRE" VARCHAR2(250), "FECHA" DATE DEFAULT SYSDATE, "RESPUESTA" DATE DEFAULT TO_DATE('01-06-70 00:00:00', 'dd-MM-yy hh24:mi:ss'), "DESCRIPCION" VARCHAR2(200), "TIPO_REPROGRAMA" VARCHAR2(30), "REPROGRAMA" NUMBER(4,0), "TIEMPO_RESPUESTA" NUMBER DEFAULT '0') PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS";
CREATE TABLE "VISTA_FORMATO" ("IDVISTA_FORMATO" NUMBER, "NOMBRE" VARCHAR2(255), "ETIQUETA" VARCHAR2(255), "FORMATO_PADRE" NUMBER DEFAULT 0, "RUTA_MOSTRAR" VARCHAR2(255), "LIBRERIAS" VARCHAR2(255) DEFAULT null, "ESTILOS" VARCHAR2(255) DEFAULT null, "JAVASCRIPT" VARCHAR2(255) DEFAULT null, "ENCABEZADO" VARCHAR2(4000), "PIE_PAGINA" VARCHAR2(4000), "MARGENES" VARCHAR2(50) DEFAULT '30,30,30,30', "ORIENTACION" VARCHAR2(50), "PAPEL" VARCHAR2(50) DEFAULT 'letter', "EXPORTAR" VARCHAR2(255) DEFAULT 'pdf', "FUNCIONARIO_IDFUNCIONARIO" NUMBER DEFAULT 0, "FECHA" DATE DEFAULT sysdate, "IMAGEN" VARCHAR2(1), "AYUDA" VARCHAR2(400), "CUERPO" CLOB DEFAULT empty_clob(), "FONT_SIZE" VARCHAR2(5) DEFAULT '12', "BANDERAS" VARCHAR2(255) DEFAULT 'm') PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "SAIANUEVO_DATOS"  LOB ("CUERPO") STORE AS ( TABLESPACE "SAIANUEVO_DATOS" ENABLE STORAGE IN ROW CHUNK 16384 PCTVERSION 10 NOCACHE LOGGING  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT));

--TRIGGERs
CREATE OR REPLACE TRIGGER "ACCION_IDACCION_TRG" BEFORE INSERT OR UPDATE ON accion
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idaccion IS NULL THEN
  SELECT accion_SEQ.NEXTVAL INTO :NEW.idaccion FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "ACCION_IDACCION_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ACCION_TRG" BEFORE INSERT OR UPDATE ON accion
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idaccion IS NULL THEN
  SELECT accion_SEQ.NEXTVAL INTO :NEW.idaccion FROM DUAL;
  END IF;
END;
ALTER TRIGGER "ACCION_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ALMACENAMIENTO_IDALMACENAMIENT" BEFORE INSERT OR UPDATE ON almacenamiento
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idalmacenamiento IS NULL THEN
  SELECT almacenamiento_SEQ.NEXTVAL INTO :NEW.idalmacenamiento FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "ALMACENAMIENTO_IDALMACENAMIENT" ENABLE;

CREATE OR REPLACE TRIGGER "ANEXOS_IDANEXOS_TRG" BEFORE INSERT OR UPDATE ON anexos
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idanexos IS NULL THEN
  SELECT anexos_SEQ.NEXTVAL INTO :NEW.idanexos FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "ANEXOS_IDANEXOS_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ASIGNACION_ENTIDAD_TRG" BEFORE INSERT OR UPDATE ON ASIGNACION_ENTIDAD
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idasignacion_entidad IS NULL THEN
  SELECT ASIG_ENTIDAD_SEQ.NEXTVAL INTO :NEW.idasignacion_entidad FROM DUAL;
  END IF;
END;
ALTER TRIGGER "ASIGNACION_ENTIDAD_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ASIGNACION_TERMINAR_TRG" BEFORE INSERT OR UPDATE ON ASIGNACION_TERMINAR
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idasignacion_terminar IS NULL THEN
  SELECT ASIGNACION_TERMINAR_SEQ.NEXTVAL INTO :NEW.IDASIGNACION_TERMINAR FROM DUAL;
  END IF;
END;
ALTER TRIGGER "ASIGNACION_TERMINAR_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ASIGNACION_IDASIGNACION" BEFORE INSERT OR UPDATE ON asignacion
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idasignacion IS NULL THEN
  SELECT ASIGNACION_SEQ.NEXTVAL INTO :NEW.idasignacion FROM DUAL;
  END IF;
END;

ALTER TRIGGER "ASIGNACION_IDASIGNACION" ENABLE;

CREATE OR REPLACE TRIGGER "BINARIO_TRG" BEFORE INSERT OR UPDATE ON BINARIO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idBINARIO IS NULL THEN
  SELECT BINARIO_SEQ.NEXTVAL INTO :NEW.idBINARIO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "BINARIO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_ENTRADA_IDTRANSFERENCIA_" BEFORE INSERT OR UPDATE ON buzon_entrada
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idtransferencia IS NULL THEN
  SELECT buzon_entrada_SEQ.NEXTVAL INTO :NEW.idtransferencia FROM DUAL;
  END IF;
END;
ALTER TRIGGER "BUZON_ENTRADA_IDTRANSFERENCIA_" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_ENTRADA_NOMBRE_ETRG" 
BEFORE INSERT OR UPDATE
ON BUZON_ENTRADA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
v_val buzon_entrada.nombre%TYPE;
v_test buzon_entrada.nombre%TYPE;
BEGIN
v_val := 'LEIDO';
v_test := TRIM(:NEW.nombre);
IF v_test = '1' OR v_test = 'LEIDO' THEN
v_val := 'LEIDO';
ELSIF v_test = '2' OR v_test = 'COPIA' THEN
v_val := 'COPIA';
ELSIF v_test = '3' OR v_test = 'HISTORICO' THEN
v_val := 'HISTORICO';
ELSIF v_test = '4' OR v_test = 'GESTION' THEN
v_val := 'GESTION';
ELSIF v_test = '5' OR v_test = 'CENTRAL' THEN
v_val := 'CENTRAL';
ELSIF v_test = '6' OR v_test = 'BLOQUEADO' THEN
v_val := 'BLOQUEADO';
ELSIF v_test = '7' OR v_test = 'RECHAZADO' THEN
v_val := 'RECHAZADO';
ELSIF v_test = '8' OR v_test = 'POR_APROBAR' THEN
v_val := 'POR_APROBAR';
ELSIF v_test = '9' OR v_test = 'RECEPCION' THEN
v_val := 'RECEPCION';
ELSIF v_test = '10' OR v_test = 'PRODUCCION' THEN
v_val := 'PRODUCCION';
ELSIF v_test = '11' OR v_test = 'DISTRIBUCION' THEN
v_val := 'DISTRIBUCION';
ELSIF v_test = '12' OR v_test = 'CONSULTA' THEN
v_val := 'CONSULTA';
ELSIF v_test = '13' OR v_test = 'RETENCION' THEN
v_val := 'RETENCION';
ELSIF v_test = '14' OR v_test = 'ALMACENAMIENTO' THEN
v_val := 'ALMACENAMIENTO';
ELSIF v_test = '15' OR v_test = 'RECUPERACION' THEN
v_val := 'RECUPERACION';
ELSIF v_test = '16' OR v_test = 'PRESERVACION' THEN
v_val := 'PRESERVACION';
ELSIF v_test = '17' OR v_test = 'DISPOSICION FINAL' THEN
v_val := 'DISPOSICION FINAL';
ELSIF v_test = '18' OR v_test = 'REVISADO' THEN
v_val := 'REVISADO';
ELSIF v_test = '19' OR v_test = 'APROBADO' THEN
v_val := 'APROBADO';
ELSIF v_test = '20' OR v_test = 'DEVOLUCION' THEN
v_val := 'DEVOLUCION';
ELSIF v_test = '21' OR v_test = 'TRAMITE' THEN
v_val := 'TRAMITE';
ELSIF v_test = '22' OR v_test = 'TRANSFERIDO' THEN
v_val := 'TRANSFERIDO';
ELSIF v_test = '23' OR v_test = 'BORRADOR' THEN
v_val := 'BORRADOR';
ELSIF v_test = '24' OR v_test = 'VERIFICACION' THEN
v_val := 'VERIFICACION';
ELSIF v_test = '25' OR v_test = 'TERMINADO' THEN
v_val := 'TERMINADO';
ELSIF v_test = '31' OR v_test = 'ELIMINA_LEIDO' THEN
v_val := 'ELIMINA_LEIDO';
ELSIF v_test = '32' OR v_test = 'ELIMINA_COPIA' THEN
v_val := 'ELIMINA_COPIA';
ELSIF v_test = '26' OR v_test = 'ELIMINA_BLOQUEADO' THEN
v_val := 'ELIMINA_BLOQUEADO';
ELSIF v_test = '27' OR v_test = 'ELIMINA_RECHAZADO' THEN
v_val := 'ELIMINA_RECHAZADO';
ELSIF v_test = '28' OR v_test = 'ELIMINA_POR_APROBAR' THEN
v_val := 'ELIMINA_POR_APROBAR';
ELSIF v_test = '30' OR v_test = 'ELIMINA_REVISADO' THEN
v_val := 'ELIMINA_REVISADO';
ELSIF v_test = '29' OR v_test = 'ELIMINA_APROBADO' THEN
v_val := 'ELIMINA_APROBADO';
ELSIF v_test = '37' OR v_test = 'ELIMINA_DEVOLUCION' THEN
v_val := 'ELIMINA_DEVOLUCION';
ELSIF v_test = '36' OR v_test = 'ELIMINA_TRANSFERIDO' THEN
v_val := 'ELIMINA_TRANSFERIDO';
ELSIF v_test = '33' OR v_test = 'ELIMINA_BORRADOR' THEN
v_val := 'ELIMINA_BORRADOR';
ELSIF v_test = '34' OR v_test = 'ELIMINA_VERIFICACION' THEN
v_val := 'ELIMINA_VERIFICACION';
ELSIF v_test = '35' OR v_test = 'ELIMINA_TERMINADO' THEN
v_val := 'ELIMINA_TERMINADO';
ELSIF v_test = '36' OR v_test = 'RESPONDIDO' THEN
v_val := 'RESPONDIDO';
ELSIF v_test = '37' OR v_test = 'ELIMINADO' THEN
v_val := 'ELIMINADO';
ELSIF v_test = '38' OR v_test = 'DELEGADO' THEN
v_val := 'DELEGADO';
END IF; :NEW.nombre := v_val;
END;
ALTER TRIGGER "BUZON_ENTRADA_NOMBRE_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_ENTRADA_TIPO_ETRG" 
BEFORE INSERT OR UPDATE ON buzon_entrada
FOR EACH ROW
DECLARE
  v_val buzon_entrada.tipo%TYPE;
  v_test buzon_entrada.tipo%TYPE;
BEGIN
  v_val := 'ARCHIVO';
  v_test := TRIM(:NEW.tipo);
  IF v_test = '1' OR v_test = 'ARCHIVO' THEN
  v_val := 'ARCHIVO';
  ELSIF v_test = '2' OR v_test = 'DOCUMENTO' THEN
  v_val := 'DOCUMENTO';
  END IF;  :NEW.tipo := v_val;
END;
ALTER TRIGGER "BUZON_ENTRADA_TIPO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_SALIDA_IDTRANSFERENCIA_T" BEFORE INSERT OR UPDATE ON buzon_salida
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idtransferencia IS NULL THEN
  SELECT buzon_salida_SEQ.NEXTVAL INTO :NEW.idtransferencia FROM DUAL;
  END IF;
END;

ALTER TRIGGER "BUZON_SALIDA_IDTRANSFERENCIA_T" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_SALIDA_NOMBRE_ETRG" 
BEFORE INSERT OR UPDATE
ON BUZON_SALIDA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
v_val buzon_salida.nombre%TYPE;
v_test buzon_salida.nombre%TYPE;
BEGIN
v_val := 'LEIDO';
v_test := TRIM(:NEW.nombre);
IF v_test = '1' OR v_test = 'LEIDO' THEN
v_val := 'LEIDO';
ELSIF v_test = '2' OR v_test = 'COPIA' THEN
v_val := 'COPIA';
ELSIF v_test = '3' OR v_test = 'HISTORICO' THEN
v_val := 'HISTORICO';
ELSIF v_test = '4' OR v_test = 'GESTION' THEN
v_val := 'GESTION';
ELSIF v_test = '5' OR v_test = 'CENTRAL' THEN
v_val := 'CENTRAL';
ELSIF v_test = '6' OR v_test = 'BLOQUEADO' THEN
v_val := 'BLOQUEADO';
ELSIF v_test = '7' OR v_test = 'RECHAZADO' THEN
v_val := 'RECHAZADO';
ELSIF v_test = '8' OR v_test = 'POR_APROBAR' THEN
v_val := 'POR_APROBAR';
ELSIF v_test = '9' OR v_test = 'RECEPCION' THEN
v_val := 'RECEPCION';
ELSIF v_test = '10' OR v_test = 'PRODUCCION' THEN
v_val := 'PRODUCCION';
ELSIF v_test = '11' OR v_test = 'DISTRIBUCION' THEN
v_val := 'DISTRIBUCION';
ELSIF v_test = '12' OR v_test = 'CONSULTA' THEN
v_val := 'CONSULTA';
ELSIF v_test = '13' OR v_test = 'RETENCION' THEN
v_val := 'RETENCION';
ELSIF v_test = '14' OR v_test = 'ALMACENAMIENTO' THEN
v_val := 'ALMACENAMIENTO';
ELSIF v_test = '15' OR v_test = 'RECUPERACION' THEN
v_val := 'RECUPERACION';
ELSIF v_test = '16' OR v_test = 'PRESERVACION' THEN
v_val := 'PRESERVACION';
ELSIF v_test = '17' OR v_test = 'DISPOSICION FINAL' THEN
v_val := 'DISPOSICION FINAL';
ELSIF v_test = '18' OR v_test = 'REVISADO' THEN
v_val := 'REVISADO';
ELSIF v_test = '19' OR v_test = 'APROBADO' THEN
v_val := 'APROBADO';
ELSIF v_test = '20' OR v_test = 'DEVOLUCION' THEN
v_val := 'DEVOLUCION';
ELSIF v_test = '21' OR v_test = 'TRAMITE' THEN
v_val := 'TRAMITE';
ELSIF v_test = '22' OR v_test = 'TRANSFERIDO' THEN
v_val := 'TRANSFERIDO';
ELSIF v_test = '23' OR v_test = 'BORRADOR' THEN
v_val := 'BORRADOR';
ELSIF v_test = '24' OR v_test = 'VERIFICACION' THEN
v_val := 'VERIFICACION';
ELSIF v_test = '25' OR v_test = 'TERMINADO' THEN
v_val := 'TERMINADO';
ELSIF v_test = '31' OR v_test = 'ELIMINA_LEIDO' THEN
v_val := 'ELIMINA_LEIDO';
ELSIF v_test = '32' OR v_test = 'ELIMINA_COPIA' THEN
v_val := 'ELIMINA_COPIA';
ELSIF v_test = '26' OR v_test = 'ELIMINA_BLOQUEADO' THEN
v_val := 'ELIMINA_BLOQUEADO';
ELSIF v_test = '27' OR v_test = 'ELIMINA_RECHAZADO' THEN
v_val := 'ELIMINA_RECHAZADO';
ELSIF v_test = '28' OR v_test = 'ELIMINA_POR_APROBAR' THEN
v_val := 'ELIMINA_POR_APROBAR';
ELSIF v_test = '30' OR v_test = 'ELIMINA_REVISADO' THEN
v_val := 'ELIMINA_REVISADO';
ELSIF v_test = '29' OR v_test = 'ELIMINA_APROBADO' THEN
v_val := 'ELIMINA_APROBADO';
ELSIF v_test = '37' OR v_test = 'ELIMINA_DEVOLUCION' THEN
v_val := 'ELIMINA_DEVOLUCION';
ELSIF v_test = '36' OR v_test = 'ELIMINA_TRANSFERIDO' THEN
v_val := 'ELIMINA_TRANSFERIDO';
ELSIF v_test = '33' OR v_test = 'ELIMINA_BORRADOR' THEN
v_val := 'ELIMINA_BORRADOR';
ELSIF v_test = '34' OR v_test = 'ELIMINA_VERIFICACION' THEN
v_val := 'ELIMINA_VERIFICACION';
ELSIF v_test = '35' OR v_test = 'ELIMINA_TERMINADO' THEN
v_val := 'ELIMINA_TERMINADO';
ELSIF v_test = '36' OR v_test = 'RESPONDIDO' THEN
v_val := 'RESPONDIDO';
ELSIF v_test = '37' OR v_test = 'ELIMINADO' THEN
v_val := 'ELIMINADO';
ELSIF v_test = '38' OR v_test = 'DELEGADO' THEN
v_val := 'DELEGADO';
END IF; :NEW.nombre := v_val;
END;

ALTER TRIGGER "BUZON_SALIDA_NOMBRE_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "BUZON_SALIDA_TIPO_ETRG" 
BEFORE INSERT OR UPDATE ON buzon_salida
FOR EACH ROW
DECLARE
  v_val buzon_salida.tipo%TYPE;
  v_test buzon_salida.tipo%TYPE;
BEGIN
  v_val := 'ARCHIVO';
  v_test := TRIM(:NEW.tipo);
  IF v_test = '1' OR v_test = 'ARCHIVO' THEN
  v_val := 'ARCHIVO';
  ELSIF v_test = '2' OR v_test = 'DOCUMENTO' THEN
  v_val := 'DOCUMENTO';
  END IF;  :NEW.tipo := v_val;
END;

ALTER TRIGGER "BUZON_SALIDA_TIPO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "CAJA_IDCAJA_TRG" BEFORE INSERT OR UPDATE ON caja
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcaja IS NULL THEN
  SELECT caja_SEQ.NEXTVAL INTO :NEW.idcaja FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "CAJA_IDCAJA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CAMPOS_FORMATO_TRG" BEFORE INSERT OR UPDATE ON CAMPOS_FORMATO
FOR EACH ROW
BEGIN
IF INSERTING AND :NEW.idcampos_formato IS NULL THEN
SELECT campos_formato_SEQ.NEXTVAL INTO :NEW.idcampos_formato FROM DUAL;
END IF;
END;
ALTER TRIGGER "CAMPOS_FORMATO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CAMPOS_TIPO_ETRG" 
BEFORE INSERT OR UPDATE ON campos
FOR EACH ROW
DECLARE
v_val campos.tipo%TYPE;
v_test campos.tipo%TYPE;
BEGIN
v_val := 'TEXT';
v_test := TRIM(:NEW.tipo);
IF v_test = '1' OR v_test = 'TEXT' THEN
v_val := 'TEXT';
ELSIF v_test = '2' OR v_test = 'AUTOCOMPLETAR' THEN
v_val := 'AUTOCOMPLETAR';
ELSIF v_test = '3' OR v_test = 'FECHA' THEN
v_val := 'FECHA';
ELSIF v_test = '4' OR v_test = 'RADIO' THEN
v_val := 'RADIO';
ELSIF v_test = '5' OR v_test = 'CHECKBOX' THEN
v_val := 'CHECKBOX';
ELSIF v_test = '6' OR v_test = 'SELECT' THEN
v_val := 'SELECT';
END IF; :NEW.tipo := v_val;
END; 
ALTER TRIGGER "CAMPOS_TIPO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "CAMPOS_TRG" BEFORE INSERT OR UPDATE ON CAMPOS
FOR EACH ROW
BEGIN
IF INSERTING AND :NEW.idCAMPOS IS NULL THEN
SELECT CAMPOS_SEQ.NEXTVAL INTO :NEW.idCAMPOS FROM DUAL;
END IF;
END;
ALTER TRIGGER "CAMPOS_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CARACTERISTICAS_CAMPOS_TRG" BEFORE INSERT OR UPDATE ON CARACTERISTICAS_CAMPOS
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idCARACTERISTICAS_CAMPOS IS NULL THEN
  SELECT CARACTERISTICAS_CAMPOS_SEQ.NEXTVAL INTO :NEW.idCARACTERISTICAS_CAMPOS FROM DUAL;
  END IF;
END;
ALTER TRIGGER "CARACTERISTICAS_CAMPOS_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CARGO_IDCARGO_TRG" BEFORE INSERT OR UPDATE ON cargo
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcargo IS NULL THEN
  SELECT cargo_SEQ.NEXTVAL INTO :NEW.idcargo FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "CARGO_IDCARGO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CARRUSEL_TRG" BEFORE INSERT OR UPDATE ON carrusel
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcarrusel IS NULL THEN
  SELECT carrusel_SEQ.NEXTVAL INTO :NEW.idcarrusel FROM DUAL;
  END IF;
END;
ALTER TRIGGER "CARRUSEL_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "COMENTARIO_IMG_IDCOMENTARIO_IM" BEFORE INSERT OR UPDATE ON comentario_img
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcomentario_img IS NULL THEN
  SELECT comentario_img_SEQ.NEXTVAL INTO :NEW.idcomentario_img FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "COMENTARIO_IMG_IDCOMENTARIO_IM" ENABLE;

CREATE OR REPLACE TRIGGER "CONFIGURACION_IDCONFIGURACION_" BEFORE INSERT OR UPDATE ON configuracion
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idconfiguracion IS NULL THEN
  SELECT configuracion_SEQ.NEXTVAL INTO :NEW.idconfiguracion FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "CONFIGURACION_IDCONFIGURACION_" ENABLE;

CREATE OR REPLACE TRIGGER "CONTADOR_IDCONTADOR_TRG" BEFORE INSERT OR UPDATE ON contador
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcontador IS NULL THEN
  SELECT contador_SEQ.NEXTVAL INTO :NEW.idcontador FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "CONTADOR_IDCONTADOR_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "CONTENIDOS_CARRUSEL_TRG" BEFORE INSERT OR UPDATE ON contenidos_carrusel
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idcontenidos_carrusel IS NULL THEN
  SELECT contenidos_carrusel_SEQ.NEXTVAL INTO :NEW.idcontenidos_carrusel FROM DUAL;
  END IF;
END;
ALTER TRIGGER "CONTENIDOS_CARRUSEL_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DATOS_EJECUTOR_TRG" BEFORE INSERT OR UPDATE ON DATOS_EJECUTOR
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idDATOS_EJECUTOR IS NULL THEN
  SELECT DATOS_EJECUTOR_SEQ.NEXTVAL INTO :NEW.idDATOS_EJECUTOR FROM DUAL;
  END IF;
END;
ALTER TRIGGER "DATOS_EJECUTOR_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DEPARTAMENTO_IDDEPARTAMENTO_TR" BEFORE INSERT OR UPDATE ON departamento
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddepartamento IS NULL THEN
  SELECT departamento_SEQ.NEXTVAL INTO :NEW.iddepartamento FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "DEPARTAMENTO_IDDEPARTAMENTO_TR" ENABLE;

CREATE OR REPLACE TRIGGER "DEPENDENCIA_CARGO_IDDEPENDENCI" BEFORE INSERT OR UPDATE ON dependencia_cargo
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddependencia_cargo IS NULL THEN
  SELECT dependencia_cargo_SEQ.NEXTVAL INTO :NEW.iddependencia_cargo FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "DEPENDENCIA_CARGO_IDDEPENDENCI" ENABLE;

CREATE OR REPLACE TRIGGER "DEPENDENCIA_IDDEPENDENCIA_TRG" BEFORE INSERT OR UPDATE ON dependencia
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddependencia IS NULL THEN
  SELECT dependencia_SEQ.NEXTVAL INTO :NEW.iddependencia FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "DEPENDENCIA_IDDEPENDENCIA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DIGITALIZACION_TRG" BEFORE INSERT OR UPDATE ON DIGITALIZACION
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idDIGITALIZACION IS NULL THEN
  SELECT DIGITALIZACION_SEQ.NEXTVAL INTO :NEW.idDIGITALIZACION FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "DIGITALIZACION_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DOCUMENTO_ANEXO_ETRG" 
BEFORE INSERT OR UPDATE ON documento
FOR EACH ROW
DECLARE
  v_val documento.anexo%TYPE;
  v_test documento.anexo%TYPE;
BEGIN
  v_val := NULL;
  v_test := TRIM(:NEW.anexo);
  IF v_test = '1' OR v_test = 'PAPEL' THEN
  v_val := 'PAPEL';
  ELSIF v_test = '2' OR v_test = 'FAX' THEN
  v_val := 'FAX';
  ELSIF v_test = '3' OR v_test = 'CONSIGNACION' THEN
  v_val := 'CONSIGNACION';
  ELSIF v_test = '4' OR v_test = 'CONSIGNACION ORIGINAL' THEN
  v_val := 'CONSIGNACION ORIGINAL';
  ELSIF v_test = '5' OR v_test = 'DISKETES' THEN
  v_val := 'DISKETES';
  ELSIF v_test = '6' OR v_test = 'CD-ROM' THEN
  v_val := 'CD-ROM';
  ELSIF v_test = '7' OR v_test = 'DVD' THEN
  v_val := 'DVD';
  ELSIF v_test = '8' OR v_test = 'VIDEO' THEN
  v_val := 'VIDEO';
  ELSIF v_test = '9' OR v_test = 'MICROFILMINAS' THEN
  v_val := 'MICROFILMINAS';
  END IF;  :NEW.anexo := v_val;
END; 
ALTER TRIGGER "DOCUMENTO_ANEXO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "DOCUMENTO_ESTADO_ETRG" 
BEFORE INSERT OR UPDATE ON documento
FOR EACH ROW
DECLARE
  v_val documento.estado%TYPE;
  v_test documento.estado%TYPE;
BEGIN
  v_val := 'INICIADO';
  v_test := TRIM(:NEW.estado);
  IF v_test = '1' OR v_test = 'INICIADO' THEN
  v_val := 'INICIADO';
  ELSIF v_test = '2' OR v_test = 'HISTORICO' THEN
  v_val := 'HISTORICO';
  ELSIF v_test = '3' OR v_test = 'APROBADO' THEN
  v_val := 'APROBADO';
  ELSIF v_test = '4' OR v_test = 'PERMANENTE' THEN
  v_val := 'PERMANENTE';
  ELSIF v_test = '5' OR v_test = 'GESTION' THEN
  v_val := 'GESTION';
  ELSIF v_test = '6' OR v_test = 'CENTRAL' THEN
  v_val := 'CENTRAL';
  ELSIF v_test = '7' OR v_test = 'RECHAZADO' THEN
  v_val := 'RECHAZADO';
  ELSIF v_test = '8' OR v_test = 'ACTIVO' THEN
  v_val := 'ACTIVO';
  ELSIF v_test = '9' OR v_test = 'TERMINADO' THEN
  v_val := 'TERMINADO';
  ELSIF v_test = '10' OR v_test = 'PROGRAMADO' THEN
  v_val := 'PROGRAMADO';
  ELSIF v_test = '11' OR v_test = 'INACTIVO' THEN
  v_val := 'INACTIVO';
  ELSIF v_test = '12' OR v_test = 'ELIMINADO' THEN
  v_val := 'ELIMINADO';
  ELSIF v_test = '13' OR v_test = 'TRAMITE' THEN
  v_val := 'TRAMITE';
  END IF;  :NEW.estado := v_val;
END;
ALTER TRIGGER "DOCUMENTO_ESTADO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "DOCUMENTO_ETIQUETA_TRG" BEFORE INSERT OR UPDATE ON documento_etiqueta
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddocumento_etiqueta IS NULL THEN
  SELECT documento_etiqueta_SEQ.NEXTVAL INTO :NEW.iddocumento_etiqueta FROM DUAL;
  END IF;
END;
ALTER TRIGGER "DOCUMENTO_ETIQUETA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DOCUMENTO_IDDOCUMENTO_TRG" BEFORE INSERT OR UPDATE ON documento
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddocumento IS NULL THEN
  SELECT documento_SEQ.NEXTVAL INTO :NEW.iddocumento FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "DOCUMENTO_IDDOCUMENTO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "DOCUMENTO_VERSION_TRG" BEFORE INSERT OR UPDATE ON DOCUMENTO_VERSION FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.iddocumento_version IS NULL THEN
  SELECT DOCUMENTO_VERSION_SEQ.NEXTVAL INTO :NEW.iddocumento_version FROM DUAL;
  END IF;
END;
ALTER TRIGGER "DOCUMENTO_VERSION_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "EJECUTOR_IDEJECUTOR_TRG" BEFORE INSERT OR UPDATE ON EJECUTOR FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idejecutor IS NULL THEN
  SELECT ejecutor_SEQ.NEXTVAL INTO :NEW.idejecutor FROM DUAL;
  END IF;
END;

ALTER TRIGGER "EJECUTOR_IDEJECUTOR_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ENCABEZADO_FORMATO_TRG" BEFORE INSERT OR UPDATE ON ENCABEZADO_FORMATO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idENCABEZADO_FORMATO IS NULL THEN
  SELECT ENCABEZADO_FORMATO_SEQ.NEXTVAL INTO :NEW.idENCABEZADO_FORMATO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "ENCABEZADO_FORMATO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ENTIDAD_IDENTIDAD_TRG" BEFORE INSERT OR UPDATE ON entidad
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.identidad IS NULL THEN
  SELECT entidad_SEQ.NEXTVAL INTO :NEW.identidad FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "ENTIDAD_IDENTIDAD_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ENTIDAD_PRETEXTO_IDPRETEXT_TRG" BEFORE INSERT OR UPDATE ON entidad_pretexto
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.identidad_pretexto IS NULL THEN
  SELECT ENTIDAD_PRETEXTO_SEQ.NEXTVAL INTO :NEW.identidad_pretexto FROM DUAL;
  END IF;
END;
ALTER TRIGGER "ENTIDAD_PRETEXTO_IDPRETEXT_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ENTIDAD_SERIE_TRG" BEFORE INSERT OR UPDATE ON ENTIDAD_SERIE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.identidad_serie IS NULL THEN
  SELECT ENTIDAD_SERIE_SEQ.NEXTVAL INTO :NEW.identidad_serie FROM DUAL;
  END IF;
END;

ALTER TRIGGER "ENTIDAD_SERIE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "EST_SAIA_IDEST_SAIA_TRG" BEFORE INSERT OR UPDATE ON estadisticas_saia
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idestadisticas_saia IS NULL THEN
  SELECT estadisticas_saia_SEQ.NEXTVAL INTO :NEW.idestadisticas_saia FROM DUAL;
  END IF;
END;
ALTER TRIGGER "EST_SAIA_IDEST_SAIA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "ETIQUETA_TRG" BEFORE INSERT OR UPDATE ON ETIQUETA
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idetiqueta IS NULL THEN
  SELECT etiqueta_SEQ.NEXTVAL INTO :NEW.idetiqueta FROM DUAL;
  END IF;
END;

ALTER TRIGGER "ETIQUETA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "EVENTO_EVENTO_ETRG" 
BEFORE INSERT OR UPDATE ON evento
FOR EACH ROW
DECLARE
  v_val evento.evento%TYPE;
  v_test evento.evento%TYPE;
BEGIN
  v_val := 'ADICIONAR';
  v_test := TRIM(:NEW.evento);
  IF v_test = '1' OR v_test = 'ADICIONAR' THEN
  v_val := 'ADICIONAR';
  ELSIF v_test = '2' OR v_test = 'MODIFICAR' THEN
  v_val := 'MODIFICAR';
  ELSIF v_test = '3' OR v_test = 'ELIMINAR' THEN
  v_val := 'ELIMINAR';
  END IF;  :NEW.evento := v_val;
END; 

ALTER TRIGGER "EVENTO_EVENTO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "EVENTO_IDEVENTO_TRG" BEFORE INSERT OR UPDATE ON evento
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idevento IS NULL THEN
  SELECT evento_SEQ.NEXTVAL INTO :NEW.idevento FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "EVENTO_IDEVENTO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "EXPEDIENTE_DOC_TRG" BEFORE INSERT OR UPDATE ON EXPEDIENTE_DOC
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idEXPEDIENTE_DOC IS NULL THEN
  SELECT EXPEDIENTE_DOC_SEQ.NEXTVAL INTO :NEW.idEXPEDIENTE_DOC FROM DUAL;
  END IF;
END;
ALTER TRIGGER "EXPEDIENTE_DOC_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "EXPEDIENTE_TRG" BEFORE INSERT OR UPDATE ON EXPEDIENTE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idEXPEDIENTE IS NULL THEN
  SELECT EXPEDIENTE_SEQ.NEXTVAL INTO :NEW.idEXPEDIENTE FROM DUAL;
  END IF;
END;
ALTER TRIGGER "EXPEDIENTE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FILTRO_GRAFICA_TRG" BEFORE INSERT OR UPDATE ON filtro_grafica
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idfiltro_grafica IS NULL THEN
  SELECT filtro_grafica_SEQ.NEXTVAL INTO :NEW.idfiltro_grafica FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "FILTRO_GRAFICA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FILTRO_REPORTE_TRG" BEFORE INSERT OR UPDATE ON filtro_reporte
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idfiltro_reporte IS NULL THEN
  SELECT filtro_reporte_SEQ.NEXTVAL INTO :NEW.idfiltro_reporte FROM DUAL;
  END IF;
END;
ALTER TRIGGER "FILTRO_REPORTE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FOLDER_IDFOLDER_TRG" BEFORE INSERT OR UPDATE ON folder
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idfolder IS NULL THEN
  SELECT folder_SEQ.NEXTVAL INTO :NEW.idfolder FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "FOLDER_IDFOLDER_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FORMATO_TRG" BEFORE INSERT OR UPDATE ON FORMATO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idFORMATO IS NULL THEN
  SELECT FORMATO_SEQ.NEXTVAL INTO :NEW.idFORMATO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "FORMATO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FT_CARTA_TRG" BEFORE INSERT OR UPDATE ON FT_CARTA FOR EACH ROW BEGIN IF INSERTING AND :NEW.IDFT_CARTA IS NULL THEN SELECT FT_CARTA_SEQ.NEXTVAL INTO :NEW.IDFT_CARTA FROM DUAL; END IF; END;
ALTER TRIGGER "FT_CARTA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FT_MEMORANDO_TRG" BEFORE INSERT OR UPDATE ON FT_MEMORANDO FOR EACH ROW BEGIN IF INSERTING AND :NEW.IDFT_MEMORANDO IS NULL THEN SELECT FT_MEMORANDO_SEQ.NEXTVAL INTO :NEW.IDFT_MEMORANDO FROM DUAL; END IF; END;
ALTER TRIGGER "FT_MEMORANDO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FUNC_FORMATO_ACCION_TRG" BEFORE INSERT OR UPDATE ON FUNCIONES_FORMATO_ACCION
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idFUNCIONES_FORMATO_ACCION IS NULL THEN
  SELECT FUNC_FORMATO_ACCION_SEQ.NEXTVAL INTO :NEW.idFUNCIONES_FORMATO_ACCION FROM DUAL;
  END IF;
END;
ALTER TRIGGER "FUNC_FORMATO_ACCION_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FUNCIONARIO_IDFUNCIONARIO_TRG" BEFORE INSERT OR UPDATE ON funcionario
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idfuncionario IS NULL THEN
  SELECT funcionario_SEQ.NEXTVAL INTO :NEW.idfuncionario FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "FUNCIONARIO_IDFUNCIONARIO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FUNCIONES_BUSQUEDA_TRG" BEFORE INSERT OR UPDATE ON FUNCIONES_BUSQUEDA
FOR EACH ROW
BEGIN
IF INSERTING AND :NEW.idFUNCIONES_BUSQUEDA IS NULL THEN
SELECT FUNCIONES_BUSQUEDA_SEQ.NEXTVAL INTO :NEW.idFUNCIONES_BUSQUEDA FROM DUAL;
END IF;
END;

ALTER TRIGGER "FUNCIONES_BUSQUEDA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "FUNCIONES_FORMATO_TRG" BEFORE INSERT OR UPDATE ON FUNCIONES_FORMATO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idFUNCIONES_FORMATO IS NULL THEN
  SELECT FUNCIONES_FORMATO_SEQ.NEXTVAL INTO :NEW.idFUNCIONES_FORMATO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "FUNCIONES_FORMATO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "GRAFICO_TRG" BEFORE INSERT OR UPDATE ON GRAFICO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idGRAFICO IS NULL THEN
  SELECT GRAFICO_SEQ.NEXTVAL INTO :NEW.idGRAFICO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "GRAFICO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "IDAUTOGUARDADO_TRG" BEFORE INSERT OR UPDATE ON AUTOGUARDADO
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.idAUTOGUARDADO IS NULL
    THEN
    SELECT AUTOGUARDADO_seq.NEXTVAL INTO :NEW.idAUTOGUARDADO FROM DUAL;
    END IF;
END; 
ALTER TRIGGER "IDAUTOGUARDADO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "LOG_ACCESO_TRG" BEFORE INSERT OR UPDATE ON log_acceso
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idlog_acceso IS NULL THEN
  SELECT LOG_ACCESO_SEQ.NEXTVAL INTO :NEW.idlog_acceso FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "LOG_ACCESO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "MENSAJE_IDMENSAJE_TRG" BEFORE INSERT OR UPDATE ON mensaje
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idmensaje IS NULL THEN
  SELECT mensaje_SEQ.NEXTVAL INTO :NEW.idmensaje FROM DUAL;
  END IF;
END;
ALTER TRIGGER "MENSAJE_IDMENSAJE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "MODULO_IDMODULO_TRG" BEFORE INSERT OR UPDATE ON modulo
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idmodulo IS NULL THEN
  SELECT modulo_SEQ.NEXTVAL INTO :NEW.idmodulo FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "MODULO_IDMODULO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "MUNICIPIO_EXTERIOR_TRG" BEFORE INSERT OR UPDATE ON MUNICIPIO_EXTERIOR
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idMUNICIPIO_EXTERIOR IS NULL THEN
  SELECT MUNICIPIO_EXTERIOR_SEQ.NEXTVAL INTO :NEW.idMUNICIPIO_EXTERIOR FROM DUAL;
  END IF;
END;
ALTER TRIGGER "MUNICIPIO_EXTERIOR_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "MUNICIPIO_IDMUNICIPIO_TRG" BEFORE INSERT OR UPDATE ON municipio
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idmunicipio IS NULL THEN
  SELECT municipio_SEQ.NEXTVAL INTO :NEW.idmunicipio FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "MUNICIPIO_IDMUNICIPIO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PAGINA_CONSECUTIVO_TRG" BEFORE INSERT OR UPDATE ON pagina
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.consecutivo IS NULL THEN
  SELECT pagina_SEQ.NEXTVAL INTO :NEW.consecutivo FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "PAGINA_CONSECUTIVO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PAIS_TRG" BEFORE INSERT OR UPDATE ON PAIS
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idPAIS IS NULL THEN
  SELECT PAIS_SEQ.NEXTVAL INTO :NEW.idPAIS FROM DUAL;
  END IF;
END;
ALTER TRIGGER "PAIS_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERFIL_IDPERFIL_TRG" BEFORE INSERT OR UPDATE ON perfil
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idperfil IS NULL THEN
  SELECT perfil_SEQ.NEXTVAL INTO :NEW.idperfil FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "PERFIL_IDPERFIL_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_ANEXO_TRG" BEFORE INSERT OR UPDATE ON PERMISO_ANEXO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idPERMISO_ANEXO IS NULL THEN
  SELECT PERMISO_ANEXO_SEQ.NEXTVAL INTO :NEW.idPERMISO_ANEXO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "PERMISO_ANEXO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_DOCUMENTO_TRG" 
 BEFORE INSERT OR UPDATE ON PERMISO_DOCUMENTO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idPERMISO_DOCUMENTO IS NULL THEN
  SELECT PERMISO_DOCUMENTO_SEQ.NEXTVAL INTO :NEW.idPERMISO_DOCUMENTO FROM DUAL;
  END IF;
END;

ALTER TRIGGER "PERMISO_DOCUMENTO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_EXPEDIENTE_TRG" BEFORE INSERT OR UPDATE ON PERMISO_EXPEDIENTE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idPERMISO_EXPEDIENTE IS NULL THEN
  SELECT PERMISO_EXPEDIENTE_SEQ.NEXTVAL INTO :NEW.idPERMISO_EXPEDIENTE FROM DUAL;
  END IF;
END;
ALTER TRIGGER "PERMISO_EXPEDIENTE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_FORMATO_TRG" BEFORE INSERT OR UPDATE ON PERMISO_FORMATO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idPERMISO_FORMATO IS NULL THEN
  SELECT PERMISO_FORMATO_SEQ.NEXTVAL INTO :NEW.idPERMISO_FORMATO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "PERMISO_FORMATO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_FUNCIONARIO_TRG" BEFORE INSERT OR UPDATE ON permiso_funcionario
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idpermiso_funcionario IS NULL THEN
  SELECT permiso_funcionario_SEQ.NEXTVAL INTO :NEW.idpermiso_funcionario FROM DUAL;
  END IF;
END;
ALTER TRIGGER "PERMISO_FUNCIONARIO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_IDPERMISO_TRG" BEFORE INSERT OR UPDATE ON permiso
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idpermiso IS NULL THEN
  SELECT permiso_SEQ.NEXTVAL INTO :NEW.idpermiso FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "PERMISO_IDPERMISO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "PERMISO_PERFIL_IDPERMISO_PERFI" BEFORE INSERT OR UPDATE ON permiso_perfil
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idpermiso_perfil IS NULL THEN
  SELECT permiso_perfil_seq.NEXTVAL INTO :NEW.idpermiso_perfil FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "PERMISO_PERFIL_IDPERMISO_PERFI" ENABLE;

CREATE OR REPLACE TRIGGER "PRETEXTO_IDPRETEXTO_TRG" BEFORE INSERT OR UPDATE ON pretexto
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idpretexto IS NULL THEN
  SELECT PRETEXTO_SEQ.NEXTVAL INTO :NEW.idpretexto FROM DUAL;
  END IF;
END;

ALTER TRIGGER "PRETEXTO_IDPRETEXTO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "REEMPLAZO_TRG" BEFORE INSERT OR UPDATE ON REEMPLAZO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idREEMPLAZO IS NULL THEN
  SELECT REEMPLAZO_SEQ.NEXTVAL INTO :NEW.idREEMPLAZO FROM DUAL;
  END IF;
END;
ALTER TRIGGER "REEMPLAZO_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "REPORTE_TRG" BEFORE INSERT OR UPDATE ON REPORTE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idREPORTE IS NULL THEN
  SELECT REPORTE_SEQ.NEXTVAL INTO :NEW.idREPORTE FROM DUAL;
  END IF;
END;
ALTER TRIGGER "REPORTE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "RESERVA_IDRESERVA_TRG" BEFORE INSERT OR UPDATE ON RESERVA
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idreserva IS NULL THEN
  SELECT reserva_SEQ.NEXTVAL INTO :NEW.idreserva FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "RESERVA_IDRESERVA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "RESPUESTA_IDRESPUESTA_TRG" BEFORE INSERT OR UPDATE ON RESPUESTA
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idrespuesta IS NULL THEN
  SELECT respuesta_SEQ.NEXTVAL INTO :NEW.idrespuesta FROM DUAL;
  END IF;
END; 
ALTER TRIGGER "RESPUESTA_IDRESPUESTA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "RUTA_CONDICION_REFERENCIA_ETRG" 
BEFORE INSERT OR UPDATE ON RUTA
FOR EACH ROW
DECLARE
  v_val RUTA.condicion_transferencia%TYPE;
  v_test RUTA.condicion_transferencia%TYPE;
BEGIN
  v_val := NULL;
  v_test := TRIM(:NEW.condicion_transferencia);
  IF v_test = '1' OR v_test = 'RECEPCION' THEN
  v_val := 'RECEPCION';
  ELSIF v_test = '2' OR v_test = 'PRODUCCION' THEN
  v_val := 'PRODUCCION';
  ELSIF v_test = '3' OR v_test = 'DISTRIBUCION' THEN
  v_val := 'DISTRIBUCION';
  ELSIF v_test = '4' OR v_test = 'CONSULTA' THEN
  v_val := 'CONSULTA';
  ELSIF v_test = '5' OR v_test = 'POR_APROBAR' THEN
  v_val := 'POR_APROBAR';
  ELSIF v_test = '6' OR v_test = 'RETENCION' THEN
  v_val := 'RETENCION';
  ELSIF v_test = '7' OR v_test = 'ALMACENAMIENTO' THEN
  v_val := 'ALMACENAMIENTO';
  ELSIF v_test = '8' OR v_test = 'RECUPERACION' THEN
  v_val := 'RECUPERACION';
  ELSIF v_test = '9' OR v_test = 'PRESERVACION' THEN
  v_val := 'PRESERVACION';
  ELSIF v_test = '10' OR v_test = 'DISPOSICION FINAL' THEN
  v_val := 'DISPOSICION FINAL';
  ELSIF v_test = '11' OR v_test = 'REVISADO' THEN
  v_val := 'REVISADO';
  ELSIF v_test = '12' OR v_test = 'APROBADO' THEN
  v_val := 'APROBADO';
  ELSIF v_test = '13' OR v_test = 'TRANSFERIDO' THEN
  v_val := 'TRANSFERIDO';
  END IF;  :NEW.condicion_transferencia := v_val;
END; 

ALTER TRIGGER "RUTA_CONDICION_REFERENCIA_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "RUTA_IDRUTA_TRG" BEFORE INSERT OR UPDATE ON RUTA
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idruta IS NULL THEN
  SELECT ruta_SEQ.NEXTVAL INTO :NEW.idruta FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "RUTA_IDRUTA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "RUTA_TIPO_ETRG" BEFORE INSERT OR UPDATE ON RUTA
FOR EACH ROW
DECLARE
  v_val RUTA.tipo%TYPE;
  v_test RUTA.tipo%TYPE;
BEGIN
  v_val := 'ACTIVO';
  v_test := TRIM(:NEW.tipo);
  IF v_test = '1' OR v_test = 'ACTIVO' THEN
  v_val := 'ACTIVO';
  ELSIF v_test = '2' OR v_test = 'INACTIVO' THEN
  v_val := 'INACTIVO';
  END IF;  :NEW.tipo := v_val;
END; 

ALTER TRIGGER "RUTA_TIPO_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "SALIDAS_IDSALIDA_TRG" BEFORE INSERT OR UPDATE ON SALIDAS
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idsalida IS NULL THEN
  SELECT salidas_SEQ.NEXTVAL INTO :NEW.idsalida FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "SALIDAS_IDSALIDA_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "SERIE_CONSERVACION_ETRG" 
BEFORE INSERT OR UPDATE ON SERIE
FOR EACH ROW
DECLARE
  v_val SERIE.conservacion%TYPE;
  v_test SERIE.conservacion%TYPE;
BEGIN
  v_val := NULL;
  v_test := TRIM(:NEW.conservacion);
  IF v_test = '1' OR v_test = 'TOTAL' THEN
  v_val := 'TOTAL';
  ELSIF v_test = '2' OR v_test = 'ELIMINACION' THEN
  v_val := 'ELIMINACION';
  END IF;  :NEW.conservacion := v_val;
END; 

ALTER TRIGGER "SERIE_CONSERVACION_ETRG" ENABLE;

CREATE OR REPLACE TRIGGER "SERIE_IDSERIE_TRG" BEFORE INSERT OR UPDATE ON SERIE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idserie IS NULL THEN
  SELECT serie_SEQ.NEXTVAL INTO :NEW.idserie FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "SERIE_IDSERIE_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "SOLICITUD_IDSOLICITUD_TRG" BEFORE INSERT OR UPDATE ON SOLICITUD
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idsolicitud IS NULL THEN
  SELECT solicitud_SEQ.NEXTVAL INTO :NEW.idsolicitud FROM DUAL;
  END IF;
END; 

ALTER TRIGGER "SOLICITUD_IDSOLICITUD_TRG" ENABLE;

CREATE OR REPLACE TRIGGER "TAREA_IDTAREA" BEFORE INSERT OR UPDATE ON tarea
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idtarea IS NULL THEN
  SELECT TAREA_SEQ.NEXTVAL INTO :NEW.idtarea FROM DUAL;
  END IF;
END;

ALTER TRIGGER "TAREA_IDTAREA" ENABLE;

CREATE OR REPLACE TRIGGER "VISTA_FORMATO_IDVISTA_FORMATO" BEFORE INSERT OR UPDATE ON VISTA_FORMATO
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.idvista_formato IS NULL THEN
  SELECT VISTA_FORMATO_SEQ.NEXTVAL INTO :NEW.idvista_formato FROM DUAL;
  END IF;
END;

ALTER TRIGGER "VISTA_FORMATO_IDVISTA_FORMATO" ENABLE;
