<?php
die();
include_once("db.php");
echo "Ejecutando limpieza, espere un momento por favor<br />";
//-----------------limpiar base de datos------------/

$conn->Ejecutar_Sql("delete from asignacion where tarea_idtarea=2"); 
 //tablas relacionadas para limpiar todo lo referente a los documentos
$conn->Ejecutar_Sql("truncate table almacenamiento");
$conn->Ejecutar_Sql("truncate table anexos");
$conn->Ejecutar_Sql("truncate table asignacion");
$conn->Ejecutar_Sql("truncate table asignacion_entidad");
$conn->Ejecutar_Sql("truncate table asignacion_terminar");
$conn->Ejecutar_Sql("truncate table autoguardado");
$conn->Ejecutar_Sql("truncate table binario");
//$conn->Ejecutar_Sql("truncate table busqueda");
//$conn->Ejecutar_Sql("truncate table busqueda_componente");
//$conn->Ejecutar_Sql("truncate table busqueda_condicion");
//$conn->Ejecutar_Sql("truncate table busqueda_condicion_enlace");
//$conn->Ejecutar_Sql("truncate table busqueda_filtro");
//$conn->Ejecutar_Sql("truncate table busqueda_filtro_temp");
//$conn->Ejecutar_Sql("truncate table busqueda_grafico");
//$conn->Ejecutar_Sql("truncate table busqueda_ruta");
//$conn->Ejecutar_Sql("truncate table busqueda_union");
//$conn->Ejecutar_Sql("truncate table busqueda_usuario");
$conn->Ejecutar_Sql("truncate table buzon_entrada");
$conn->Ejecutar_Sql("truncate table buzon_salida");
$conn->Ejecutar_Sql("truncate table caja");
//$conn->Ejecutar_Sql("truncate table calendario_saia");
//$conn->Ejecutar_Sql("truncate table campos");
//$conn->Ejecutar_Sql("truncate table campos_formato");
//$conn->Ejecutar_Sql("truncate table caracteristica");
//$conn->Ejecutar_Sql("truncate table caracteristicas_campos");
//$conn->Ejecutar_Sql("truncate table caracteristica_p");
//$conn->Ejecutar_Sql("truncate table cargo");
//$conn->Ejecutar_Sql("truncate table carrusel");
//$conn->Ejecutar_Sql("truncate table categoria_formato");
$conn->Ejecutar_Sql("truncate table campo_busqueda_usuario");
//$conn->Ejecutar_Sql("truncate table carrusel");
$conn->Ejecutar_Sql("truncate table comentario_img");
//$conn->Ejecutar_Sql("truncate table configuracion");
$conn->Ejecutar_Sql("update contador set consecutivo=1");
//$conn->Ejecutar_Sql("truncate table contenidos_carrusel");
$conn->Ejecutar_Sql("truncate table correo_usuario");
$conn->Ejecutar_Sql("truncate table datos_ejecutor");
//$conn->Ejecutar_Sql("truncate table departamento");
//$conn->Ejecutar_Sql("truncate table dependencia");
//$conn->Ejecutar_Sql("truncate table dependencia_cargo");
//--------flujos-----------------
//$conn->Ejecutar_Sql("truncate table diagram");
//$conn->Ejecutar_Sql("truncate table diagramdata");
//$conn->Ejecutar_Sql("truncate table diagram_closed");
//$conn->Ejecutar_Sql("truncate table diagram_finished");
//$conn->Ejecutar_Sql("truncate table diagram_history");
$conn->Ejecutar_Sql("truncate table diagram_instance");
$conn->Ejecutar_Sql("truncate table digitalizacion");
$conn->Ejecutar_Sql("truncate table documento");
$conn->Ejecutar_Sql("truncate table documento_accion");
$conn->Ejecutar_Sql("truncate table documento_anulacion");
$conn->Ejecutar_Sql("truncate table documento_etiqueta");
$conn->Ejecutar_Sql("truncate table documento_tareas");
$conn->Ejecutar_Sql("truncate table documento_verificacion");
$conn->Ejecutar_Sql("truncate table documento_vinculados");
//$conn->Ejecutar_Sql("truncate table documento_version");
$conn->Ejecutar_Sql("truncate table ejecutor");
//$conn->Ejecutar_Sql("truncate table encabezado_formato");
//$conn->Ejecutar_Sql("truncate table entidad");
$conn->Ejecutar_Sql("truncate table entidad_expediente");
$conn->Ejecutar_Sql("truncate table entidad_pretexto");
//$conn->Ejecutar_Sql("truncate table entidad_serie");
$conn->Ejecutar_Sql("truncate table error");
$conn->Ejecutar_Sql("truncate table estadisticas_saia_size");
$conn->Ejecutar_Sql("truncate table etiqueta");
$conn->Ejecutar_Sql("truncate table evento");
//$conn->Ejecutar_Sql("truncate table expediente");
//$conn->Ejecutar_Sql("truncate table expediente_doc");
//$conn->Ejecutar_Sql("truncate table filtro_grafica");
//$conn->Ejecutar_Sql("truncate table filtro_reporte");
$conn->Ejecutar_Sql("truncate table folder");
//$conn->Ejecutar_Sql("truncate table formato");
//$conn->Ejecutar_Sql("truncate table formato_ruta");


/*$formatos=busca_filtro_tabla("nombre_tabla","formato","","",$conn);
	for($i=0;$i<$formatos["numcampos"];$i++)	
    $conn->Ejecutar_Sql("truncate table ".$formatos[$i]["nombre_tabla"]);*/
    

//$conn->Ejecutar_Sql("truncate table funcion");
//$conn->Ejecutar_Sql("truncate table funcionario");
//$conn->Ejecutar_Sql("truncate table funcionario_validacion");
//$conn->Ejecutar_Sql("truncate table funciones_formato");
//$conn->Ejecutar_Sql("truncate table funciones_formato_accion");
//$conn->Ejecutar_Sql("truncate table funciones_paso");
//$conn->Ejecutar_Sql("truncate table funciones_paso_accion");
//$conn->Ejecutar_Sql("truncate table grafico");
//$conn->Ejecutar_Sql("truncate table grafico_serie");
$conn->Ejecutar_Sql("truncate table log_acceso");
$conn->Ejecutar_Sql("truncate table mensaje_formato");
//$conn->Ejecutar_Sql("truncate table modulo");
//$conn->Ejecutar_Sql("truncate table modulo_exterior");
//$conn->Ejecutar_Sql("truncate table modulo_temp");
//$conn->Ejecutar_Sql("truncate table municipio");
//$conn->Ejecutar_Sql("truncate table municipio_exterior");
//$conn->Ejecutar_Sql("truncate table noticias_index");
$conn->Ejecutar_Sql("truncate table pagina");
//$conn->Ejecutar_Sql("truncate table pais");
//$conn->Ejecutar_Sql("truncate table pantalla");
//$conn->Ejecutar_Sql("truncate table paso");
//$conn->Ejecutar_Sql("truncate table paso_actividad");
$conn->Ejecutar_Sql("truncate table paso_actividad_anexo");
//$conn->Ejecutar_Sql("truncate table paso_actividad_funciones");
//$conn->Ejecutar_Sql("truncate table paso_actividad_programacion");
//$conn->Ejecutar_Sql("truncate table paso_devolucion");
$conn->Ejecutar_Sql("truncate table paso_documento");
//$conn->Ejecutar_Sql("truncate table paso_enlace");
$conn->Ejecutar_Sql("truncate table paso_enlace_temporal");
$conn->Ejecutar_Sql("truncate table paso_instancia_pendiente");
$conn->Ejecutar_Sql("truncate table paso_instancia_rastro");
$conn->Ejecutar_Sql("truncate table paso_instancia_terminada");
$conn->Ejecutar_Sql("truncate table paso_inst_terminacion");
$conn->Ejecutar_Sql("truncate table paso_rastro");
$conn->Ejecutar_Sql("truncate table paso_tareas");
$conn->Ejecutar_Sql("truncate table paso_temporal");
$conn->Ejecutar_Sql("truncate table permiso_anexo");
//$conn->Ejecutar_Sql("truncate table perfil");
//$conn->Ejecutar_Sql("truncate table permiso");
$conn->Ejecutar_Sql("truncate table permiso_anexos");
$conn->Ejecutar_Sql("truncate table permiso_documento");
//$conn->Ejecutar_Sql("truncate table permiso_formato");
//$conn->Ejecutar_Sql("truncate table permiso_funcionario");
//$conn->Ejecutar_Sql("truncate table permiso_perfil");
$conn->Ejecutar_Sql("truncate table pretexto");
$conn->Ejecutar_Sql("truncate table prioridad_documento");
//$conn->Ejecutar_Sql("truncate table permiso_expediente");
$conn->Ejecutar_Sql("truncate table reemplazo");
$conn->Ejecutar_Sql("truncate table radicados_carta");
$conn->Ejecutar_Sql("truncate table respuesta");
$conn->Ejecutar_Sql("truncate table ruta");
$conn->Ejecutar_Sql("truncate table salidas");
//$conn->Ejecutar_Sql("truncate table serie");
//$conn->Ejecutar_Sql("truncate table tarea");
$conn->Ejecutar_Sql("truncate table tareas");
$conn->Ejecutar_Sql("truncate table tareas_buzon");
//$conn->Ejecutar_Sql("truncate table userdiagram");
//$conn->Ejecutar_Sql("truncate table user_workflow);
//$conn->Ejecutar_Sql("truncate table reserva");
//$conn->Ejecutar_Sql("truncate table solicitud");
echo ("Fin de la limpieza");                   
?>