<html><title>.:ADICIONAR CONTROL DE CITA:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">CONTROL DE CITA</td></tr><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(292,3369);?></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_solicitud_cita"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_solicitud_cita"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_solicitud_cita);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3363)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">NOMBRE DEL PACIENTE*</td>
                     <td bgcolor="#F5F5F5"><input   class="required"   tabindex='1'  type="text" size="100" id="nombre_paciente_control" name="nombre_paciente_control"  value="<?php echo(validar_valor_campo(3366)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">ESTADO DE LA CITA</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(292,3365,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="idft_control_cita" value="<?php echo(validar_valor_campo(3367)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DESCRIPCI&Oacute;N</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="descripcion_control_cita" id="descripcion_control_cita" cols="53" rows="3" class="tiny_basico"><?php echo(validar_valor_campo(3364)); ?></textarea></td>
                    </tr><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3368)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3370)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3371)); ?>"><?php nombre_control_cita(292,NULL);?><input type="hidden" name="campo_descripcion" value="3365"><tr><td colspan='2'><?php submit_formato(292);?></td></tr></table></form></body></html>