<html><title>.:ADICIONAR RESERVAR:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">RESERVAR</td></tr><tr>
                     <td class="encabezado" width="20%" title="Guarda el iddocumento relacionado">DOCUMENTO RELACIONADO</td>
                     <?php ft_tabla_funcion(324,3789);?></tr><input type="hidden" name="fecha_entrega" value="<?php echo(validar_valor_campo(3790)); ?>"><input type="hidden" name="usuario_entrega" value="<?php echo(validar_valor_campo(3791)); ?>"><input type="hidden" name="observacion_entrega" value="<?php echo(validar_valor_campo(3792)); ?>"><input type="hidden" name="fecha_devolver" value="<?php echo(validar_valor_campo(3793)); ?>"><input type="hidden" name="usuario_devolver" value="<?php echo(validar_valor_campo(3794)); ?>"><input type="hidden" name="observacion_devolver" value="<?php echo(validar_valor_campo(3795)); ?>"><input type="hidden" name="estado_doc" value="<?php echo(validar_valor_campo(3796)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(324,3781);?></tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3778)); ?>"><input type="hidden" name="idft_reservar_documento" value="<?php echo(validar_valor_campo(3779)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3780)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3782)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3783)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">FECHA DE SOLICITUD*</td>
                     <?php fecha_formato(324,3784);?></tr><tr>
                    <td class="encabezado" width="20%" title="">DESDE*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='1'  type="text" readonly="true" name="desde"  class="required dateISO"  id="desde" value="<?php echo(date("0000-00-00 00:00")); ?>"><?php selector_fecha("desde","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr>
                    <td class="encabezado" width="20%" title="">HASTA*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='2'  type="text" readonly="true" name="hasta"  class="required dateISO"  id="hasta" value="<?php echo(date("0000-00-00 00:00")); ?>"><?php selector_fecha("hasta","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">SOLICITAR A*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(324,3787,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="">OBSERVACIONES</td>
                     <td class="celda_transparente"><textarea  tabindex='3'  name="observaciones" id="observaciones" cols="53" rows="3" class="tiny_basico"><?php echo(validar_valor_campo(3788)); ?></textarea></td>
                    </tr><input type="hidden" name="campo_descripcion" value="3784"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(324);?></td></tr></table></form></body></html>