<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.8.3
 */

/**
 * Database `saia_ig`
 */

/* `saia_ig`.`campos_formato` */
$campos_formato = array(
  array('idcampos_formato' => '7027','formato_idformato' => '431','nombre' => 'anexos','etiqueta' => 'Anexos','tipo_dato' => 'TEXT','longitud' => NULL,'obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'archivo','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7023','formato_idformato' => '431','nombre' => 'ciudad_proveedor','etiqueta' => 'Ciudad proveedor','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7022','formato_idformato' => '431','nombre' => 'direccion_proveedor','etiqueta' => 'Direcci&oacute;n proveedor','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7016','formato_idformato' => '431','nombre' => 'estado_documento','etiqueta' => 'ESTADO DEL DOCUMENTO','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a','ayuda' => '','predeterminado' => '','banderas' => '','etiqueta_html' => 'hidden','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7024','formato_idformato' => '431','nombre' => 'estado_proveedor','etiqueta' => 'Departamento proveedor','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7020','formato_idformato' => '431','nombre' => 'fecha_factura','etiqueta' => 'Fecha factura','tipo_dato' => 'DATETIME','longitud' => NULL,'obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'fecha','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7029','formato_idformato' => '431','nombre' => 'fk_datos_factura','etiqueta' => 'fk_datos_factura','tipo_dato' => 'INT','longitud' => '11','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'hidden','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7026','formato_idformato' => '431','nombre' => 'info_proveedor','etiqueta' => 'Informaci&oacute;n adicional del proveedor','tipo_dato' => 'TEXT','longitud' => NULL,'obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'textarea','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7019','formato_idformato' => '431','nombre' => 'nit_proveedor','etiqueta' => 'NIT Proveedor','tipo_dato' => 'VARCHAR','longitud' => '20','obligatoriedad' => '1','valor' => NULL,'acciones' => 'a,e,p,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7021','formato_idformato' => '431','nombre' => 'nombre_proveedor','etiqueta' => 'Nombre proveedor','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7018','formato_idformato' => '431','nombre' => 'num_factura','etiqueta' => 'N&uacute;mero de factura','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '1','valor' => NULL,'acciones' => 'a,e,p,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7025','formato_idformato' => '431','nombre' => 'pais_proveedor','etiqueta' => 'Pais proveedor','tipo_dato' => 'VARCHAR','longitud' => '255','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7017','formato_idformato' => '431','nombre' => 'serie_idserie','etiqueta' => 'SERIE DOCUMENTAL','tipo_dato' => 'INT','longitud' => '11','obligatoriedad' => '1','valor' => '../../test/test_serie_funcionario.php?estado_serie=1;2;0;1;1;0;1','acciones' => 'a,e','ayuda' => 'Factura electr&oacute;nica','predeterminado' => '0','banderas' => 'fk','etiqueta_html' => 'hidden','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL),
  array('idcampos_formato' => '7028','formato_idformato' => '431','nombre' => 'total_factura','etiqueta' => 'Total factura','tipo_dato' => 'VARCHAR','longitud' => '50','obligatoriedad' => '0','valor' => NULL,'acciones' => 'a,e,b','ayuda' => NULL,'predeterminado' => NULL,'banderas' => NULL,'etiqueta_html' => 'text','orden' => '0','mascara' => NULL,'adicionales' => NULL,'autoguardado' => '0','fila_visible' => '1','placeholder' => NULL,'longitud_vis' => NULL,'opciones' => NULL,'estilo' => NULL)
);
