<?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/header_formato.php"); ?><legend id="label_formato" class="legend">B&uacute;squeda en formato Devoluci&oacute;n Factura</legend><br /><br /><?php include_once("../librerias/funciones_generales.php"); ?>
                <fieldset>
                <legend style="font-size:10pt;line-height:15px"><b>Proveedor</b></legend>
                <div class="control-group;" style="background-color:#F5F5F5">
                <b>Nombre<input type="hidden" name="bksaiacondicion_f@nombre__0" id="bksaiacondicion_f@nombre__0" value="like_total"></b><div class="controls"><input type="text"    id="proveedor_devolucion-nombre" name="g@proveedor_devolucion-nombre" ></div><b>Identificacion</b><div class="controls"><input type="text"    id="proveedor_devolucion-identificacion" name="g@proveedor_devolucion-identificacion" ></div><b>Empresa</b><div class="controls"><input type="text"    id="proveedor_devolucion-empresa" name="g@proveedor_devolucion-empresa" ></div></div></fieldset><br><div class="control-group"><label class="string control-label" style="font-size:9pt" for="forma_envio"><b>Forma Envio<input type="hidden" name="bksaiacondicion_g@forma_envio" id="bksaiacondicion_g@forma_envio" value="="></b></label><div class="controls"><?php genera_campo_listados_editar(304,3554,'',1,'buscar');?><div class="btn-group" data-toggle="buttons-radio" >
		  <!--button type="button" class="btn btn-mini" data-toggle="button" id="y" onclick="llenar_valor('bqsaiaenlace_g@forma_envio',this.id)">
		    Y
		  </button>
		  <button type="button" class="btn btn-mini" data-toggle="button" id="o" onclick="llenar_valor('bqsaiaenlace_g@forma_envio',this.id)">
		    O
		  </button-->
		  <input type="hidden" name="bqsaiaenlace_g@forma_envio" id="bqsaiaenlace_g@forma_envio" value="y" />
		</div></div></div><div class="control-group"><b>observaciones<input type="hidden" name="bksaiacondicion_g@observaciones" id="bksaiacondicion_g@observaciones" value="like_total"></b><div class="controls"><textarea    id="observaciones" name="bqsaia_g@observaciones"  style="width:500px;height:100px"></textarea></div></div><input type="hidden" name="campos_especiales" value="proveedor_devolucion@ejecutor"><input type="hidden" name="filtro_adicional" id="filtro_adicional" value=" ft_devolu_factura_radica g @ AND  g.documento_iddocumento=iddocumento "><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"></body>