<html><title>.:ADICIONAR SOLICITUD DE ANULACI&OACUTE;N:.</title><head><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery-1.4.2.min.js"></script><script type="text/javascript" src="../../js/jquery.validate2.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script></head><body bgcolor="#F5F5F5"><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">SOLICITUD DE ANULACIóN</td></tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(888)); ?>"><tr>
                     <td class="encabezado" width="20%" title="descripci&ograve;n del motivo por el cual se desea anular el documento">JUSTIFICACIóN*</td>
                     <td class="celda_transparente"><textarea name="justificacion"  maxlenght="2000"   obligatorio="obligatorio" class="required"   cols="53" rows="3" class="tiny_"></textarea></td>
                    </tr><input type="hidden" name="idft_anulacion" value="<?php echo(validar_valor_campo(890)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(891)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(74,892);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(893)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(894)); ?>"><?php descripcion(74,NULL);?><tr><td colspan='2'><?php submit_formato(74);?></td></tr></table></form></body></html>