<html><title>.:EDITAR SOLICITUD DE ANULACI&OACUTE;N:.</title><head><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery-1.4.2.min.js"></script><script type="text/javascript" src="../../js/jquery.validate2.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script></head><body bgcolor="#F5F5F5"><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">SOLICITUD DE ANULACIóN</td></tr><tr>
                     <td class="encabezado" width="20%" title="descripci&ograve;n del motivo por el cual se desea anular el documento">JUSTIFICACIóN*</td>
                     <td class="celda_transparente"><textarea name="justificacion"  maxlenght="2000"   obligatorio="obligatorio" class="required"   cols="53" rows="3" class="tiny_"><?php echo(mostrar_valor_campo('justificacion',74,$_REQUEST['iddoc'])); ?></textarea></td>
                    </tr><input type="hidden" name="idft_anulacion" value="<?php echo(mostrar_valor_campo('idft_anulacion',74,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(mostrar_valor_campo('documento_iddocumento',74,$_REQUEST['iddoc'])); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(74,892,$_REQUEST['iddoc']);?></tr><input type="hidden" name="encabezado" value="<?php echo(mostrar_valor_campo('encabezado',74,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="firma" value="<?php echo(mostrar_valor_campo('firma',74,$_REQUEST['iddoc'])); ?>"><?php descripcion(74,NULL,$_REQUEST['iddoc']);?><input type="hidden" name="formato" value="74"><tr><td colspan='2'><?php submit_formato(74,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>