<html><title>.:ADICIONAR FORMACI&Oacute;N ACAD&Eacute;MICA:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type="text/javascript" src="../../anexosdigitales/multiple-file-upload/jquery.MultiFile.js"></script><?php include_once("../../anexosdigitales/funciones_archivo.php"); ?><script type="text/javascript" src="../../anexosdigitales/highslide-4.0.10/highslide/highslide-with-html.js"></script><link rel="stylesheet" type="text/css" href="../../anexosdigitales/highslide-4.0.10/highslide/highslide.css" />
    </style><script type='text/javascript'>
    hs.graphicsDir = '../../anexosdigitales/highslide-4.0.10/highslide/graphics/';
    hs.outlineType = 'rounded-white';
</script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">FORMACI&Oacute;N ACAD&Eacute;MICA</td></tr><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(220,2376);?></tr><input type="hidden" name="apellidos" value="<?php echo(validar_valor_campo(2366)); ?>"><input type="hidden" name="celular" value="<?php echo(validar_valor_campo(2367)); ?>"><input type="hidden" name="direccion" value="<?php echo(validar_valor_campo(2368)); ?>"><input type="hidden" name="email" value="<?php echo(validar_valor_campo(2369)); ?>"><input type="hidden" name="nombre" value="<?php echo(validar_valor_campo(2371)); ?>"><tr id="tr_tipo_formacion" >
                     <td class="encabezado" width="20%" title="">TIPO DE FORMACI&Oacute;N ACAD&Eacute;MICA*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(220,2373,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="">INSTITUCI&Oacute;N*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='1'  type="text" size="100" id="institucion_formacion" name="institucion_formacion"  value="<?php echo(validar_valor_campo(2370)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">T&Iacute;TULO OBTENIDO*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='2'  type="text" size="100" id="titulo_formacion" name="titulo_formacion"  value="<?php echo(validar_valor_campo(2372)); ?>"></td>
                    </tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_hoja_vida"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_hoja_vida"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_hoja_vida);} ?><tr>
                     <td class="encabezado" width="20%" title="">AEXOS DIGITALES*</td>
                     <td class="celda_transparente"><input  tabindex='3'  type="file" maxlength="255"  class="required multi"  name="anexos[]" accept="<?php echo $extensiones;?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(2364)); ?>"><input type="hidden" name="idft_formacion_academica" value="<?php echo(validar_valor_campo(2374)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(2375)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(2377)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(2378)); ?>"><input type="hidden" name="campo_descripcion" value="2373"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(220);?></td></tr></table><input type='hidden' name='permisos_anexos' id='permisos_anexos' value=''></form></body></html>