<html><title>.:ADICIONAR DESPACHO FISICO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">DESPACHO FISICO</td></tr><input type="hidden" name="fecha_despacho" value="<?php echo(validar_valor_campo(4081)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(352,4069);?></tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(4064)); ?>"><input type="hidden" name="docs_seleccionados" value="<?php echo(validar_valor_campo(4065)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">SELECCIONE MENSAJERO</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(352,4066,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="idft_despacho_fisico" value="<?php echo(validar_valor_campo(4067)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(4068)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(4070)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(4071)); ?>"><?php campos_ocultos_despacho(352,NULL);?><input type="hidden" name="campo_descripcion" value="4081"><tr><td colspan='2'><?php submit_formato(352);?></td></tr></table></form></body></html>