<html><title>.:ADICIONAR PRUEBA (CONFIRMA - APRUEBA):.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">PRUEBA (CONFIRMA - APRUEBA)</td></tr><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5079)); ?>"><tr id="tr_hola_mundo">
                     <td class="encabezado" width="20%" title="">HOLA MUNDO</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='1'  type="text" size="100" id="hola_mundo" name="hola_mundo"  value="<?php echo(validar_valor_campo(5080)); ?>"></td>
                    </tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5078)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(410,5077);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5076)); ?>"><input type="hidden" name="idft_prueba_confir_apru" value="<?php echo(validar_valor_campo(5075)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5074)); ?>"><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5073)); ?>"><tr><td colspan='2'><?php submit_formato(410);?></td></tr></table></form></body></html>