<html><title>.:EDITAR PRUEBA (CONFIRMA - APRUEBA):.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">PRUEBA (CONFIRMA - APRUEBA)</td></tr><input type="hidden" name="firma" value="<?php echo(mostrar_valor_campo('firma',410,$_REQUEST['iddoc'])); ?>"><tr id="tr_hola_mundo">
                     <td class="encabezado" width="20%" title="">HOLA MUNDO</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='1'  type="text" size="100" id="hola_mundo" name="hola_mundo"  value="<?php echo(mostrar_valor_campo('hola_mundo',410,$_REQUEST['iddoc'])); ?>"></td>
                    </tr><input type="hidden" name="encabezado" value="<?php echo(mostrar_valor_campo('encabezado',410,$_REQUEST['iddoc'])); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(410,5077,$_REQUEST['iddoc']);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(mostrar_valor_campo('documento_iddocumento',410,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="idft_prueba_confir_apru" value="<?php echo(mostrar_valor_campo('idft_prueba_confir_apru',410,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="formato" value="410"><tr><td colspan='2'><?php submit_formato(410,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>