<html><title>.:EDITAR EVOLUCION DE TRATAMIENTO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../librerias/funciones_item.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr>
                    <td class="encabezado" width="20%" title="">FECHA*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='1'  type="text" readonly="true" name="fecha_evolucion"  class="required dateISO"  id="fecha_evolucion" value="<?php mostrar_valor_campo('fecha_evolucion',294,$_REQUEST['iddoc']); ?>"><?php selector_fecha("fecha_evolucion","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">PROCEDIMIENTO*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="procedimiento_evolucion" id="procedimiento_evolucion" cols="53" rows="3" class="tiny_basico required"><?php echo(mostrar_valor_campo('procedimiento_evolucion',294,$_REQUEST['iddoc'])); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">FIRMA PACIENTE</td>
                     <td bgcolor="#F5F5F5"><input    tabindex='3'  type="text" size="100" id="firma_paciente" name="firma_paciente"  value="<?php echo(mostrar_valor_campo('firma_paciente',294,$_REQUEST['iddoc'])); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">FIRMA PROFESIONAL</td>
                     <td bgcolor="#F5F5F5"><input    tabindex='4'  type="text" size="100" id="firma_profesional" name="firma_profesional"  value="<?php echo(mostrar_valor_campo('firma_profesional',294,$_REQUEST['iddoc'])); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">ABONO</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="11"   tabindex='5'  type="text" size="100" id="abono_evoluciones" name="abono_evoluciones"  value="<?php echo(mostrar_valor_campo('abono_evoluciones',294,$_REQUEST['iddoc'])); ?>"></td>
                    </tr><input type="hidden" name="idft_evolucion_tratamiento" value="<?php echo(mostrar_valor_campo('idft_evolucion_tratamiento',294,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="formato" value="294"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="formato" value="evolucion_tratamiento"><input type="hidden" name="accion" value="editar" ><input type="hidden" name="item" value="<?php echo $_REQUEST["item"]; ?>" ><input type="hidden" name="anterior" value="<?php echo $_REQUEST["campo"]; ?>" ><tr><td colspan='2'><?php submit_formato(294,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>