INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*asignar_responsables*}','asignar_responsables','','asignar_responsables','asignar_responsables','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_empresa*}','nombre_empresa','','nombre_empresa','nombre_empresa','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*botones_estado_acta*}','botones_estado_acta','','botones_estado_acta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*insertar_item*}','insertar_item','','insertar_item','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_asistentes_acta*}','mostrar_asistentes_acta','','mostrar_asistentes_acta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_item_invitado*}','mostrar_item_invitado','','mostrar_item_invitado','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_numero_convocatoria*}','mostrar_numero_convocatoria','','mostrar_numero_convocatoria','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_tipo_reunion*}','mostrar_tipo_reunion','','mostrar_tipo_reunion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*tareas_acta*}','tareas_acta','','tareas_acta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*temas_acta*}','temas_acta','','temas_acta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferir_participante_invitado*}','transferir_participante_invitado','','transferir_participante_invitado','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_tipo_reunion*}','ver_tipo_reunion','','ver_tipo_reunion','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_conclusiones*}','mostrar_conclusiones','','mostrar_conclusiones','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_fecha_creacion_acta*}','mostrar_fecha_creacion_acta','','mostrar_fecha_creacion_acta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*select_tipo_reunion*}','select_tipo_reunion','','select_tipo_reunion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*eliminar_selectos_reunion*}','eliminar_selectos_reunion','','eliminar_selectos_reunion','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_envio_copia*}','transferencia_envio_copia','','transferencia_envio_copia','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_temas*}','validar_temas','','validar_temas','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_codigo_qr*}','mostrar_codigo_qr','','mostrar_codigo_qr','Muestra el codigo QR','../../app/qr/librerias.php','m','|-formato-|')||

/*inicio_datos--{*asignar_responsables*},{*botones_estado_acta*},{*eliminar_selectos_reunion*},{*formato_numero*},{*insertar_item*},{*logo_empresa*},{*mostrar_asistentes_acta*},{*mostrar_codigo_qr*},{*mostrar_conclusiones*},{*mostrar_estado_proceso*},{*mostrar_fecha_creacion_acta*},{*mostrar_item_invitado*},{*mostrar_numero_convocatoria*},{*mostrar_tipo_reunion*},{*nombre_empresa*},{*nombre_formato*},{*select_tipo_reunion*},{*tareas_acta*},{*temas_acta*},{*transferencia_envio_copia*},{*transferir_participante_invitado*},{*validar_temas*},{*ver_tipo_reunion*}--fin_datos*/