INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*ciudad*}','ciudad','','ciudad','ciudad','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_fecha*}','mostrar_fecha','','mostrar_fecha','mostrar_fecha','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*dependencia_codigo*}','dependencia_codigo','','dependencia_codigo','dependencia_codigo','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_anexos_memo*}','mostrar_anexos_memo','','mostrar_anexos_memo','mostrar_anexos_memo','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*estilo_formato*}','estilo_formato','','estilo_formato','estilo_formato','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*crear_pdf*}','crear_pdf','','crear_pdf','crear_pdf','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*cargar_destinos_carta*}','cargar_destinos_carta','','funciones.php','permite exportar e importar los destinos de una carta','funciones.php','a,e')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*actualizar_radicados*}','actualizar_radicados','','actualizar_radicados','actualizar_radicados','funciones.php','')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*lista_destinos*}','lista_destinos','','lista_destinos','lista_destinos','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*asignar_responsables*}','asignar_responsables','','asignar_responsables','asignar_responsables','funciones.php','a')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_copias_carta*}','mostrar_copias_carta','','Mostrar Copias de la Carta','Mostrar Copias de la Carta','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_destinos*}','mostrar_destinos','','Mostrar Destinos','Mostrar Destinos','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*transferencia_automatica*}','transferencia_automatica','copiainterna,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*guardar_plantilla*}','guardar_plantilla','','guardar_plantilla','','funciones.php','a')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_imagenes_escaneadas*}','mostrar_imagenes_escaneadas','','mostrar_imagenes_escaneadas','','funciones.php','a,e')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_anexos*}','mostrar_anexos','','mostrar_anexos','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_destinos_carta*}','mostrar_destinos_carta','','mostrar_destinos_carta','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*nombre_dependencia*}','nombre_dependencia','','nombre_dependencia','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_iniciales*}','mostrar_iniciales','','mostrar_iniciales','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_datos_radicaion*}','mostrar_datos_radicaion','','mostrar_datos_radicaion','','../carta/funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_formato_funcion*}','mostrar_formato_funcion','','mostrar_formato_funcion','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_iniciales*}','mostrar_iniciales','','mostrar_iniciales','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*foto_pagina*}','foto_pagina','','foto_pagina','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_copia_interna*}','mostrar_copia_interna','','mostrar_copia_interna','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_asunto_carta*}','mostrar_asunto_carta','','mostrar_asunto_carta','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*logo_encabezado*}','logo_encabezado','','logo_encabezado','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*fecha_creacion*}','fecha_creacion','','fecha_creacion','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*editar_usuario_ruta*}','editar_usuario_ruta','','editar_usuario_ruta','editar_usuario_ruta','../librerias/funciones_generales.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*serie_subserie*}','serie_subserie','','serie_subserie','serie_subserie','../librerias/funciones_generales.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_datos_radicacion*}','mostrar_datos_radicacion','','mostrar_datos_radicacion','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_qr_carta*}','mostrar_qr_carta','','mostrar_qr_carta','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*generar_codigo_qr_carta*}','generar_codigo_qr_carta','','generar_codigo_qr_carta','','funciones.php','')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*tamanio_texto_anexos_ext*}','tamanio_texto_anexos_ext','','tamanio_texto_anexos_ext','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_copias_comunicacion_ext*}','mostrar_copias_comunicacion_ext','','mostrar_copias_comunicacion_ext','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_anexos_externa*}','mostrar_anexos_externa','','mostrar_anexos_externa','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*generar_correo_confirmacion*}','generar_correo_confirmacion','','generar_correo_confirmacion','','funciones.php','')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*pie_pagina_carta*}','pie_pagina_carta','','pie_pagina_carta','','../librerias/encabezado_pie_pagina.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*parsear_arbol_expediente_serie_carta*}','parsear_arbol_expediente_serie_carta','','parsear_arbol_expediente_serie_carta','','funciones.php','a')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*vincular_expediente_serie_carta*}','vincular_expediente_serie_carta','','vincular_expediente_serie_carta','','funciones.php','')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*formato_radicado_enviada*}','formato_radicado_enviada','','formato_radicado_enviada','','funciones.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*mostrar_listado_distribucion_documento*}','mostrar_listado_distribucion_documento','','mostrar_listado_distribucion_documento','','../../distribucion/funciones_distribucion.php','m')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones) VALUES('{*vincular_distribucion_carta*}','vincular_distribucion_carta','','vincular_distribucion_carta','vincula el formato carta a la distribucion','funciones.php','')||

/*inicio_datos--{*actualizar_radicados*},{*asignar_responsables*},{*cargar_destinos_carta*},{*ciudad*},{*crear_pdf*},{*dependencia_codigo*},{*editar_usuario_ruta*},{*estilo_formato*},{*fecha_creacion*},{*fecha_formato*},{*formato_numero*},{*formato_radicado_enviada*},{*foto_pagina*},{*generar_codigo_qr_carta*},{*generar_correo_confirmacion*},{*guardar_plantilla*},{*lista_destinos*},{*logo_empresa*},{*logo_encabezado*},{*mostrar_anexos*},{*mostrar_anexos_externa*},{*mostrar_anexos_memo*},{*mostrar_asunto_carta*},{*mostrar_copia_interna*},{*mostrar_copias_carta*},{*mostrar_copias_comunicacion_ext*},{*mostrar_datos_radicacion*},{*mostrar_datos_radicaion*},{*mostrar_destinos*},{*mostrar_destinos_carta*},{*mostrar_estado_proceso*},{*mostrar_fecha*},{*mostrar_formato_funcion*},{*mostrar_imagenes_escaneadas*},{*mostrar_iniciales*},{*mostrar_listado_distribucion_documento*},{*mostrar_qr_carta*},{*nombre_dependencia*},{*nombre_formato*},{*parsear_arbol_expediente_serie_carta*},{*pie_pagina_carta*},{*serie_subserie*},{*tamanio_texto_anexos_ext*},{*transferencia_automatica*},{*vincular_distribucion_carta*},{*vincular_expediente_serie_carta*}--fin_datos*/