INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('1','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('2','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('3','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('4','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('5','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('6','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('7','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('8','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('9','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('10','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('11','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('12','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('13','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('19','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('23','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('24','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('76','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('87','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('97','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('98','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('104','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('105','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('106','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('107','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('109','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('113','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('135','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('178','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('191','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('383','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('426','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('435','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('455','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('456','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('457','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('501','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('502','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('564','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('565','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('566','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('608','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('738','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('895','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('896','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('932','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('943','1','|-idfunciones_formato_enlace-|')||
INSERT INTO funciones_formato_enlace(funciones_formato_fk,formato_idformato,idfunciones_formato_enlace) VALUES('944','1','|-idfunciones_formato_enlace-|')||
