INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*asignar_responsables*}','asignar_responsables','','asignar_responsables','asignar_responsables','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_empresa*}','nombre_empresa','','nombre_empresa','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||

/*inicio_datos--{*asignar_responsables*},{*logo_empresa*},{*nombre_empresa*},{*nombre_formato*},{*transferencia_automatica*}--fin_datos*/