INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ciudad*}','ciudad','','ciudad','ciudad','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_fecha*}','mostrar_fecha','','mostrar_fecha','mostrar_fecha','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*dependencia_codigo*}','dependencia_codigo','','dependencia_codigo','dependencia_codigo','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos_memo*}','mostrar_anexos_memo','','mostrar_anexos_memo','mostrar_anexos_memo','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*estilo_formato*}','estilo_formato','','estilo_formato','estilo_formato','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*crear_pdf*}','crear_pdf','','crear_pdf','crear_pdf','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*lista_destinos*}','lista_destinos','','lista_destinos','lista_destinos','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_origen*}','mostrar_origen','','mostrar_origen','mostrar_origen','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_imagenes*}','mostrar_imagenes','','mostrar_imagenes','mostar_imagenes','../librerias/funciones_generales.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_copias_memo*}','mostrar_copias_memo','','mostrar_copias_memo','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*guardar_plantilla*}','guardar_plantilla','','guardar_plantilla','guardar_plantilla','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*asignar_responsables*}','asignar_responsables','','asignar_responsables','asignar_responsables','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_copias_carta*}','mostrar_copias_carta','','Mostrar Copias de la Carta','Mostrar Copias de la Carta','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_destinos*}','mostrar_destinos','','Mostrar Destinos','Mostrar Destinos','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','destino,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','copia,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*seleccionar_origen*}','seleccionar_origen','','seleccionar_origen','','../memorando/funciones.php','e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos*}','mostrar_anexos','','mostrar_anexos','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_destinos_carta*}','mostrar_destinos_carta','','mostrar_destinos_carta','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_iniciales*}','mostrar_iniciales','','mostrar_iniciales','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_datos_radicaion*}','mostrar_datos_radicaion','','mostrar_datos_radicaion','','../carta/funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_iniciales*}','mostrar_iniciales','','mostrar_iniciales','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos_memo*}','mostrar_anexos_memo','','mostrar_anexos_memo','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_copia_interna*}','mostrar_copia_interna','','mostrar_copia_interna','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_formato*}','mostrar_formato','','mostrar_formato','','../class_transferencia.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*serie_subserie*}','serie_subserie','','serie_subserie','serie_subserie','../librerias/funciones_generales.php','m','|-formato-|')||

/*inicio_datos--{*asignar_responsables*},{*ciudad*},{*crear_pdf*},{*dependencia_codigo*},{*estilo_formato*},{*fecha_formato*},{*formato_numero*},{*guardar_plantilla*},{*lista_destinos*},{*logo_empresa*},{*mostrar_anexos*},{*mostrar_anexos_memo*},{*mostrar_copia_interna*},{*mostrar_copias_carta*},{*mostrar_copias_memo*},{*mostrar_datos_radicaion*},{*mostrar_destinos*},{*mostrar_destinos_carta*},{*mostrar_estado_proceso*},{*mostrar_fecha*},{*mostrar_formato*},{*mostrar_imagenes*},{*mostrar_iniciales*},{*mostrar_origen*},{*nombre_formato*},{*seleccionar_origen*},{*serie_subserie*},{*transferencia_automatica*}--fin_datos*/