INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_formato*}','mostrar_formato','','mostrar_formato','','../class_transferencia.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*cargar_datos*}','cargar_datos','','cargar_datos','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ruta_orden_pago*}','ruta_orden_pago','','ruta_orden_pago','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_dependencia_creador*}','ver_dependencia_creador','','ver_dependencia_creador','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_fecha_solicitud*}','ver_fecha_solicitud','','ver_fecha_solicitud','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_papa_detalle_factura*}','ver_papa_detalle_factura','','ver_papa_detalle_factura','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_papa_nro_factura*}','ver_papa_nro_factura','','ver_papa_nro_factura','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_papa_proveedor*}','ver_papa_proveedor','','ver_papa_proveedor','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_papa_valor_factura*}','ver_papa_valor_factura','','ver_papa_valor_factura','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_tipo_gasto*}','ver_tipo_gasto','','ver_tipo_gasto','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_papa_fecha_factura*}','ver_papa_fecha_factura','','ver_papa_fecha_factura','','funciones.php','m','|-formato-|')||

/*inicio_datos--{*cargar_datos*},{*mostrar_estado_proceso*},{*mostrar_formato*},{*ruta_orden_pago*},{*ver_dependencia_creador*},{*ver_fecha_solicitud*},{*ver_papa_detalle_factura*},{*ver_papa_fecha_factura*},{*ver_papa_nro_factura*},{*ver_papa_proveedor*},{*ver_papa_valor_factura*},{*ver_tipo_gasto*}--fin_datos*/