INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*digitalizar_formato_radicacion*}','digitalizar_formato_radicacion','','digitalizar_formato_radicacion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_email*}','validar_email','','validar_email','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_fecha_reporte*}','ver_fecha_reporte','','ver_fecha_reporte','ver_fecha_reporte','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_mensajes*}','ver_mensajes','','ver_mensajes','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos_pqrsf*}','mostrar_anexos_pqrsf','','mostrar_anexos_pqrsf','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_radicado_pqrsf*}','mostrar_radicado_pqrsf','','mostrar_radicado_pqrsf','mostrar_radicado_pqrsf','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','188@242,1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*generar_qr_pqrsf*}','generar_qr_pqrsf','','generar_qr_pqrsf','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_digitalizacion_formato_pqr*}','validar_digitalizacion_formato_pqr','','validar_digitalizacion_formato_pqr','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','251,1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||

/*inicio_datos--{*digitalizar_formato_radicacion*},{*fecha_formato*},{*formato_numero*},{*generar_qr_pqrsf*},{*logo_empresa*},{*mostrar_anexos_pqrsf*},{*mostrar_radicado_pqrsf*},{*nombre_formato*},{*transferencia_automatica*},{*validar_digitalizacion_formato_pqr*},{*validar_email*},{*ver_fecha_reporte*},{*ver_mensajes*}--fin_datos*/