INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*digitalizar_formato_radicacion*}','digitalizar_formato_radicacion','','digitalizar_formato_radicacion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_empresa*}','nombre_empresa','','nombre_empresa','nombre_empresa','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_datos_hijos*}','mostrar_datos_hijos','','mostrar_datos_hijos','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_radicado_pqrsf*}','mostrar_radicado_pqrsf','','mostrar_radicado_pqrsf','mostrar_radicado_pqrsf','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_fecha_reporte*}','ver_fecha_reporte','','ver_fecha_reporte','ver_fecha_reporte','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','188@242,1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_digitalizacion_formato_pqr*}','validar_digitalizacion_formato_pqr','','validar_digitalizacion_formato_pqr','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','251,1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*enlace_llenar_datos_radicacion_rapida_pqrsf*}','enlace_llenar_datos_radicacion_rapida_pqrsf','','enlace_llenar_datos_radicacion_rapida_pqrsf','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_codigo_qr*}','mostrar_codigo_qr','','mostrar_codigo_qr','Muestra el codigo QR','../../app/qr/librerias.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*add_edit_pqrsf*}','add_edit_pqrsf','','add_edit_pqrsf','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*post_edit_pqrsf*}','post_edit_pqrsf','','post_edit_pqrsf','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*post_aprobar_pqrsf*}','post_aprobar_pqrsf','','post_aprobar_pqrsf','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_listado_distribucion_documento*}','mostrar_listado_distribucion_documento','','mostrar_listado_distribucion_documento','','../../app/distribucion/funciones_distribucion.php','m','|-formato-|')||

/*inicio_datos--{*add_edit_pqrsf*},{*digitalizar_formato_radicacion*},{*enlace_llenar_datos_radicacion_rapida_pqrsf*},{*fecha_formato*},{*formato_numero*},{*logo_empresa*},{*mostrar_codigo_qr*},{*mostrar_datos_hijos*},{*mostrar_estado_proceso*},{*mostrar_listado_distribucion_documento*},{*mostrar_radicado_pqrsf*},{*nombre_empresa*},{*nombre_formato*},{*post_aprobar_pqrsf*},{*post_edit_pqrsf*},{*transferencia_automatica*},{*validar_digitalizacion_formato_pqr*},{*ver_fecha_reporte*}--fin_datos*/