INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('serie_idserie','SERIE DOCUMENTAL','INT','11','0','','a','Procedimiento','1040','','hidden','2','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('idft_procedimiento','PROCEDIMIENTO','INT','11','1','','a,e','','','pk','hidden','3','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('documento_iddocumento','DOCUMENTO ASOCIADO','INT','11','1','','a,e','','','i','hidden','4','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('firma','FIRMAS DIGITALES','INT','11','1','','a,e','','1','i','hidden','5','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('encabezado','ENCABEZADO','INT','11','1','1','a,e','','1','i','hidden','6','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('dependencia','DEPENDENCIA DEL CREADOR DEL DOCUMENTO','INT','11','1','{*buscar_dependencia*}','a,e','','','i','hidden','1','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('version','Version','VARCHAR','255','0','','a,e','Version','','','hidden','9','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('nombre','Nombre','VARCHAR','255','1','','a,e,p,d,b','Nombre del Procedimiento','','','text','10','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('estado','Estado','VARCHAR','255','1','ELABORACION,ELABORACION;REVISION,REVISION;APROBACION,APROBACION;DISTRIBUCION,DISTRIBUCION;INACTIVO,INACTIVO','a,e,b','Estado Actual del Proceso :
ELABORACION,REVISION,APROBACION,DISTRIBUCION,INACTIVO ','ELABORACION','','radio','11','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('objetivo','Objetivo','TEXT','','1','','a,e,d,b','Objetivo especifico del Procedimiento','','','hidden','12','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('definicion','Definicion','TEXT','','1','','a,e','Definicion del procedimiento','','','hidden','14','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('ft_proceso','procedimiento','INT','11','1','194','a','Procedimiento','','fk','detalle','15','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('dispocisiones_generales','Disposiciones Generales','TEXT','','0','','a,e','Disposiciones Generales','','','hidden','16','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('anexos','Anexos Digitales','VARCHAR','255','0','','a,e','Anexos Digitales al Procedimiento','','','archivo','17','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('acta','Acta','VARCHAR','255','0','','a,e','Acta con que fue aprobado el procedimiento','','','hidden','18','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('aprobado_por','Datos para Aprobar el Documento','VARCHAR','255','0','','a,e','Datos que deben quedar guardados de quien ( Nombre y Cargo de quien Aprueba) o que (Acta administrativa o documento legal) aprueba el documento','','','hidden','19','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('secretarias','Secretarias Vinculadas','VARCHAR','255','0','../../test_serie.php?tabla=dependencia;1;0;1;1;0;2','a,e','Secretarias vinculadas','','','arbol','20','','','0','1','|-formato_idformato-|')||
