INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos_memo*}','mostrar_anexos_memo','','mostrar_anexos_memo','mostrar_anexos_memo','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_anexos_memo*}','mostrar_anexos_memo','','mostrar_anexos_memo','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_empresa*}','nombre_empresa','','nombre_empresa','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*aprobacion*}','aprobacion','','aprobacion','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*vigencia_procedimiento*}','vigencia_procedimiento','','vigencia_procedimiento','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*vigencia*}','vigencia','','vigencia','vigencia','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*listado_pasos_procedimiento*}','listado_pasos_procedimiento','','Pasos','Listado de Pasos del Procedimiento','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*empresa*}','empresa','','Empresa','Nombre de la empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*control_procedimiento*}','control_procedimiento','','Puntos de Control ','Puntos de Control','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*listar_pasos_procedimiento*}','listar_pasos_procedimiento','','listar_pasos_procedimiento','listar_pasos_procedimiento','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica',',1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','secretarias,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||

/*inicio_datos--{*aprobacion*},{*control_procedimiento*},{*empresa*},{*listado_pasos_procedimiento*},{*listar_pasos_procedimiento*},{*logo_empresa*},{*mostrar_anexos_memo*},{*nombre_empresa*},{*transferencia_automatica*},{*vigencia*},{*vigencia_procedimiento*}--fin_datos*/