INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_fecha*}','mostrar_fecha','','mostrar_fecha','mostrar_fecha','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*enviar_adicionar*}','enviar_adicionar','','enviar_adicionar','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_radicado_entrada*}','mostrar_radicado_entrada','','mostrar_radicado_entrada','','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_digitalizacion_formato_radicacion*}','validar_digitalizacion_formato_radicacion','','validar_digitalizacion_formato_radicacion','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*vincular_flujo*}','vincular_flujo','','vincular_flujo','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','copia_a,2','transferencia_automatica','transferencia_automaticatransferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*cambiar_estado*}','cambiar_estado','','cambiar_estado','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*digitalizar_formato_radicacion*}','digitalizar_formato_radicacion','','digitalizar_formato_radicacion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','destino,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','destino,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','copia_a,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*llenar_datos_funcion*}','llenar_datos_funcion','','llenar_datos_funcion','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*quitar_descripcion_entrada*}','quitar_descripcion_entrada','','quitar_descripcion_entrada','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*imagenes_digitalizadas_funcion*}','imagenes_digitalizadas_funcion','','imagenes_digitalizadas_funcion','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*obtener_informacion_proveedor*}','obtener_informacion_proveedor','','obtener_informacion_proveedor','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferir_con_copia*}','transferir_con_copia','','transferir_con_copia','','funciones.php','','|-formato-|')||

/*inicio_datos--{*cambiar_estado*},{*digitalizar_formato_radicacion*},{*enviar_adicionar*},{*fecha_formato*},{*formato_numero*},{*imagenes_digitalizadas_funcion*},{*llenar_datos_funcion*},{*logo_empresa*},{*mostrar_estado_proceso*},{*mostrar_fecha*},{*mostrar_radicado_entrada*},{*nombre_formato*},{*obtener_informacion_proveedor*},{*quitar_descripcion_entrada*},{*transferencia_automatica*},{*transferir_con_copia*},{*validar_digitalizacion_formato_radicacion*},{*vincular_flujo*}--fin_datos*/