INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('serie_idserie','Tipo de documento','INT','11','1','../../test_serie_funcionario.php;2;0;1;1;0;1','a','Salida','3','','arbol','7','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('anexos_fisicos','ANEXOS FISICOS','INT','11','0','1,CD-ROM;2,DISKETE;3,DVD;4,DOCUMENTO;5,FAX;6,REVISTA O LIBRO;7,VIDEO;8,OTROS ANEXOS','a,e,b','','','','select','13','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('persona_natural','Persona natural o jur&iacute;dica','VARCHAR','255','1','unico@nombre,identificacion@cargo,empresa,direccion,telefono,email,titulo,ciudad','a,e,b','','','','ejecutor','10','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('descripcion_salida','DESCRIPCION O ASUNTO','TEXT','1000','1','sin_tiny','a,e,p,d,b','','','','textarea','11','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('descripcion_anexos','DESCRIPCION ANEXOS FISICOS','VARCHAR','1000','0','sin_tiny','a,e,b','','','','textarea','14','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('estado_radicado','Estado de radicado','VARCHAR','255','0','','a,e,b','1:Aprobado
2:Iniciado','1','','hidden','17','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('numero_radicado','NUMERO DE RADICADO','INT','11','0','{*mostrar_radicado_salida*}','a,e,b','','','','text','3','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('area_responsable','Funcionario responsable','VARCHAR','255','1','../../test.php?rol=1;1;0;1;1;0;5','a,e,b','','','','arbol','6','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('idft_radicacion_salida','RADICACION_SALIDA','INT','11','1','','a,e','','','ai,pk','hidden','9','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('documento_iddocumento','DOCUMENTO ASOCIADO','INT','11','1','','a,e','','','i','hidden','8','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('dependencia','DEPENDENCIA DEL CREADOR DEL DOCUMENTO','INT','11','1','{*buscar_dependencia*}','a,e','','','i','hidden','1','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('firma','FIRMAS DIGITALES','INT','11','1','','a,e','','1','','hidden','5','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('tipo_mensajeria','TIPO DE MENSAJERIA','INT','11','1','1,Mensajeria externa;2,Mensajeria interna;3,Entrega personal','a,e,b','','1','','radio','15','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('mensajeros','Mensajeros','INT','15','0','{*mostrar_mensajeros*}','a,e,b','','','','text','16','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('num_folios','Numero de folios','INT','11','1','0@1000@1@0','a,e,b','','','','spin','12','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('estado_documento','ESTADO DEL DOCUMENTO','INT','11','1','','a,e','','1','','hidden','0','','','0','1','|-formato_idformato-|')||
