INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_fecha*}','mostrar_fecha','','mostrar_fecha','mostrar_fecha','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*fecha_formato*}','fecha_formato','','fecha_formato','fecha_formato','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*digitalizacion_formato_salida*}','digitalizacion_formato_salida','','digitalizacion_formato_salida','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*enviar_adicionar_salida*}','enviar_adicionar_salida','','enviar_adicionar_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_radicado_salida*}','mostrar_radicado_salida','','mostrar_radicado_salida','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*llenar_datos_funcion_salida*}','llenar_datos_funcion_salida','','llenar_datos_funcion_salida','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*cambiar_estado_salida*}','cambiar_estado_salida','','cambiar_estado_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*actualizar_campos_documento_salida*}','actualizar_campos_documento_salida','','actualizar_campos_documento_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_digitalizacion_formato_salida*}','validar_digitalizacion_formato_salida','','validar_digitalizacion_formato_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_mensajeros*}','mostrar_mensajeros','','mostrar_mensajeros','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*registrar_salida*}','registrar_salida','','registrar_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*quitar_descripcion_salida*}','quitar_descripcion_salida','','quitar_descripcion_salida','','funciones.php','e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*obtener_informacion_proveedor_salida*}','obtener_informacion_proveedor_salida','','obtener_informacion_proveedor_salida','','funciones.php','m','|-formato-|')||

/*inicio_datos--{*actualizar_campos_documento_salida*},{*cambiar_estado_salida*},{*digitalizacion_formato_salida*},{*enviar_adicionar_salida*},{*fecha_formato*},{*formato_numero*},{*llenar_datos_funcion_salida*},{*logo_empresa*},{*mostrar_fecha*},{*mostrar_mensajeros*},{*mostrar_radicado_salida*},{*nombre_formato*},{*obtener_informacion_proveedor_salida*},{*quitar_descripcion_salida*},{*registrar_salida*},{*validar_digitalizacion_formato_salida*}--fin_datos*/