INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('serie_idserie','SERIE DOCUMENTAL','INT','11','1','','a','Radicaci&oacute;n de Facturas','1024','fk','hidden','20','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('adjuntar','Adjuntar','VARCHAR','','0','','a,e,b','','','','archivo','16','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('detalle_factura','Detalle de Factura','VARCHAR','','1','','a,e,b','','','','text','10','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('empresa_guia','Empresa Guia','VARCHAR','','0','','a,e,b','','','','text','15','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('ft_orden_compra','Orden de compra','INT','11','1','{*listar_ordenes_compra*}','a,e,b','','','','select','5','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('guia','Gu&iacute;a','VARCHAR','','0','','a,e,b','','','','text','14','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('numero_factura','N&uacute;mero Factura','VARCHAR','','1','','a,e,p,d,b','','','','text','8','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('observaciones','Observaciones','TEXT','','0','','a,e,b','','','','textarea','13','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('proveedor','Proveedor','VARCHAR','','1','unico@nombre,identificacion@direccion','a,e,b','','','','ejecutor','9','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('responsable_op','Responsable Orden de Pago','VARCHAR','','1','../../test.php?rol=1&sin_padre=1;2;0;1;1;0;0','a,e,b','','','','arbol','12','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('tipo_documento','Tipo Documento','INT','11','1','1,Factura;2,Solicitud de Pago','a,e,b','','','','radio','3','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('valor_factura','Valor Factura','VARCHAR','','1','','a,e,b','','','','text','11','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('idft_radicacion_facturas','RADICACION_FACTURAS','INT','11','1','','a,e','','','ai,pk','hidden','17','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('documento_iddocumento','DOCUMENTO ASOCIADO','INT','11','1','','a,e','','','i','hidden','18','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('dependencia','DEPENDENCIA DEL CREADOR DEL DOCUMENTO','INT','11','1','{*buscar_dependencia*}','a,e','','','i','hidden','2','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('encabezado','ENCABEZADO','INT','11','1','','a,e','','1','','hidden','1','','','0','1','|-formato_idformato-|')||
INSERT INTO campos_formato(nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible,formato_idformato) VALUES('firma','FIRMAS DIGITALES','INT','11','1','','a,e','','1','','hidden','19','','','0','1','|-formato_idformato-|')||
