INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_digitalizacion_formato*}','validar_digitalizacion_formato','','validar_digitalizacion_formato','validar_digitalizacion_formato','../librerias/funciones_formatos_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*digitalizar_formato*}','digitalizar_formato','','digitalizar_formato','digitalizar_formato','../librerias/funciones_formatos_generales.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*cargar_remitente_orden_compra*}','cargar_remitente_orden_compra','','cargar_remitente_orden_compra','','funciones.php','a','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*codigo_organizacion*}','codigo_organizacion','','codigo_organizacion','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*enviar_colilla_factura*}','enviar_colilla_factura','','enviar_colilla_factura','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*listar_ordenes_compra*}','listar_ordenes_compra','','listar_ordenes_compra','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_codigo_organizacion*}','mostrar_codigo_organizacion','','mostrar_codigo_organizacion','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ordenes_compra_vinculadas*}','ordenes_compra_vinculadas','','ordenes_compra_vinculadas','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_fechas*}','validar_fechas','','validar_fechas','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_valor_factura*}','ver_valor_factura','','ver_valor_factura','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','','transferencia_automatica','','../librerias/funciones_generales.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_responsable_op*}','ver_responsable_op','','ver_responsable_op','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_imagenes_factura*}','mostrar_imagenes_factura','','mostrar_imagenes_factura','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_adjuntar*}','ver_adjuntar','','ver_adjuntar','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','responsable_op,2','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||

/*inicio_datos--{*cargar_remitente_orden_compra*},{*codigo_organizacion*},{*digitalizar_formato*},{*enviar_colilla_factura*},{*listar_ordenes_compra*},{*mostrar_codigo_organizacion*},{*mostrar_estado_proceso*},{*mostrar_imagenes_factura*},{*ordenes_compra_vinculadas*},{*transferencia_automatica*},{*validar_digitalizacion_formato*},{*validar_fechas*},{*ver_adjuntar*},{*ver_responsable_op*},{*ver_valor_factura*}--fin_datos*/