INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_estado_proceso*}','mostrar_estado_proceso','','mostrar_estado_proceso','mostrar_estado_proceso','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*formato_numero*}','formato_numero','','formato_numero','formato_numero','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*logo_empresa*}','logo_empresa','','logo_empresa','logo_empresa','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*nombre_formato*}','nombre_formato','','nombre_formato','','../librerias/encabezado_pie_pagina.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_formato*}','mostrar_formato','','mostrar_formato','','../class_transferencia.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*total_horas*}','total_horas','','total_horas','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ocultar_mostrar_motivo*}','ocultar_mostrar_motivo','','ocultar_mostrar_motivo','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_codigo_nomina_funcionario*}','mostrar_codigo_nomina_funcionario','','mostrar_codigo_nomina_funcionario','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*validar_fecha_menor_formato_autorizacion_salida*}','validar_fecha_menor_formato_autorizacion_salida','','validar_fecha_menor_formato_autorizacion_salida','','funciones.php','a,e','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_nombre_apellido_funcionario*}','mostrar_nombre_apellido_funcionario','','mostrar_nombre_apellido_funcionario','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_cargo_dependencia_funcionario*}','mostrar_cargo_dependencia_funcionario','','mostrar_cargo_dependencia_funcionario','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*crear_ruta_aprobacion_formato_aut_salida*}','crear_ruta_aprobacion_formato_aut_salida','','crear_ruta_aprobacion_formato_aut_salida','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*terminar_actividad_manual_sol*}','terminar_actividad_manual_sol','','terminar_actividad_manual_sol','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*mostrar_campos_fecha_motivo_documento*}','mostrar_campos_fecha_motivo_documento','','mostrar_campos_fecha_motivo_documento','','funciones.php','','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferir_porteria*}','transferir_porteria','','transferir_porteria','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*hora_entrada_reportada*}','hora_entrada_reportada','','hora_entrada_reportada','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*ver_boton_cierre*}','ver_boton_cierre','','ver_boton_cierre','','funciones.php','m','|-formato-|')||
INSERT INTO funciones_formato(nombre,nombre_funcion,parametros,etiqueta,descripcion,ruta,acciones,formato) VALUES('{*transferencia_automatica*}','transferencia_automatica','231,1','transferencia_automatica','transferencia_automatica','../librerias/funciones_generales.php','','|-formato-|')||

/*inicio_datos--{*crear_ruta_aprobacion_formato_aut_salida*},{*formato_numero*},{*hora_entrada_reportada*},{*logo_empresa*},{*mostrar_campos_fecha_motivo_documento*},{*mostrar_cargo_dependencia_funcionario*},{*mostrar_codigo_nomina_funcionario*},{*mostrar_estado_proceso*},{*mostrar_formato*},{*mostrar_nombre_apellido_funcionario*},{*nombre_formato*},{*ocultar_mostrar_motivo*},{*terminar_actividad_manual_sol*},{*total_horas*},{*transferencia_automatica*},{*transferir_porteria*},{*validar_fecha_menor_formato_autorizacion_salida*},{*ver_boton_cierre*}--fin_datos*/