<html><title>.:ADICIONAR CARTAS REMITIDAS:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">CARTAS REMITIDAS</td></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_citas_ejecutadas"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_citas_ejecutadas"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_citas_ejecutadas);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3023)); ?>"><input type="hidden" name="idft_carta_citas" value="<?php echo(validar_valor_campo(3024)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3025)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3027)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3028)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(266,3026);?></tr><tr>
                   <td class="encabezado" width="20%" title="">PARA*</td>
                   <td bgcolor="#F5F5F5">
                   <input type="hidden"  class="required"  name="destino" id="destino" value=""><?php componente_ejecutor("3029",@$_REQUEST["iddoc"]); ?></td>
                  </tr><tr>
                     <td class="encabezado" width="20%" title="">ASUNTO*</td>
                     <td bgcolor="#F5F5F5"><input   class="required"   tabindex='1'  type="text" size="100" id="asunto" name="asunto"  value="<?php echo(validar_valor_campo(3030)); ?>"></td>
                    </tr><input type="hidden" name="citas_remitidas" value="<?php echo(validar_valor_campo(3031)); ?>"><?php ingresar_remitidos(266,NULL);?><input type="hidden" name="campo_descripcion" value="3030"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(266);?></td></tr></table></form></body></html>