<html><title>.:ADICIONAR EMPRESAS INVITADAS:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../librerias/funciones_item.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(1019)); ?>"><tr>
                   <td class="encabezado" width="20%" title="">EMPRESA Y/O PROVEEDOR*</td>
                   <td bgcolor="#F5F5F5">
                   <input type="hidden" maxlength="255"  class="required"  name="empresa_proveedor" id="empresa_proveedor" value=""><?php componente_ejecutor("1020",@$_REQUEST["iddoc"]); ?></td>
                  </tr><tr>
                     <td class="encabezado" width="20%" title="">ENTREGA COTIZACI&Oacute;N*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(83,1021,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="idft_" value="<?php echo(validar_valor_campo(1022)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(1023)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(83,1024);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(1025)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(1026)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_acta_evaluacion"  value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden"  name="idpadre"  value="<?php echo $_REQUEST["idpadre"]; ?>"><?php } ?><tr><td class="encabezado">ACCION A SEGUIR LUEGO DE GUARDAR</td><td ><input type="radio" name="opcion_item" value="adicionar">Adicionar otro&nbsp;&nbsp;<input type="radio" name="opcion_item" value="terminar">Terminar</td></tr><input type="hidden" name="campo_descripcion" value="1020"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="formato" value="empresas_invitadas"><input type="hidden" name="accion" value="guardar_item" ><tr><td colspan='2'><?php submit_formato(83);?></td></tr></table></form></body></html>