<html><title>.:ADICIONAR 2. RESPUESTA PQRSF:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">2. RESPUESTA PQRSF</td></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3600)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(307,3599);?></tr><tr>
                     <td class="encabezado" width="20%" title="">PARA*</td>
                     <?php email_papa(307,3596);?></tr><tr>
                     <td class="encabezado" width="20%" title="">ASUNTO*</td>
                     <?php adicionar_asunto(307,3594);?></tr><tr>
                     <td class="encabezado" width="20%" title="">COMENTARIO*</td>
                     <td class="celda_transparente"><textarea  tabindex='1'  name="comentario" id="comentario" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(3595)); ?></textarea></td>
                    </tr><input type="hidden" name="idft_respuesta_pqrsf" value="<?php echo(validar_valor_campo(3597)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3598)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3601)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_pqrsf"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_pqrsf"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_pqrsf);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3593)); ?>"><input type="hidden" name="campo_descripcion" value="3594"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(307);?></td></tr></table></form></body></html>