<html><title>.:ADICIONAR ENTREGA DE PR&Eacute;STAMO:.</title><head><?php include_once("../../librerias_saia.php"); ?><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $(document).ready(function() {
	// validar los campos del formato
			  		$('#formulario_formatos').validate();

				});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">ENTREGA DE PRÉSTAMO</td></tr><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5118)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_solicitud_prestamo"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_solicitud_prestamo"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_solicitud_prestamo);} ?><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5121)); ?>"><tr id="tr_dependencia">
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(413,5122);?></tr><tr id="tr_fecha_entrega">
                    <td class="encabezado" width="20%" title="">FECHA DE PRESTAMO*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='1'  type="text" readonly="true" name="fecha_entrega"  class="required dateISO"  id="fecha_entrega" value="<?php echo(date("Y-m-d H:i")); ?>"><?php selector_fecha("fecha_entrega","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr id="tr_transferencia_presta">
                     <td class="encabezado" width="20%" title="">EXPEDIENTE VINCULADO*</td>
                     <?php llenar_transferencia_vinculada_entrega(413,5206);?></tr><tr id="tr_observaciones">
                     <td class="encabezado" width="20%" title="">OBSERVACIONES*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="observaciones" id="observaciones" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(5129)); ?></textarea></td></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5123)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5124)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5119)); ?>"><input type="hidden" name="estado_devolucion" value="<?php echo(validar_valor_campo(5130)); ?>"><input type="hidden" name="fecha_devolucion" value="<?php echo(validar_valor_campo(5131)); ?>"><input type="hidden" name="observaciones_devolu" value="<?php echo(validar_valor_campo(5132)); ?>"><input type="hidden" name="usuario_devolucion" value="<?php echo(validar_valor_campo(5133)); ?>"><input type="hidden" name="idft_entrega_prestamo" value="<?php echo(validar_valor_campo(5120)); ?>"><input type="hidden" name="campo_descripcion" value="5125"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(413);?></td></tr></table></form></body></html>