<html><title>.:EDITAR ENTREGA DE PR&Eacute;STAMO:.</title><head><?php include_once("../../librerias_saia.php"); ?><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $(document).ready(function() {
	// validar los campos del formato
			  		$('#formulario_formatos').validate();

				});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">ENTREGA DE PRÉSTAMO</td></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(mostrar_valor_campo('documento_iddocumento',413,$_REQUEST['iddoc'])); ?>"><tr id="tr_dependencia">
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(413,5122,$_REQUEST['iddoc']);?></tr><tr id="tr_fecha_entrega">
                    <td class="encabezado" width="20%" title="">FECHA DE PRESTAMO*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='1'  type="text" readonly="true" name="fecha_entrega"  class="required dateISO"  id="fecha_entrega" value="<?php mostrar_valor_campo('fecha_entrega',413,$_REQUEST['iddoc']); ?>"><?php selector_fecha("fecha_entrega","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr id="tr_transferencia_presta">
                     <td class="encabezado" width="20%" title="">EXPEDIENTE VINCULADO*</td>
                     <?php llenar_transferencia_vinculada_entrega(413,5206,$_REQUEST['iddoc']);?></tr><tr id="tr_observaciones">
                     <td class="encabezado" width="20%" title="">OBSERVACIONES*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="observaciones" id="observaciones" cols="53" rows="3" class="tiny_basico required"><?php echo(mostrar_valor_campo('observaciones',413,$_REQUEST['iddoc'])); ?></textarea></td></tr><input type="hidden" name="encabezado" value="<?php echo(mostrar_valor_campo('encabezado',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="firma" value="<?php echo(mostrar_valor_campo('firma',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="estado_devolucion" value="<?php echo(mostrar_valor_campo('estado_devolucion',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="fecha_devolucion" value="<?php echo(mostrar_valor_campo('fecha_devolucion',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="observaciones_devolu" value="<?php echo(mostrar_valor_campo('observaciones_devolu',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="usuario_devolucion" value="<?php echo(mostrar_valor_campo('usuario_devolucion',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="idft_entrega_prestamo" value="<?php echo(mostrar_valor_campo('idft_entrega_prestamo',413,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="campo_descripcion" value="<?php echo('5125'); ?>"><input type="hidden" name="formato" value="413"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="editar" ><input type="hidden" name="item" value="<?php echo $_REQUEST["item"]; ?>" ><input type="hidden" name="anterior" value="<?php echo $_REQUEST["campo"]; ?>" ><tr><td colspan='2'><?php submit_formato(413,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>