<html><title>.:ADICIONAR AVANCES TAREA:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">AVANCES TAREA</td></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_recordar_tarea"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_recordar_tarea"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_recordar_tarea);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(2709)); ?>"><input type="hidden" name="idft_avances" value="<?php echo(validar_valor_campo(2710)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(2711)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(240,2712);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(2713)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(2714)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">ESTADO*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(240,2725,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="">DESCRIPCI&Oacute;N*</td>
                     <td class="celda_transparente"><textarea  tabindex='1'  name="descripcion_formato" id="descripcion_formato" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(2726)); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">FECHA*</td>
                     <?php fecha_formato(240,2727);?></tr><?php validar_ingreso_funcion(240,NULL);?><input type="hidden" name="campo_descripcion" value="2726"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(240);?></td></tr></table></form></body></html>