<html><title>.:ADICIONAR SOLICITUD DE CONFIGURACION:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">SOLICITUD DE CONFIGURACION</td></tr><input type="hidden" name="idft_solic_configura" value="<?php echo(validar_valor_campo(3943)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3944)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(338,3945);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3946)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3947)); ?>"><tr>
                       <td class="encabezado" width="20%" title="">FECHA*</td><td colspan="2" bgcolor="#F5F5F5"><span class="phpmaker"><input  tabindex='1'  type="text" readonly="true"  class="required dateISO"  name="fecha_config" id="fecha_config" tipo="fecha" value="<?php echo(date("Y-m-d")); ?>"><?php selector_fecha("fecha_config","formulario_formatos","Y-m-d",date("m"),date("Y"),"default.css","../../","AD:VALOR","VENTANA",FALSE,FALSE); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">CONFIGURACION*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="solicitud" id="solicitud" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(3942)); ?></textarea></td>
                    </tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_clasif_solicitud"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_clasif_solicitud"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_clasif_solicitud);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3940)); ?>"><input type="hidden" name="campo_descripcion" value="3942"><tr><td colspan='2'><?php submit_formato(338);?></td></tr></table></form></body></html>