<?php

declare (strict_types = 1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190130215601 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        $conn = $this->connection;
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span><div class="controls">{*procesar_archivo*}</div></li>'], ["nombre" => "archivo"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span><div class="controls">{*procesar_remitente*}</div></li>'], ["nombre" => "ejecutor"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span><div class="controls">{*procesar_ruta_fija_documento*}</div></li>'], ["nombre" => "ruta_fija_documento"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span><div class="controls">{*procesar_ruta_documento*}</div></li>'], ["nombre" => "ruta_documento"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}  <span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span><div class="controls"><div id="{*nombre*}" class="highslide" style="cursor:pointer;" name="{*nombre*}">{*etiqueta*}</div><script type="text/javascript">$(document).ready(function(){hs.graphicsDir = "{*obtener_ruta_db_superior*}anexosdigitales/highslide-4.0.10/highslide/graphics/";hs.outlineType = "rounded-white";$("#{*nombre*}").click(function(e){e.preventDefault();{*procesar_conector_highslide*}});});</script></div></li>'], ["nombre" => "conector_highslide"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;">{*procesar_etiqueta*}</span></li>'], ["nombre" => "etiqueta"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b>></span> <div class="controls">{*procesar_file*}</div></li>'], ["nombre" => "file"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;">{*etiqueta*}{*obligatoriedad*}</span> <div class="controls">{*procesar_textarea_tiny*}</div></li>'], ["nombre" => "textarea_tiny"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}"><span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> {*clase_eliminar_pantalla_componente*}<div class="controls"><div id="{*nombre*}" class="input-append date">{*procesar_datetime*}<span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span></div></div></li>'], ["nombre" => "datetime"]);       
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;">{*etiqueta*}{*obligatoriedad*}</span> <div class="controls"><div id="{*nombre*}" class="input-append date">{*procesar_date*}<span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span></div></div></li><script type="text/javascript">$(document).ready(function(){$("#{*nombre*}").datetimepicker({language: "es",pick12HourFormat: true,pickTime: false}).on("changeDate", function(e){$(this).datetimepicker("hide");});});</script>'], ["nombre" => "date"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span> <div class="controls"><div id="{*nombre*}" class="highslide" style="cursor:pointer;" name="{*nombre*}">{*etiqueta*}</div><script type="text/javascript">$(document).ready(function(){hs.graphicsDir = "{*obtener_ruta_db_superior*}highslide/graphics/";hs.outlineType = "rounded-white";$("#{*nombre*}").live("click",function(e){e.preventDefault();{*procesar_highslide*}});});</script></div></li>'], ["nombre" => "highslide"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span><div class="controls"><div class="input-append"><input type="text" class="daterange" name="etiqueta_{*nombre*}" id="etiqueta_{*nombre*}" value="" readonly/><input type="hidden" name="{*nombre*}" id="{*nombre*}" value="" /><span class="add-on" id="boton_{*nombre*}"><i class="icon-calendar"></i></span></div></div></li><script type="text/javascript">$(document).ready(function(){$("#boton_{*nombre*}").daterangepicker({startDate: moment().subtract("days", 29),opens: "left",endDate: moment(),showDropdowns: true,showWeekNumbers: true,timePicker: false,timePickerIncrement: 1,timePicker12Hour: true,ranges: {"Hoy": [moment(), moment()],"Pasados 30 Dias": [moment().subtract("days", 29), moment()],	"Mes Pasado": [moment().subtract("month", 1).startOf("month"), moment().subtract("month", 1).endOf("month")]},opens: "left",buttonClasses: ["btn btn-default"],applyClass: "btn-small btn-primary",cancelClass: "btn-small",format: "YYYY-MM-DD",separator: " - ",locale: {applyLabel: "Seleccionar",fromLabel: "De",toLabel: "A",customRangeLabel: "Seleccione rango",daysOfWeek: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi","Sa"],monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Novimbre", "Diciembre"],firstDay: 1}},function(start, end) {$("#etiqueta_{*nombre*}").val(start.format("YYYY-MM-DD")+" a "+end.format("YYYY-MM-DD"));$("#{*nombre*}").val(start.format("YYYY-MM-DD")+","+end.format("YYYY-MM-DD"));});});</script>'], ["nombre" => "daterange"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span> <div class="controls"> {*cargar_listado_inicial_arbol_radio*}  {*busca_componente_arbol_radio*}<div id="esperando_{*nombre*}"><img src="{*obtener_ruta_db_superior*}imagenes/cargando.gif"></div><div id="treebox_{*nombre*}" height="90%"></div>		    <script type="text/javascript">$(document).ready(function(){var browserType;if (document.layers) {browserType = "nn4"}if (document.all) {browserType = "ie"}if (window.navigator.userAgent.toLowerCase().match("gecko")) {browserType= "gecko"}tree_{*nombre*}=new dhtmlXTreeObject("treebox_{*nombre*}","100%","",0);tree_{*nombre*}.enableTreeImages(false);	tree_{*nombre*}.setImagePath("{*obtener_ruta_db_superior*}imgs/");tree_{*nombre*}.enableIEImageFix(true);              tree_{*nombre*}.setOnLoadingStart(cargando_{*nombre*});tree_{*nombre*}.setOnLoadingEnd(fin_cargando_{*nombre*});tree_{*nombre*}.enableCheckBoxes(1);tree_{*nombre*}.enableRadioButtons(true);tree_{*nombre*}.setOnCheckHandler(onNodeSelect_{*nombre*});{*load_datos_arbol_radio*}	function fin_cargando_{*nombre*}(){if (browserType == "gecko")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")")else if (browserType == "ie")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");elsedocument.poppedLayer = eval("document.layers["esperando_{*nombre*}"]");document.poppedLayer.style.display = "none";}function cargando_{*nombre*}() {if (browserType == "gecko" )document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");else if (browserType == "ie")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");elsedocument.poppedLayer =	eval("document.layers["esperando_{*nombre*}"]");document.poppedLayer.style.display = "";}function onNodeSelect_{*nombre*}(nodeId){valor_destino=document.getElementById("{*nombre*}");	if(tree_{*nombre*}.isItemChecked(nodeId)){if(valor_destino.value!=="")	tree_{*nombre*}.setCheck(valor_destino.value,false);						var pos_destino=nodeId.lastIndexOf("_");if(pos_destino>0)					{valor_destino.value=nodeId.substring(0,pos_destino);}else{ valor_destino.value=nodeId;}}else{valor_destino.value="";}}{*caracteristicas_arbol_radio*}		});</script>		</div></li>'], ["nombre" => "arbol_radio"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span> <div class="controls"><a {*procesar_link*} name="{*nombre*}" class="elemento_formulario" idpantalla_campos="{*idpantalla_campos*}"><b>{*etiqueta*}</b></a></div></li>'], ["nombre" => "link"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> <div class="controls">{*procesar_select*}</div></li>'], ["nombre" => "select"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> <div class="controls"><textarea name="{*nombre*}" class="elemento_formulario" placeholder="{*placeholder*}" idpantalla_campos="{*idpantalla_campos*}" id="{*nombre*}">{*procesar_textarea*}</textarea></div></li>'], ["nombre" => "textarea"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span> <div class="controls"><input type="{*etiqueta_html*}" name="{*nombre*}" id="{*nombre*}" class="elemento_formulario" placeholder="{*placeholder*}" idpantalla_campos="{*idpantalla_campos*}" value="{*procesar_password*}" /></div></div>'], ["nombre" => "password"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> </label><div class="controls">{*procesar_checkbox*}</div></li>'], ["nombre" => "checkbox"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*}{*obligatoriedad*}</b></span> <div class="controls"> {*cargar_listado_inicial_arbol_checkbox*}  {*busca_componente_arbol_checkbox*}<div id="esperando_{*nombre*}"><img src="{*obtener_ruta_db_superior*}imagenes/cargando.gif"></div><div id="treebox_{*nombre*}" height="90%" class="arbol_saia"></div>		    <script type="text/javascript">$(document).ready(function(){var browserType;if (document.layers) {browserType = "nn4"}if (document.all) {browserType = "ie"}if (window.navigator.userAgent.toLowerCase().match("gecko")) {browserType= "gecko"}tree_{*nombre*}=new dhtmlXTreeObject("treebox_{*nombre*}","100%","",0);tree_{*nombre*}.enableTreeImages(false);    	tree_{*nombre*}.setImagePath("{*obtener_ruta_db_superior*}imgs/");tree_{*nombre*}.enableIEImageFix(true);              tree_{*nombre*}.setOnLoadingStart(cargando_{*nombre*});tree_{*nombre*}.setOnLoadingEnd(fin_cargando_{*nombre*});tree_{*nombre*}.enableCheckBoxes(1);{*padre_independiente_arbol_checkbox*}tree_{*nombre*}.setOnCheckHandler(onNodeSelect_{*nombre*});{*load_datos_arbol_checkbox*}	function fin_cargando_{*nombre*}(){if (browserType == "gecko")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")")else if (browserType == "ie")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");elsedocument.poppedLayer = eval("document.layers["esperando_{*nombre*}"]");document.poppedLayer.style.display = "none";}function cargando_{*nombre*}() {if (browserType == "gecko" )document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");else if (browserType == "ie")document.poppedLayer = eval("document.getElementById("esperando_{*nombre*}")");elsedocument.poppedLayer =	eval("document.layers["esperando_{*nombre*}"]");document.poppedLayer.style.display = "";}function onNodeSelect_{*nombre*}(nodeId){valor_destino=document.getElementById("{*nombre*}");destinos=tree_{*nombre*}.getAllChecked();var nuevos_valores=destinos.split(",");var cantidad=nuevos_valores.length;var funcionarios=new Array();var indice=0;for(var i=0;i<cantidad;i++){if(nuevos_valores[i].indexOf("#")=="-1"){if(nuevos_valores[i]!=""){funcionarios[indice]=nuevos_valores[i];indice++;}}}valor_destino.value=funcionarios.join(",");}{*caracteristicas_arbol_checkbox*}		});</script>		</div></li>'], ["nombre" => "arbol_checkbox"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> <div class="controls">{*procesar_radio*}</div></li>'], ["nombre" => "radio"]);
        $resp = $conn->update('pantalla_componente', ['componente' => '<li class="ui-state-default element" idpantalla_componente="{*idpantalla_componente*}" idpantalla_campo="{*idpantalla_campos*}" id="pc_{*idpantalla_campos*}" nombre="{*nombre_componente*}">{*clase_eliminar_pantalla_componente*}<span class="ui-icon ui-icon-arrowthick-2-n-s" style="font-size:12px;"><b>{*etiqueta*} {*obligatoriedad*}</b></span> <div class="controls"><input type="{*etiqueta_html*}" name="{*nombre*}" maxlength="{*longitud*}" class="elemento_formulario" placeholder="{*placeholder*}" idpantalla_campos="{*idpantalla_campos*}" value="{*procesar_texto*}" id="{*nombre*}" />{*procesar_opcion_buscar*}</div></li>'], ["nombre" => "text"]);
  

    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }

    public function preUp(Schema $schema) : void
    {
        date_default_timezone_set("America/Bogota");

        if ($this->connection->getDatabasePlatform()->getName() == "mysql") {
            $this->platform->registerDoctrineTypeMapping('enum', 'string');
        }
    }

    public function preDown(Schema $schema) : void
    {
        date_default_timezone_set("America/Bogota");

        if ($this->connection->getDatabasePlatform()->getName() == "mysql") {
            $this->platform->registerDoctrineTypeMapping('enum', 'string');
        }
    }
}