<?php

namespace Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20181219160009 extends AbstractMigration
{
    private $modulo = array(
        array('idmodulo' => '1','pertenece_nucleo' => '1','nombre' => 'agrupador_radicacion','tipo' => 'grouper','imagen' => 'fa fa-envelope-o','etiqueta' => 'CAD','enlace' => '','cod_padre' => '0','orden' => '2'),
        array('idmodulo' => '2','pertenece_nucleo' => '1','nombre' => 'configuracion','tipo' => '1','imagen' => 'fa fa-cogs','etiqueta' => 'Configuraci&oacute;n','enlace' => '','cod_padre' => '1948','orden' => '1'),
        array('idmodulo' => '4','pertenece_nucleo' => '0','nombre' => 'documento','tipo' => '','imagen' => 'fa fa-briefcase','etiqueta' => 'Mis Documentos','enlace' => '','cod_padre' => '1942','orden' => '1'),
        array('idmodulo' => '5','pertenece_nucleo' => '0','nombre' => 'ejecutor','tipo' => '1','imagen' => 'fa fa-user','etiqueta' => 'Terceros externos','enlace' => 'pantallas/buscador_principal.php?idbusqueda=101','cod_padre' => '1946','orden' => '4'),
        array('idmodulo' => '6','pertenece_nucleo' => '0','nombre' => 'radicacion_entrada_formulario','tipo' => '2','imagen' => 'fa fa-inbox','etiqueta' => 'Registrar Correspondencia','enlace' => 'pantallas/formato/principal_formatos_radicacion.php','cod_padre' => '2007','orden' => '2'),
        array('idmodulo' => '9','pertenece_nucleo' => '0','nombre' => 'contador','tipo' => '1','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Contador','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '10','pertenece_nucleo' => '0','nombre' => 'configuracion_boton','tipo' => '','imagen' => 'fa fa-cogs','etiqueta' => 'Configuraci&oacute;n del Sistema','enlace' => 'pantallas/buscador_principal.php?idbusqueda=19','cod_padre' => '2','orden' => '1'),
        array('idmodulo' => '12','pertenece_nucleo' => '0','nombre' => 'cargo','tipo' => '1','imagen' => 'fa fa-cubes','etiqueta' => 'Roles (Jerarqu&iacute;a)','enlace' => 'cargo.php','cod_padre' => '291','orden' => '3'),
        array('idmodulo' => '13','pertenece_nucleo' => '0','nombre' => 'dependencia_cargo','tipo' => '1','imagen' => 'botones/principal/dependencia_cargo.png','etiqueta' => 'Roles','enlace' => 'pantallas/buscador_principal.php?idbusqueda=11','cod_padre' => '9999','orden' => '4'),
        array('idmodulo' => '14','pertenece_nucleo' => '0','nombre' => 'serie','tipo' => '1','imagen' => 'fa fa-list-alt','etiqueta' => 'TRD (Series Documentales)','enlace' => 'pantallas/serie/serielist.php','cod_padre' => '291','orden' => '5'),
        array('idmodulo' => '15','pertenece_nucleo' => '0','nombre' => 'funcionario','tipo' => '1','imagen' => 'fa fa-users','etiqueta' => 'Usuarios (Funcionarios)','enlace' => 'pantallas/buscador_principal.php?idbusqueda=1&default_componente=funcionario','cod_padre' => '291','orden' => '1'),
        array('idmodulo' => '16','pertenece_nucleo' => '0','nombre' => 'dependencia','tipo' => '1','imagen' => 'fa fa-sitemap','etiqueta' => '&Aacute;reas (Dependencias)','enlace' => 'dependencia.php','cod_padre' => '291','orden' => '2'),
        array('idmodulo' => '17','pertenece_nucleo' => '0','nombre' => 'permiso','tipo' => '1','imagen' => 'fa fa-key','etiqueta' => 'Permisos','enlace' => 'permiso_perfiladd.php','cod_padre' => '291','orden' => '4'),
        array('idmodulo' => '18','pertenece_nucleo' => '0','nombre' => 'enrutar','tipo' => '1','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Enrutar','enlace' => 'rutaadd.php','cod_padre' => '1615','orden' => '3'),
        array('idmodulo' => '20','pertenece_nucleo' => '0','nombre' => 'proceso_buzon','tipo' => '2','imagen' => 'botones/principal/en_proceso.png','etiqueta' => 'Ingresados','enlace' => 'pantallas/buscador_principal.php?idbusqueda=9','cod_padre' => '2007','orden' => '5'),
        array('idmodulo' => '21','pertenece_nucleo' => '0','nombre' => 'pendientes','tipo' => '2','imagen' => 'fa fa-flag','etiqueta' => 'Pendiente por Registrar','enlace' => 'pantallas/buscador_principal.php?idbusqueda=7','cod_padre' => '2007','orden' => '3'),
        array('idmodulo' => '24','pertenece_nucleo' => '0','nombre' => 'genera_ingreso','tipo' => '2','imagen' => 'fa fa-qrcode','etiqueta' => 'Generar Sello','enlace' => 'formatos/radicacion_entrada/radicacion_rapida.php?idcategoria_formato=1','cod_padre' => '2007','orden' => '1'),
        array('idmodulo' => '33','pertenece_nucleo' => '1','nombre' => 'documentos_recibidos','tipo' => '2','imagen' => 'fa fa-inbox','etiqueta' => 'Bandeja de Entrada','enlace' => 'views/buzones/index.php?idbusqueda_componente=7','cod_padre' => '4','orden' => '1'),
        array('idmodulo' => '34','pertenece_nucleo' => '1','nombre' => 'documentos_enviados','tipo' => '2','imagen' => 'fa fa-paper-plane','etiqueta' => 'Bandeja de Salida','enlace' => 'views/buzones/index.php?idbusqueda_componente=14','cod_padre' => '4','orden' => '2'),
        array('idmodulo' => '35','pertenece_nucleo' => '0','nombre' => 'log','tipo' => '2','imagen' => 'fa fa-history','etiqueta' => 'Historial','enlace' => 'pantallas/buscador_principal.php?idbusqueda=21','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '36','pertenece_nucleo' => '0','nombre' => 'eliminar_pagina','tipo' => '2','imagen' => 'images/eliminar_pagina.png','etiqueta' => 'Eliminar pagina','enlace' => '#','cod_padre' => '28','orden' => '6'),
        array('idmodulo' => '38','pertenece_nucleo' => '0','nombre' => 'editar_paginas','tipo' => '','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Editar paginas','enlace' => 'auxiliar2.php?modulo=38','cod_padre' => '64','orden' => '1'),
        array('idmodulo' => '41','pertenece_nucleo' => '0','nombre' => 'envio_copias','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso copias','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '44','pertenece_nucleo' => '0','nombre' => 'formatos','tipo' => '2','imagen' => 'pg-form','etiqueta' => 'Formatos','enlace' => 'pantallas/formato/principal_formatos.php','cod_padre' => '9999','orden' => '6'),
        array('idmodulo' => '45','pertenece_nucleo' => '1','nombre' => 'gestion','tipo' => '2','imagen' => 'fa fa-folder-open','etiqueta' => 'Expedientes','enlace' => 'views/dashboard/kaiten_dashboard.php?panels=[{"kConnector": "html.page","url": "pantallas/busquedas/componentes_busqueda.php?idbusqueda=37"}]','cod_padre' => '4','orden' => '4'),
        array('idmodulo' => '64','pertenece_nucleo' => '0','nombre' => 'menu_ordenar','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => '5. MENU DOCUMENTOS','enlace' => '#','cod_padre' => '9999','orden' => '14'),
        array('idmodulo' => '126','pertenece_nucleo' => '0','nombre' => 'documento_siguiente','tipo' => '','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Siguiente documento.','enlace' => 'ordenar.php?accion=mostrar&mostrar_doc=sig','cod_padre' => '64','orden' => '127'),
        array('idmodulo' => '127','pertenece_nucleo' => '0','nombre' => 'documento_anterior','tipo' => '','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Anterior documento.','enlace' => 'ordenar.php?accion=mostrar&mostrar_doc=ant','cod_padre' => '64','orden' => '127'),
        array('idmodulo' => '142','pertenece_nucleo' => '0','nombre' => 'activar_documento','tipo' => '2','imagen' => 'fa fa-plug','etiqueta' => 'Activaci&oacute;n de Registros','enlace' => 'pantallas/buscador_principal.php?idbusqueda=22','cod_padre' => '1946','orden' => '3'),
        array('idmodulo' => '200','pertenece_nucleo' => '1','nombre' => 'dias_habiles','tipo' => '1','imagen' => 'fa fa-calendar','etiqueta' => 'Mi Calendario','enlace' => '','cod_padre' => '1942','orden' => '4'),
        array('idmodulo' => '203','pertenece_nucleo' => '0','nombre' => 'plantillas','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Plantillas','enlace' => 'formatos/formatolist.php','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '210','pertenece_nucleo' => '0','nombre' => 'expediente','tipo' => '','imagen' => 'botones/intermedio/ingresar_expediente.png','etiqueta' => 'Expediente','enlace' => 'expediente_principal.php','cod_padre' => '64','orden' => '14'),
        array('idmodulo' => '216','pertenece_nucleo' => '0','nombre' => 'reemplazo','tipo' => '2','imagen' => 'fa fa-exchange','etiqueta' => 'Reemplazo de usuarios','enlace' => 'pantallas/buscador_principal.php?idbusqueda=56','cod_padre' => '1946','orden' => '1'),
        array('idmodulo' => '224','pertenece_nucleo' => '0','nombre' => 'formato_digital','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Plantillas digitales','enlace' => 'formato_digital.php','cod_padre' => '1615','orden' => '14'),
        array('idmodulo' => '232','pertenece_nucleo' => '0','nombre' => 'editar_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Editar expediente','enlace' => '#','cod_padre' => '45','orden' => '1'),
        array('idmodulo' => '235','pertenece_nucleo' => '0','nombre' => 'graficos_reportes','tipo' => '2','imagen' => 'botones/comentarios/graficos_reportes.png','etiqueta' => 'Graficos y reportes','enlace' => 'graficos/listado_graficos.php?iddoc=@key@','cod_padre' => '64','orden' => '127'),
        array('idmodulo' => '236','pertenece_nucleo' => '0','nombre' => 'modulo_formatos','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Formatos','enlace' => '#','cod_padre' => '9999','orden' => '9'),
        array('idmodulo' => '237','pertenece_nucleo' => '0','nombre' => 'carta','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Comunicaci&oacute;n Externa','enlace' => 'formatos/carta/mostrar_carta.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '238','pertenece_nucleo' => '0','nombre' => 'memorando','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Comunicaci&oacute;n Interna','enlace' => 'formatos/memorando/mostrar_memorando.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '243','pertenece_nucleo' => '0','nombre' => 'admin_almacenamiento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Administracion almacenamiento','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '266','pertenece_nucleo' => '0','nombre' => 'permiso_busqueda_general','tipo' => '','imagen' => '#','etiqueta' => 'Busqueda general','enlace' => '#','cod_padre' => '1615','orden' => '127'),
        array('idmodulo' => '291','pertenece_nucleo' => '1','nombre' => 'organizacion','tipo' => '1','imagen' => 'fa fa-building-o','etiqueta' => 'Organizaci&oacute;n','enlace' => '','cod_padre' => '1944','orden' => '1'),
        array('idmodulo' => '665','pertenece_nucleo' => '0','nombre' => 'modulos','tipo' => '2','imagen' => 'fa fa-cubes','etiqueta' => 'M&oacute;dulos','enlace' => 'pantallas/buscador_principal.php?idbusqueda=16','cod_padre' => '2','orden' => '2'),
        array('idmodulo' => '685','pertenece_nucleo' => '0','nombre' => 'adicionar_listado','tipo' => '2','imagen' => 'botones/principal/admin_listados.png','etiqueta' => 'Listados','enlace' => 'pantallas/buscador_principal.php?idbusqueda=20','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '705','pertenece_nucleo' => '0','nombre' => 'radicados_por_dia','tipo' => '2','imagen' => 'botones/principal/reportes.png','etiqueta' => 'Radicados','enlace' => 'radicadoslist.php','cod_padre' => '1057','orden' => '7'),
        array('idmodulo' => '806','pertenece_nucleo' => '0','nombre' => 'manual_carta','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Elaboraci&AACUTE;;n de Cartas','enlace' => 'ayudas/Manual_carta.pdf','cod_padre' => '807','orden' => '1'),
        array('idmodulo' => '807','pertenece_nucleo' => '0','nombre' => 'ayuda_modulos','tipo' => '1','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Ayudas','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '808','pertenece_nucleo' => '0','nombre' => 'configuracion_de_pagina','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual para configurar p&AACUTE;;gina','enlace' => 'ayudas/Instructivo_configuracion_pagina.pdf','cod_padre' => '807','orden' => '2'),
        array('idmodulo' => '809','pertenece_nucleo' => '0','nombre' => 'manual_busquedas','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual de B&UACUTE;;squedas','enlace' => 'ayudas/Manual_busquedas.pdf','cod_padre' => '807','orden' => '3'),
        array('idmodulo' => '810','pertenece_nucleo' => '0','nombre' => 'manual_circular_externa','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Circular Externa','enlace' => 'ayudas/Manual_circular_externa.pdf','cod_padre' => '807','orden' => '4'),
        array('idmodulo' => '811','pertenece_nucleo' => '0','nombre' => 'manual_circular_interna','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Circular Interna','enlace' => 'ayudas/Manual_circular_interna.pdf','cod_padre' => '807','orden' => '5'),
        array('idmodulo' => '812','pertenece_nucleo' => '0','nombre' => 'manual_documentos_pendientes','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Documentos Pendientes','enlace' => 'ayudas/Manual_Documentos_Pendientes.pdf','cod_padre' => '807','orden' => '6'),
        array('idmodulo' => '813','pertenece_nucleo' => '0','nombre' => 'manual_memorando','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Memorando','enlace' => 'ayudas/Manual_memorando.pdf','cod_padre' => '807','orden' => '7'),
        array('idmodulo' => '814','pertenece_nucleo' => '0','nombre' => 'manual_menu_detalles','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Manual Men&UACUTE;; Detalles','enlace' => 'ayudas/Manual_Menu_Detalles.pdf','cod_padre' => '807','orden' => '8'),
        array('idmodulo' => '821','pertenece_nucleo' => '0','nombre' => 'slider','tipo' => '2','imagen' => 'fa fa-image','etiqueta' => 'Carrusel de Inicio','enlace' => 'carrusel/sliderconfig.php','cod_padre' => '1947','orden' => '1'),
        array('idmodulo' => '830','pertenece_nucleo' => '0','nombre' => 'procesos','tipo' => '','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Procesos','enlace' => 'auxiliar2.php?modulo=830','cod_padre' => '1615','orden' => '5'),
        array('idmodulo' => '861','pertenece_nucleo' => '0','nombre' => 'Workflow','tipo' => '1','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Flujo de informacion','enlace' => 'workflow/mapeo_diagrama.php?key=@key@','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '862','pertenece_nucleo' => '0','nombre' => 'terminar_actividad_paso_manual','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Terminar la actividad del paso','enlace' => 'workflow/terminar_actividad_paso.php?idactividad_paso=@actividad_paso@','cod_padre' => '861','orden' => '1'),
        array('idmodulo' => '864','pertenece_nucleo' => '0','nombre' => 'busqueda_total_series','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Busqueda total en las series','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '865','pertenece_nucleo' => '0','nombre' => 'busqueda_avanzada_documentos','tipo' => '2','imagen' => 'fa fa-search','etiqueta' => 'Buscar','enlace' => 'pantallas/buscador_principal.php?idbusqueda=17','cod_padre' => '9999','orden' => '7'),
        array('idmodulo' => '1006','pertenece_nucleo' => '0','nombre' => 'creacion_formatos','tipo' => '2','imagen' => 'botones/principal/default.png','etiqueta' => 'Creacion de formatos','enlace' => '#','cod_padre' => '44','orden' => '1'),
        array('idmodulo' => '1007','pertenece_nucleo' => '0','nombre' => 'crear_radicacion_entrada','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Radicaci&oacute;n de Correspondencia','enlace' => 'formatos/radicacion_entrada/adicionar_radicacion_entrada.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1008','pertenece_nucleo' => '0','nombre' => 'radicacion_entrada','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Radicaci&oacute;n de Correspondencia','enlace' => 'formatos/radicacion_entrada/mostrar_radicacion_entrada.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1013','pertenece_nucleo' => '0','nombre' => 'listado_flujos','tipo' => '2','imagen' => 'fa fa-share-alt','etiqueta' => 'Flujos de trabajo','enlace' => 'pantallas/buscador_principal.php?idbusqueda=23','cod_padre' => '2','orden' => '4'),
        array('idmodulo' => '1039','pertenece_nucleo' => '0','nombre' => 'crear_carta','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Comunicaci&oacute;n Externa','enlace' => 'formatos/carta/adicionar_carta.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1040','pertenece_nucleo' => '0','nombre' => 'busqueda_total_documentos','tipo' => '2','imagen' => 'fa fa-binoculars','etiqueta' => 'Buscar Admin','enlace' => 'pantallas/buscador_principal.php?idbusqueda=27','cod_padre' => '9999','orden' => '8'),
        array('idmodulo' => '1042','pertenece_nucleo' => '0','nombre' => 'crear_memorando','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Comunicaci&oacute;n Interna','enlace' => 'formatos/memorando/adicionar_memorando.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1046','pertenece_nucleo' => '0','nombre' => 'acciones_documento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Acciones del documento','enlace' => '#','cod_padre' => '1615','orden' => '1'),
        array('idmodulo' => '1047','pertenece_nucleo' => '0','nombre' => 'informacion_documento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Informaci&oacute;n del documento','enlace' => '#','cod_padre' => '1615','orden' => '2'),
        array('idmodulo' => '1048','pertenece_nucleo' => '0','nombre' => 'accesos_rapidos_documento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Accesos rapidos del documento','enlace' => '#','cod_padre' => '64','orden' => '1'),
        array('idmodulo' => '1049','pertenece_nucleo' => '0','nombre' => 'correo_saia','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Correo SAIA','enlace' => 'formatos/correo_saia/mostrar_correo_saia.php','cod_padre' => '236','orden' => '9'),
        array('idmodulo' => '1050','pertenece_nucleo' => '0','nombre' => 'ver_notas','tipo' => '2','imagen' => 'botones/intermedio/post_it.png','etiqueta' => 'Ver Notas','enlace' => '#','cod_padre' => '64','orden' => '3'),
        array('idmodulo' => '1057','pertenece_nucleo' => '1','nombre' => 'reportes_graficos','tipo' => '1','imagen' => 'fa fa-bar-chart-o','etiqueta' => 'Reportes','enlace' => '','cod_padre' => '1942','orden' => '5'),
        array('idmodulo' => '1060','pertenece_nucleo' => '0','nombre' => 'anulaciones','tipo' => '2','imagen' => 'fa fa-ban','etiqueta' => 'Anulaci&oacute;n de Registros','enlace' => 'pantallas/buscador_principal.php?idbusqueda=26','cod_padre' => '1946','orden' => '2'),
        array('idmodulo' => '1073','pertenece_nucleo' => '0','nombre' => 'despachados','tipo' => '2','imagen' => 'botones/principal/en_proceso.png','etiqueta' => 'Despachados','enlace' => 'pantallas/buscador_principal.php?idbusqueda=34','cod_padre' => '2007','orden' => '6'),
        array('idmodulo' => '1188','pertenece_nucleo' => '1','nombre' => 'logo_saia','tipo' => '2','imagen' => 'fa fa-cube','etiqueta' => 'Logo de inicio','enlace' => 'pantallas/logo/adicionar_logo.php','cod_padre' => '1949','orden' => '2'),
        array('idmodulo' => '1205','pertenece_nucleo' => '0','nombre' => 'crear_formato_saia','tipo' => '2','imagen' => 'botones/principal/admin_formatos.png','etiqueta' => 'Admin. Formatos','enlace' => 'pantallas/buscador_principal.php?idbusqueda=44&cmd=resetall','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '1208','pertenece_nucleo' => '0','nombre' => 'adicionar_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Adicionar expediente','enlace' => '#','cod_padre' => '45','orden' => '1'),
        array('idmodulo' => '1209','pertenece_nucleo' => '0','nombre' => 'distribucion_fisica','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Distribuci&oacute;n F&iacute;&shy;sica','enlace' => 'formatos/distribucion_fisica/mostrar_distribucion_fisica.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1210','pertenece_nucleo' => '0','nombre' => 'crear_distribucion_fisica','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Distribuci&oacute;n F&iacute;&shy;sica','enlace' => 'formatos/distribucion_fisica/adicionar_distribucion_fisica.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1211','pertenece_nucleo' => '0','nombre' => 'reporte_distribuciones_fisicas','tipo' => '2','imagen' => 'botones/principal/reportes.png','etiqueta' => 'Planilla de Mensajer&iacute;a','enlace' => 'pantallas/buscador_principal.php?idbusqueda=45','cod_padre' => '1057','orden' => '5'),
        array('idmodulo' => '1213','pertenece_nucleo' => '0','nombre' => 'documentos_serie','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Busqueda avanzada documentos por serie','enlace' => '#','cod_padre' => '865','orden' => '1'),
        array('idmodulo' => '1215','pertenece_nucleo' => '0','nombre' => 'editar','tipo' => '2','imagen' => 'botones/intermedio/editar_documento.png','etiqueta' => 'Editar informaci&oacute;n del documento.','enlace' => 'documentoedit.php?key=@key@','cod_padre' => '64','orden' => '60'),
        array('idmodulo' => '1232','pertenece_nucleo' => '0','nombre' => 'acercar_pagina','tipo' => '2','imagen' => 'icon-zoom-in','etiqueta' => 'Acercar pagina','enlace' => '#','cod_padre' => '28','orden' => '4'),
        array('idmodulo' => '1233','pertenece_nucleo' => '0','nombre' => 'alejar_pagina','tipo' => '2','imagen' => 'icon-zoom-out','etiqueta' => 'Alejar pagina','enlace' => '#','cod_padre' => '28','orden' => '3'),
        array('idmodulo' => '1234','pertenece_nucleo' => '0','nombre' => 'rotar_pagina','tipo' => '2','imagen' => '','etiqueta' => 'Rotar Pagina','enlace' => '#','cod_padre' => '28','orden' => '5'),
        array('idmodulo' => '1235','pertenece_nucleo' => '0','nombre' => 'adjuntos_documento','tipo' => '2','imagen' => 'icon-adjuntos_documento','etiqueta' => 'Adjuntos del documento','enlace' => 'pantallas/buscador_principal.php?idbusqueda=7','cod_padre' => '231','orden' => '1'),
        array('idmodulo' => '1236','pertenece_nucleo' => '0','nombre' => 'informacion_anexos','tipo' => '2','imagen' => 'icon-info-sign','etiqueta' => 'informaci&oacute;n documento anexo','enlace' => '#','cod_padre' => '1235','orden' => '1'),
        array('idmodulo' => '1237','pertenece_nucleo' => '0','nombre' => 'descargar_anexo','tipo' => '2','imagen' => 'icon-download','etiqueta' => 'Descargar anexo','enlace' => '#','cod_padre' => '1235','orden' => '2'),
        array('idmodulo' => '1238','pertenece_nucleo' => '0','nombre' => 'permisos_anexo','tipo' => '2','imagen' => 'icon-lock','etiqueta' => 'Permisos anexo','enlace' => '#','cod_padre' => '1235','orden' => '3'),
        array('idmodulo' => '1239','pertenece_nucleo' => '0','nombre' => 'eliminar_anexo','tipo' => '2','imagen' => 'icon-minus-sign','etiqueta' => 'Eliminar anexo','enlace' => '#','cod_padre' => '1235','orden' => '4'),
        array('idmodulo' => '1240','pertenece_nucleo' => '0','nombre' => 'menu_adjuntos','tipo' => '2','imagen' => 'menu_adjuntos','etiqueta' => 'Men&uacute; adjuntos','enlace' => '#','cod_padre' => '1235','orden' => '1'),
        array('idmodulo' => '1290','pertenece_nucleo' => '0','nombre' => 'vincular_doc_expedie','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Vincular Documentos a un Expediente','enlace' => 'formatos/vincular_doc_expedie/mostrar_vincular_doc_expedie.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1291','pertenece_nucleo' => '0','nombre' => 'crear_vincular_doc_expedie','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Vincular Documentos a un Expediente','enlace' => 'formatos/vincular_doc_expedie/adicionar_vincular_doc_expedie.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1292','pertenece_nucleo' => '0','nombre' => 'ver_pag_documento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Ver paginas del documento','enlace' => '#','cod_padre' => '64','orden' => '1'),
        array('idmodulo' => '1293','pertenece_nucleo' => '0','nombre' => 'arbol_documento','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Arbol de proceso','enlace' => '.','cod_padre' => '64','orden' => '1'),
        array('idmodulo' => '1320','pertenece_nucleo' => '0','nombre' => 'reporte_reservar_documentos','tipo' => '2','imagen' => 'fa fa-shopping-cart','etiqueta' => 'Pr&eacute;stamo de Archivo','enlace' => 'pantallas/buscador_principal.php?idbusqueda=54','cod_padre' => '2008','orden' => '20'),
        array('idmodulo' => '1386','pertenece_nucleo' => '0','nombre' => 'acciones_menu_mostrar','tipo' => '2','imagen' => 'botones/configuracion/default.gif','etiqueta' => 'Home','enlace' => 'ordenar.php?key=@key@&accion=mostrar&mostrar_formato=1','cod_padre' => '64','orden' => '0'),
        array('idmodulo' => '1387','pertenece_nucleo' => '0','nombre' => 'eliminar_documento_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Eliminar un documento de un expediente','enlace' => '#','cod_padre' => '45','orden' => '2'),
        array('idmodulo' => '1388','pertenece_nucleo' => '0','nombre' => 'ver_versiones','tipo' => '2','imagen' => 'icon-versiones_documento','etiqueta' => 'Versiones del documento','enlace' => 'pantallas/buscador_principal.php?idbusqueda=59','cod_padre' => '64','orden' => '20'),
        array('idmodulo' => '1395','pertenece_nucleo' => '0','nombre' => 'expediente_admin','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Expedientes admin','enlace' => '#','cod_padre' => '45','orden' => '1'),
        array('idmodulo' => '1402','pertenece_nucleo' => '0','nombre' => 'noticia_index','tipo' => '2','imagen' => 'botones/principal/noticias_index.png','etiqueta' => 'Noticias','enlace' => 'noticia_index/noticia_detalles.php','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '1429','pertenece_nucleo' => '0','nombre' => 'transferencia_doc','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Transferencia documental','enlace' => 'formatos/transferencia_doc/mostrar_transferencia_doc.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1430','pertenece_nucleo' => '0','nombre' => 'crear_transferencia_doc','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Transferencia documental','enlace' => 'formatos/transferencia_doc/adicionar_transferencia_doc.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1431','pertenece_nucleo' => '0','nombre' => 'eliminar_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Eliminar expediente','enlace' => '#','cod_padre' => '45','orden' => '3'),
        array('idmodulo' => '1432','pertenece_nucleo' => '0','nombre' => 'asignar_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Asginar expediente','enlace' => '#','cod_padre' => '45','orden' => '4'),
        array('idmodulo' => '1441','pertenece_nucleo' => '0','nombre' => 'crear_correo_saia','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Correo SAIA','enlace' => 'formatos/correo_saia/adicionar_correo_saia.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1443','pertenece_nucleo' => '0','nombre' => 'Correo','tipo' => '2','imagen' => 'fa fa-envelope','etiqueta' => 'Email','enlace' => 'index_correo.php','cod_padre' => '4','orden' => '5'),
        array('idmodulo' => '1450','pertenece_nucleo' => '0','nombre' => 'cancelar_paso_flujo','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Cancelar paso flujo','enlace' => '.','cod_padre' => '1698','orden' => '1'),
        array('idmodulo' => '1451','pertenece_nucleo' => '0','nombre' => 'despacho_fisico','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Despacho fisico','enlace' => 'formatos/despacho_fisico/mostrar_despacho_fisico.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1452','pertenece_nucleo' => '0','nombre' => 'crear_despacho_fisico','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Despacho fisico','enlace' => 'formatos/despacho_fisico/adicionar_despacho_fisico.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1453','pertenece_nucleo' => '0','nombre' => 'despacho_ingresados','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Entrega interna','enlace' => 'formatos/despacho_ingresados/mostrar_despacho_ingresados.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1454','pertenece_nucleo' => '0','nombre' => 'crear_despacho_ingresados','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Entrega interna','enlace' => 'formatos/despacho_ingresados/adicionar_despacho_ingresados.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1572','pertenece_nucleo' => '0','nombre' => 'oficio_word','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Documentos en formato (WORD)','enlace' => 'formatos/oficio_word/mostrar_oficio_word.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1573','pertenece_nucleo' => '0','nombre' => 'crear_oficio_word','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Documentos en formato (WORD)','enlace' => 'formatos/oficio_word/adicionar_oficio_word.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1590','pertenece_nucleo' => '0','nombre' => 'destino_radicacion','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'destino_radicacion','enlace' => 'formatos/destino_radicacion/mostrar_destino_radicacion.php','cod_padre' => '1008','orden' => '1'),
        array('idmodulo' => '1591','pertenece_nucleo' => '0','nombre' => 'crear_destino_radicacion','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear destino_radicacion','enlace' => 'formatos/destino_radicacion/adicionar_destino_radicacion.php','cod_padre' => '1007','orden' => '1'),
        array('idmodulo' => '1596','pertenece_nucleo' => '0','nombre' => 'ruta_distribucion','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Rutas de Distribuci&oacute;n','enlace' => 'formatos/ruta_distribucion/mostrar_ruta_distribucion.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1597','pertenece_nucleo' => '0','nombre' => 'crear_ruta_distribucion','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Rutas de Distribuci&oacute;n','enlace' => 'formatos/ruta_distribucion/adicionar_ruta_distribucion.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1598','pertenece_nucleo' => '0','nombre' => 'dependencias_ruta','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Dependencias de la Ruta','enlace' => 'formatos/dependencias_ruta/mostrar_dependencias_ruta.php','cod_padre' => '1596','orden' => '1'),
        array('idmodulo' => '1599','pertenece_nucleo' => '0','nombre' => 'crear_dependencias_ruta','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Dependencias de la Ruta','enlace' => 'formatos/dependencias_ruta/adicionar_dependencias_ruta.php','cod_padre' => '1597','orden' => '1'),
        array('idmodulo' => '1600','pertenece_nucleo' => '0','nombre' => 'funcionarios_ruta','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Funcionarios de la ruta','enlace' => 'formatos/funcionarios_ruta/mostrar_funcionarios_ruta.php','cod_padre' => '1596','orden' => '1'),
        array('idmodulo' => '1601','pertenece_nucleo' => '0','nombre' => 'crear_funcionarios_ruta','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Funcionarios de la ruta','enlace' => 'formatos/funcionarios_ruta/adicionar_funcionarios_ruta.php','cod_padre' => '1597','orden' => '1'),
        array('idmodulo' => '1607','pertenece_nucleo' => '0','nombre' => 'item_despacho_ingres','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Item despacho ingresados','enlace' => 'formatos/item_despacho_ingres/mostrar_item_despacho_ingres.php','cod_padre' => '1453','orden' => '1'),
        array('idmodulo' => '1608','pertenece_nucleo' => '0','nombre' => 'crear_item_despacho_ingres','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Item despacho ingresados','enlace' => 'formatos/item_despacho_ingres/adicionar_item_despacho_ingres.php','cod_padre' => '1454','orden' => '1'),
        array('idmodulo' => '1609','pertenece_nucleo' => '0','nombre' => 'reporte_trd_gd','tipo' => '2','imagen' => 'botones/principal/reportes.png','etiqueta' => 'TRD GD','enlace' => 'pantallas/buscador_principal.php?idbusqueda=98','cod_padre' => '1057','orden' => '6'),
        array('idmodulo' => '1610','pertenece_nucleo' => '0','nombre' => 'permiso_abrir_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso Abrir Expediente','enlace' => '#','cod_padre' => '45','orden' => '0'),
        array('idmodulo' => '1611','pertenece_nucleo' => '0','nombre' => 'reporte_acceso_usuarios','tipo' => '2','imagen' => 'botones/principal/reportes.png','etiqueta' => 'Reporte usuarios','enlace' => 'pantallas/buscador_principal.php?idbusqueda=100','cod_padre' => '1057','orden' => '10'),
        array('idmodulo' => '1615','pertenece_nucleo' => '0','nombre' => 'opcion_otros','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Otros','enlace' => '#','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '1620','pertenece_nucleo' => '0','nombre' => 'novedad_despacho','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Novedad Despacho Mensajeros','enlace' => 'formatos/novedad_despacho/mostrar_novedad_despacho.php','cod_padre' => '1453','orden' => '1'),
        array('idmodulo' => '1621','pertenece_nucleo' => '0','nombre' => 'crear_novedad_despacho','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Novedad Despacho Mensajeros','enlace' => 'formatos/novedad_despacho/adicionar_novedad_despacho.php','cod_padre' => '1454','orden' => '1'),
        array('idmodulo' => '1626','pertenece_nucleo' => '0','nombre' => 'entrega_prestamo','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Entrega de Pr&eacute;stamo','enlace' => 'formatos/entrega_prestamo/mostrar_entrega_prestamo.php','cod_padre' => '1624','orden' => '1'),
        array('idmodulo' => '1627','pertenece_nucleo' => '0','nombre' => 'crear_entrega_prestamo','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Entrega de Pr&eacute;stamo','enlace' => 'formatos/entrega_prestamo/adicionar_entrega_prestamo.php','cod_padre' => '1625','orden' => '1'),
        array('idmodulo' => '1639','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_radicacion_correspondencia_dependencias','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Reporte Radicaci&oacute;n de Correspondencia por Dependencias','enlace' => 'pantallas/buscador_principal.php?idbusqueda=105&default_componente=indicadores_reporte_radicacion_correspondencia_dependencias','cod_padre' => '1057','orden' => '11'),
        array('idmodulo' => '1640','pertenece_nucleo' => '0','nombre' => 'modulo_admin_categoria_formato','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Categoria Formato','enlace' => 'pantallas/buscador_principal.php?idbusqueda=106','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '1641','pertenece_nucleo' => '1','nombre' => 'temas_saia','tipo' => '2','imagen' => 'fa fa-paint-brush','etiqueta' => 'Temas Saia','enlace' => 'pantallas/buscador_principal.php?idbusqueda=4','cod_padre' => '1949','orden' => '1'),
        array('idmodulo' => '1642','pertenece_nucleo' => '1','nombre' => 'permiso_radicacion_externa','tipo' => '2','imagen' => 'botones/configuracion/default.gif','etiqueta' => 'Radicaci&oacute;n Externa','enlace' => '#','cod_padre' => '6','orden' => '0'),
        array('idmodulo' => '1644','pertenece_nucleo' => '1','nombre' => 'permiso_expedientes_gestion','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso Gesti&oacute;n','enlace' => '#','cod_padre' => '45','orden' => '0'),
        array('idmodulo' => '1645','pertenece_nucleo' => '1','nombre' => 'permiso_expedientes_central','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso Central','enlace' => '#','cod_padre' => '45','orden' => '0'),
        array('idmodulo' => '1646','pertenece_nucleo' => '1','nombre' => 'permiso_expedientes_historico','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso Hist&oacute;rico','enlace' => '#','cod_padre' => '45','orden' => '0'),
        array('idmodulo' => '1647','pertenece_nucleo' => '0','nombre' => 'permiso_expedientes_cajas','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Permiso Cajas','enlace' => '#','cod_padre' => '45','orden' => '0'),
        array('idmodulo' => '1654','pertenece_nucleo' => '0','nombre' => 'reporte_distribucion_documentos','tipo' => '2','imagen' => 'fa fa-truck','etiqueta' => 'Distribuci&oacute;n','enlace' => 'pantallas/buscador_principal.php?idbusqueda=109','cod_padre' => '2007','orden' => '8'),
        array('idmodulo' => '1655','pertenece_nucleo' => '0','nombre' => 'permiso_reporte_distribucion_general_sinrecogida','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Visualizar 1. Entregas Interna a ventanilla','enlace' => '#','cod_padre' => '1654','orden' => '1'),
        array('idmodulo' => '1660','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expediente_grid','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Reporte Expedientes Grid','enlace' => 'pantallas/buscador_principal.php?idbusqueda=115','cod_padre' => '1057','orden' => '10'),
        array('idmodulo' => '1662','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expedientes_gestion','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Gestion','enlace' => 'pantallas/busquedas/consulta_busqueda_expediente.php?variable_busqueda=1&idbusqueda_componente=110','cod_padre' => '45','orden' => '1'),
        array('idmodulo' => '1663','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expedientes_central','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Central','enlace' => 'pantallas/busquedas/consulta_busqueda_expediente.php?variable_busqueda=2&idbusqueda_componente=10','cod_padre' => '45','orden' => '2'),
        array('idmodulo' => '1664','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expedientes_historico','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Historico','enlace' => 'pantallas/busquedas/consulta_busqueda_expediente.php?variable_busqueda=3&idbusqueda_componente=9','cod_padre' => '45','orden' => '3'),
        array('idmodulo' => '1665','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expedientes_cajas','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Cajas','enlace' => 'pantallas/busquedas/consulta_busqueda_caja.php?idbusqueda_componente=323','cod_padre' => '45','orden' => '4'),
        array('idmodulo' => '1666','pertenece_nucleo' => '0','nombre' => 'modulo_reporte_expedientes_prestamo','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Prestamo','enlace' => 'pantallas/busquedas/consulta_busqueda_reporte.php?idbusqueda_componente=203','cod_padre' => '45','orden' => '5'),
        array('idmodulo' => '1669','pertenece_nucleo' => '0','nombre' => 'permiso_admin_archivo','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Administraci&oacute;n de Archivo','enlace' => '#','cod_padre' => '45','orden' => '2'),
        array('idmodulo' => '1670','pertenece_nucleo' => '0','nombre' => 'reporte_usuarios_concurrentes','tipo' => '2','imagen' => 'botones/principal/reportes.png','etiqueta' => 'Usuarios Concurrentes','enlace' => 'pantallas/buscador_principal.php?idbusqueda=120','cod_padre' => '1057','orden' => '4'),
        array('idmodulo' => '1695','pertenece_nucleo' => '1','nombre' => 'centro_notificaciones','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Centro de Notificaciones','enlace' => 'auxiliar2.php?modulo=1695','cod_padre' => '9999','orden' => '20'),
        array('idmodulo' => '1696','pertenece_nucleo' => '1','nombre' => 'mis_tareas','tipo' => '1','imagen' => 'fa fa-tasks','etiqueta' => 'Mis Tareas','enlace' => 'views/calendario/tareas.php','cod_padre' => '1942','orden' => '3'),
        array('idmodulo' => '1698','pertenece_nucleo' => '1','nombre' => 'otros_permisos','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'OTROS PERMISOS','enlace' => 'auxiliar2.php?modulo=1698','cod_padre' => '9999','orden' => '9'),
        array('idmodulo' => '1711','pertenece_nucleo' => '0','nombre' => 'compartir_expediente','tipo' => '2','imagen' => 'botones/principal/defaut.png','etiqueta' => 'Compartir expediente','enlace' => '#','cod_padre' => '45','orden' => '1'),
        array('idmodulo' => '1717','pertenece_nucleo' => '0','nombre' => 'crear_otrosi_contrato','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Otrosi','enlace' => 'formatos/otrosi_contrato/adicionar_otrosi_contrato.php','cod_padre' => '1713','orden' => '1'),
        array('idmodulo' => '1809','pertenece_nucleo' => '0','nombre' => 'permiso_clasificacion_factura','tipo' => '','imagen' => '#','etiqueta' => 'Permiso boton clasificacion de factura','enlace' => '#','cod_padre' => '1800','orden' => '127'),
        array('idmodulo' => '1883','pertenece_nucleo' => '0','nombre' => 'Encabezado Despacho Ingreso','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Entrega interna','enlace' => 'formatos/Encabezado Despacho Ingreso/mostrar_despacho_ingresados.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1884','pertenece_nucleo' => '0','nombre' => 'crear_Encabezado Despacho Ingreso','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Entrega interna','enlace' => 'formatos/Encabezado Despacho Ingreso/adicionar_despacho_ingresados.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1906','pertenece_nucleo' => '1','nombre' => 'manuales','tipo' => '2','imagen' => 'fa fa-support','etiqueta' => 'Ayuda','enlace' => 'pantallas/buscador_principal.php?idbusqueda=128','cod_padre' => '9999','orden' => '9'),
        array('idmodulo' => '1917','pertenece_nucleo' => '1','nombre' => 'pantallas','tipo' => '2','imagen' => 'botones/principal/admin_formatos.png','etiqueta' => 'Admin. Pantallas','enlace' => 'pantallas/buscador_principal.php?idbusqueda=129&cmd=resetall','cod_padre' => '9999','orden' => '0'),
        array('idmodulo' => '1927','pertenece_nucleo' => '0','nombre' => 'solicitud_prestamo','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Solicitud de Prestamo','enlace' => 'formatos/solicitud_prestamo/mostrar_solicitud_prestamo.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1928','pertenece_nucleo' => '0','nombre' => 'crear_solicitud_prestamo','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Solicitud de Prestamo','enlace' => 'formatos/solicitud_prestamo/adicionar_solicitud_prestamo.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1930','pertenece_nucleo' => '1','nombre' => 'dashboard','tipo' => '1','imagen' => 'fa fa-home','etiqueta' => 'Dashboard','enlace' => 'views/dashboard/index_dashboard.php?idbusqueda_componente=7','cod_padre' => '-1','orden' => '0'),
        array('idmodulo' => '1932','pertenece_nucleo' => '0','nombre' => 'borradores','tipo' => '2','imagen' => 'fa fa-eraser','etiqueta' => 'Borradores','enlace' => 'views/dashboard/kaiten_dashboard.php?panels=[{"kConnector": "html.page","url": "pantallas/busquedas/componentes_busqueda.php?idbusqueda=25"}]','cod_padre' => '4','orden' => '3'),
        array('idmodulo' => '1933','pertenece_nucleo' => '0','nombre' => 'un_formato','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Prueba Nuevo Formato','enlace' => 'formatos/un_formato/mostrar_un_formato.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1934','pertenece_nucleo' => '0','nombre' => 'crear_un_formato','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Prueba Nuevo Formato','enlace' => 'formatos/un_formato/adicionar_un_formato.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1935','pertenece_nucleo' => '0','nombre' => 'prueba_formato_saia','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Prueba del formato','enlace' => 'formatos/mostrar_prueba_formato_saia.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1936','pertenece_nucleo' => '0','nombre' => 'crear_prueba_formato_saia','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Prueba del formato','enlace' => 'formatos/adicionar_prueba_formato_saia.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1937','pertenece_nucleo' => '0','nombre' => 'prueba_formato_saia2','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Prueba 2','enlace' => 'formatos/mostrar_prueba_formato_saia2.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1938','pertenece_nucleo' => '0','nombre' => 'crear_prueba_formato_saia2','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Prueba 2','enlace' => 'formatos/adicionar_prueba_formato_saia2.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1939','pertenece_nucleo' => '0','nombre' => 'admin_formatos','tipo' => '2','imagen' => 'fa fa-file-code-o','etiqueta' => 'Formatos','enlace' => 'pantallas/buscador_principal.php?idbusqueda=131','cod_padre' => '2','orden' => '3'),
        array('idmodulo' => '1940','pertenece_nucleo' => '0','nombre' => 'hijo_prueba2','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Hijo prueba2','enlace' => 'formatos/mostrar_hijo_prueba2.php','cod_padre' => '1937','orden' => '1'),
        array('idmodulo' => '1941','pertenece_nucleo' => '0','nombre' => 'crear_hijo_prueba2','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Hijo prueba2','enlace' => 'formatos/adicionar_hijo_prueba2.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1942','pertenece_nucleo' => '1','nombre' => 'agrupador_dashboard','tipo' => 'grouper','imagen' => 'fa fa-dashboard','etiqueta' => 'Dashboard','enlace' => '','cod_padre' => '0','orden' => '1'),
        array('idmodulo' => '1943','pertenece_nucleo' => '1','nombre' => 'etiquetas','tipo' => '1','imagen' => 'fa fa-tag','etiqueta' => 'Etiquetados','enlace' => 'app/modulo/etiquetas.php','cod_padre' => '1942','orden' => '2'),
        array('idmodulo' => '1944','pertenece_nucleo' => '1','nombre' => 'agrupador_administracion','tipo' => 'grouper','imagen' => 'fa fa-building','etiqueta' => 'Administraci&oacute;n','enlace' => '','cod_padre' => '0','orden' => '3'),
        array('idmodulo' => '1946','pertenece_nucleo' => '1','nombre' => 'gestion_administracion','tipo' => '1','imagen' => 'fa fa-cutlery','etiqueta' => 'Gesti&oacute;n','enlace' => '','cod_padre' => '1944','orden' => '2'),
        array('idmodulo' => '1947','pertenece_nucleo' => '1','nombre' => 'comunicacion','tipo' => '1','imagen' => 'fa fa-bullhorn','etiqueta' => 'Comunicaci&oacute;n','enlace' => '','cod_padre' => '1944','orden' => '3'),
        array('idmodulo' => '1948','pertenece_nucleo' => '1','nombre' => 'agrupador_configuracion','tipo' => 'grouper','imagen' => 'fa fa-cogs','etiqueta' => 'Configuraci&oacute;n','enlace' => '','cod_padre' => '0','orden' => '4'),
        array('idmodulo' => '1949','pertenece_nucleo' => '1','nombre' => 'imagen_sistema','tipo' => '1','imagen' => 'fa fa-image','etiqueta' => 'Imagen del sistema','enlace' => '','cod_padre' => '1948','orden' => '2'),
        array('idmodulo' => '1950','pertenece_nucleo' => '1','nombre' => 'reportes_configuracion','tipo' => '1','imagen' => 'fa fa-bar-chart-o','etiqueta' => 'Reportes','enlace' => '','cod_padre' => '1948','orden' => '3'),
        array('idmodulo' => '1951','pertenece_nucleo' => '1','nombre' => 'novedades_comunicacion','tipo' => '2','imagen' => 'fa fa-newspaper-o','etiqueta' => 'Novedades','enlace' => '','cod_padre' => '1947','orden' => '2'),
        array('idmodulo' => '1952','pertenece_nucleo' => '1','nombre' => 'log_transacciones','tipo' => '2','imagen' => 'fa fa-repeat','etiqueta' => 'Log de transacciones','enlace' => '','cod_padre' => '1950','orden' => '1'),
        array('idmodulo' => '1953','pertenece_nucleo' => '0','nombre' => 'estado_usuarios','tipo' => '2','imagen' => 'fa fa-eye','etiqueta' => 'Estado de usuarios','enlace' => '','cod_padre' => '1950','orden' => '2'),
        array('idmodulo' => '1954','pertenece_nucleo' => '0','nombre' => 'asdas','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'asdasd','enlace' => 'formatos/asdas/mostrar_asdas.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1955','pertenece_nucleo' => '0','nombre' => 'crear_asdas','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear asdasd','enlace' => 'formatos/asdas/adicionar_asdas.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1956','pertenece_nucleo' => '0','nombre' => 'a_fancy','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Formato con &aacute;rbol FT','enlace' => 'formatos/a_fancy/mostrar_a_fancy.php','cod_padre' => '236','orden' => '1'),
        array('idmodulo' => '1957','pertenece_nucleo' => '0','nombre' => 'crear_a_fancy','tipo' => '2','imagen' => 'botones/formatos/modulo.gif','etiqueta' => 'Crear Formato con &aacute;rbol FT','enlace' => 'formatos/a_fancy/adicionar_a_fancy.php','cod_padre' => '1006','orden' => '1'),
        array('idmodulo' => '1980','pertenece_nucleo' => '1','nombre' => 'menu_documento','tipo' => '3','imagen' => NULL,'etiqueta' => 'Acciones Documento','enlace' => '','cod_padre' => NULL,'orden' => '1'),
        array('idmodulo' => '1981','pertenece_nucleo' => '1','nombre' => 'responder','tipo' => '3','imagen' => 'fa fa-mail-reply','etiqueta' => 'Responder','enlace' => '','cod_padre' => '1980','orden' => '1'),
        array('idmodulo' => '1982','pertenece_nucleo' => '1','nombre' => 'responder_todos','tipo' => '3','imagen' => 'fa fa-mail-reply-all','etiqueta' => 'Respoder a todos','enlace' => '','cod_padre' => '1980','orden' => '2'),
        array('idmodulo' => '1983','pertenece_nucleo' => '1','nombre' => 'reenviar','tipo' => '3','imagen' => 'fa fa-share','etiqueta' => 'Reenviar','enlace' => '','cod_padre' => '1980','orden' => '3'),
        array('idmodulo' => '1986','pertenece_nucleo' => '1','nombre' => 'mover_expediente','tipo' => '3','imagen' => 'fa fa-folder','etiqueta' => 'Mover a expediente','enlace' => '','cod_padre' => '1980','orden' => '4'),
        array('idmodulo' => '1987','pertenece_nucleo' => '1','nombre' => 'asignar_serie','tipo' => '3','imagen' => 'fa fa-certificate','etiqueta' => 'Asignar tipo documental','enlace' => '','cod_padre' => '1980','orden' => '5'),
        array('idmodulo' => '1989','pertenece_nucleo' => '1','nombre' => 'discutir_documento','tipo' => '3','imagen' => 'fa-comments-o','etiqueta' => 'Discutir Documento','enlace' => '','cod_padre' => '1980','orden' => '7'),
        array('idmodulo' => '1990','pertenece_nucleo' => '1','nombre' => 'asignar_responsable','tipo' => '3','imagen' => 'fa fa-user','etiqueta' => 'Asignar responsable','enlace' => '','cod_padre' => '1980','orden' => '8'),
        array('idmodulo' => '1991','pertenece_nucleo' => '1','nombre' => 'solicitar_aprobacion','tipo' => '3','imagen' => 'fa fa-thumbs-o-up','etiqueta' => 'Solicitar aprobaci&oacute;n','enlace' => '','cod_padre' => '1980','orden' => '9'),
        array('idmodulo' => '1993','pertenece_nucleo' => '1','nombre' => 'etiquetar','tipo' => '3','imagen' => 'fa fa-tag','etiqueta' => 'Etiquetar','enlace' => 'views/documento/etiquetar.php','cod_padre' => '1980','orden' => '10'),
        array('idmodulo' => '1994','pertenece_nucleo' => '1','nombre' => 'imprimir','tipo' => '3','imagen' => 'fa fa-print','etiqueta' => 'Imprimir','enlace' => '','cod_padre' => '1980','orden' => '11'),
        array('idmodulo' => '1995','pertenece_nucleo' => '1','nombre' => 'anexos','tipo' => '3','imagen' => 'fa fa-paperclip','etiqueta' => 'Anexos','enlace' => '','cod_padre' => '1980','orden' => '12'),
        array('idmodulo' => '1996','pertenece_nucleo' => '1','nombre' => 'vincular_otro_documento','tipo' => '3','imagen' => 'fa fa-chain','etiqueta' => 'Vincular a otro documento','enlace' => '','cod_padre' => '1980','orden' => '13'),
        array('idmodulo' => '1997','pertenece_nucleo' => '1','nombre' => 'imprimir_radicado','tipo' => '3','imagen' => 'fa fa-qrcode','etiqueta' => 'Imprimir radicado','enlace' => '','cod_padre' => '1980','orden' => '14'),
        array('idmodulo' => '1998','pertenece_nucleo' => '1','nombre' => 'actualizar_pdf','tipo' => '3','imagen' => 'fa fa-file-pdf-o','etiqueta' => 'Actualizar PDF','enlace' => '','cod_padre' => '1980','orden' => '15'),
        array('idmodulo' => '1999','pertenece_nucleo' => '1','nombre' => 'distribuir_fisicamente','tipo' => '3','imagen' => 'fa fa-truck','etiqueta' => 'Distribuir f&iacute;sicamente','enlace' => '','cod_padre' => '1980','orden' => '16'),
        array('idmodulo' => '2000','pertenece_nucleo' => '1','nombre' => 'anular_documento','tipo' => '3','imagen' => 'fa fa-fire','etiqueta' => 'Anular documento','enlace' => '','cod_padre' => '1980','orden' => '17'),
        array('idmodulo' => '2001','pertenece_nucleo' => '1','nombre' => 'crear_nueva_version','tipo' => '3','imagen' => 'fa fa-copy','etiqueta' => 'Crear nueva versi&oacute;n','enlace' => '','cod_padre' => '1980','orden' => '18'),
        array('idmodulo' => '2002','pertenece_nucleo' => '1','nombre' => 'seguridad','tipo' => '3','imagen' => 'fa fa-lock','etiqueta' => 'Seguridad','enlace' => '','cod_padre' => '1980','orden' => '19'),
        array('idmodulo' => '2004','pertenece_nucleo' => '1','nombre' => 'hijo_etiquetas','tipo' => '3','imagen' => '','etiqueta' => 'Hijo Etiquetados','enlace' => 'no borrar','cod_padre' => '1943','orden' => '1'),
        array('idmodulo' => '2006','pertenece_nucleo' => '1','nombre' => 'crear_tarea','tipo' => '3','imagen' => 'fa fa-calendar','etiqueta' => 'Crear tarea','enlace' => '','cod_padre' => '1980','orden' => '6'),
        array('idmodulo' => '2007','pertenece_nucleo' => '0','nombre' => 'agr_correspondencia','tipo' => '1','imagen' => 'fa fa-envelope-o','etiqueta' => 'Correspondencia','enlace' => '','cod_padre' => '1','orden' => '2'),
        array('idmodulo' => '2008','pertenece_nucleo' => '0','nombre' => 'agr_archivo_documental','tipo' => '1','imagen' => 'fa fa-archive','etiqueta' => 'Archivo Documental','enlace' => '','cod_padre' => '1','orden' => '3')
    );
    public function getDescription(): string {
        return 'Crear formato despacho_ingresados';
    }
    public function preUp(Schema $schema): void
    {
        date_default_timezone_set("America/Bogota");

        if ($this->connection->getDatabasePlatform()->getName() == "mysql") {
            $this->platform->registerDoctrineTypeMapping('enum', 'string');
        }
    }
    public function up(Schema $schema): void
    {
        $conn = $this->connection;

        $platform   = $conn->getDatabasePlatform();

        $conn->executeUpdate($platform->getTruncateTableSQL('modulo', true /* whether to cascade */));

        $conn->beginTransaction();

        foreach ($this->modulo as $value) {
            $this->guardar_campo($value);
        }
        $conn->commit();
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
    public function preDown(Schema $schema): void {
        date_default_timezone_set("America/Bogota");

        if ($this->connection->getDatabasePlatform()->getName() == "mysql") {
            $this->platform->registerDoctrineTypeMapping('enum', 'string');
        }
    }

    private function guardar_campo($datos) {
        if (empty($datos)) {
            return false;
        }

        $conn = $this->connection;
        $resp = $conn->insert('modulo', $datos);
        if (empty($resp)) {
            $conn->rollBack();
            print_r($conn->errorInfo());
            die("Fallo la creacion del modulo");
        }
        $idbusq = $conn->lastInsertId();

        return $idbusq;
    }
}
