<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190213192702 extends AbstractMigration {

    public function getDescription(): string {
        return 'Actualiacion reporte distribucion';
    }

    public function up(Schema $schema): void {

        $this->connection->update('busqueda_componente ', ['idbusqueda_componente' => '303', 'busqueda_idbusqueda' => '109', 'tipo' => '3', 'conector' => '2', 'url' => 'pantallas/busquedas/consulta_busqueda_tabla.php', 'etiqueta' => '1. Entregas Interna a ventanilla', 'nombre' => 'reporte_distribucion_general_sinrecogida', 'orden' => '1', 'info' => 'Radicado|{*ver_documento_distribucion@iddocumento,tipo_origen*}|center|210|-|No. Distribuci&oacute;n|{*numero_distribucion*}|center|100|-|Estado|{*ver_estado_distribucion@estado_distribucion*}|center|-|Diligencia|{*mostrar_diligencia_distribucion@tipo_origen,estado_recogida*}|center|80|-|Ruta|{*mostrar_nombre_ruta_distribucion@tipo_origen,estado_recogida,ruta_origen,ruta_destino,tipo_destino,iddistribucion*}|center|-|Planilla Asociada|{*mostrar_planilla_diligencia_distribucion@iddistribucion*}|center|-|Origen|{*mostrar_origen_distribucion@tipo_origen,origen*}|center|250|-|Destino|{*mostrar_destino_distribucion@tipo_destino,destino*}|center|250|-|Fecha de Radicaci&oacute;n|{*fecha*}|center|-|Asunto|{*descripcion*}|left', 'exportar' => NULL, 'exportar_encabezado' => NULL, 'encabezado_componente' => NULL, 'estado' => '1', 'ancho' => '600', 'cargar' => '1', 'campos_adicionales' => NULL, 'tablas_adicionales' => NULL, 'ordenado_por' => 'iddistribucion', 'direccion' => 'DESC', 'agrupado_por' => NULL, 'busqueda_avanzada' => 'distribucion/busqueda_distribucion.php?idbusqueda_componente=303', 'acciones_seleccionados' => 'opciones_acciones_distribucion', 'modulo_idmodulo' => '1655', 'menu_busqueda_superior' => NULL, 'enlace_adicionar' => NULL, 'encabezado_grillas' => NULL, 'llave' => 'a.iddistribucion'], ["idbusqueda_componente" => "303"]);
        $this->connection->update('busqueda_componente ', ['idbusqueda_componente' => '302', 'busqueda_idbusqueda' => '109', 'tipo' => '3', 'conector' => '2', 'url' => 'pantallas/busquedas/consulta_busqueda_tabla.php', 'etiqueta' => '4. Finalizado', 'nombre' => 'reporte_distribucion_general_finalizado', 'orden' => '4', 'info' => 'Radicado|{*ver_documento_distribucion@iddocumento,tipo_origen*}|center|210|-|No. Distribuci&oacute;n|{*numero_distribucion*}|center|100|-|Estado|{*ver_estado_distribucion@estado_distribucion*}|center|-|Planilla Asociada|{*mostrar_planilla_diligencia_distribucion@iddistribucion*}|center|-|Origen|{*mostrar_origen_distribucion@tipo_origen,origen*}|center|250|-|Destino|{*mostrar_destino_distribucion@tipo_destino,destino*}|center|250|-|Fecha de Radicaci&oacute;n|{*fecha*}|center|-|Asunto|{*descripcion*}|left', 'exportar' => NULL, 'exportar_encabezado' => NULL, 'encabezado_componente' => NULL, 'estado' => '1', 'ancho' => '600', 'cargar' => '1', 'campos_adicionales' => NULL, 'tablas_adicionales' => NULL, 'ordenado_por' => 'iddistribucion', 'direccion' => 'DESC', 'agrupado_por' => NULL, 'busqueda_avanzada' => 'distribucion/busqueda_distribucion.php?idbusqueda_componente=302', 'acciones_seleccionados' => '', 'modulo_idmodulo' => NULL, 'menu_busqueda_superior' => NULL, 'enlace_adicionar' => NULL, 'encabezado_grillas' => NULL, 'llave' => 'a.iddistribucion'], ["idbusqueda_componente" => "302"]);
        $this->connection->update('busqueda_componente ', ['idbusqueda_componente' => '301', 'busqueda_idbusqueda' => '109', 'tipo' => '3', 'conector' => '2', 'url' => 'pantallas/busquedas/consulta_busqueda_tabla.php', 'etiqueta' => '3. En distribuci&oacute;n', 'nombre' => 'reporte_distribucion_general_endistribucion', 'orden' => '3', 'info' => 'No. Registro|{*ver_documento_distribucion@iddocumento,tipo_origen*}|center|210|-|Fecha de registro|{*fecha*}|center|210|-|No. Distribuci&oacute;n|{*numero_distribucion*}|center|100|-|Estado|{*ver_estado_distribucion@estado_distribucion*}|center|-|Diligencia|{*mostrar_diligencia_distribucion@tipo_origen,estado_recogida*}|center|80|-|Ruta|{*mostrar_nombre_ruta_distribucion@tipo_origen,estado_recogida,ruta_origen,ruta_destino,tipo_destino,iddistribucion*}|center|-|Mensajero|{*select_mensajeros_ruta_distribucion@iddistribucion*}|center|-|Planilla Asociada|{*mostrar_planilla_diligencia_distribucion@iddistribucion*}|center|-|Origen|{*mostrar_origen_distribucion@tipo_origen,origen*}|center|250|-|Destino|{*mostrar_destino_distribucion@tipo_destino,destino*}|center|250|-|Fecha de Radicaci&oacute;n|{*fecha*}|center|-|Asunto|{*descripcion*}|left', 'exportar' => NULL, 'exportar_encabezado' => NULL, 'encabezado_componente' => NULL, 'estado' => '1', 'ancho' => '600', 'cargar' => '1', 'campos_adicionales' => NULL, 'tablas_adicionales' => NULL, 'ordenado_por' => 'iddistribucion', 'direccion' => 'DESC', 'agrupado_por' => NULL, 'busqueda_avanzada' => 'distribucion/busqueda_distribucion.php?idbusqueda_componente=301', 'acciones_seleccionados' => 'opciones_acciones_distribucion', 'modulo_idmodulo' => NULL, 'menu_busqueda_superior' => NULL, 'enlace_adicionar' => NULL, 'encabezado_grillas' => NULL, 'llave' => 'a.iddistribucion'], ["idbusqueda_componente" => "301"]);
        $this->connection->update('busqueda_componente ', ['idbusqueda_componente' => '300', 'busqueda_idbusqueda' => '109', 'tipo' => '3', 'conector' => '2', 'url' => 'pantallas/busquedas/consulta_busqueda_tabla.php', 'etiqueta' => '2. Por Distribuir', 'nombre' => 'reporte_distribucion_general_pordistribuir', 'orden' => '2', 'info' => 'No. Registro|{*ver_documento_distribucion@iddocumento,tipo_origen*}|center|210|-|Fecha de registro|{*fecha*}|center|210|-|No. Distribuci&oacute;n|{*numero_distribucion*}|center|100|-|Estado|{*ver_estado_distribucion@estado_distribucion*}|center|-|Diligencia|{*mostrar_diligencia_distribucion@tipo_origen,estado_recogida*}|center|80|-|Ruta|{*mostrar_nombre_ruta_distribucion@tipo_origen,estado_recogida,ruta_origen,ruta_destino,tipo_destino,iddistribucion*}|center|-|Mensajero|{*select_mensajeros_ruta_distribucion@iddistribucion*}|center|-|Planilla Asociada|{*mostrar_planilla_diligencia_distribucion@iddistribucion*}|center|-|Origen|{*mostrar_origen_distribucion@tipo_origen,origen*}|center|250|-|Destino|{*mostrar_destino_distribucion@tipo_destino,destino*}|center|250|-|Fecha de Radicaci&oacute;n|{*fecha*}|center|-|Asunto|{*descripcion*}|left', 'exportar' => NULL, 'exportar_encabezado' => NULL, 'encabezado_componente' => NULL, 'estado' => '1', 'ancho' => '600', 'cargar' => '1', 'campos_adicionales' => NULL, 'tablas_adicionales' => NULL, 'ordenado_por' => 'iddistribucion', 'direccion' => 'DESC', 'agrupado_por' => NULL, 'busqueda_avanzada' => 'distribucion/busqueda_distribucion.php?idbusqueda_componente=300', 'acciones_seleccionados' => 'opciones_acciones_distribucion', 'modulo_idmodulo' => NULL, 'menu_busqueda_superior' => NULL, 'enlace_adicionar' => NULL, 'encabezado_grillas' => NULL, 'llave' => 'a.iddistribucion'], ["idbusqueda_componente" => "300"]);
        
        
    }

    public function down(Schema $schema): void {
        // this down() migration is auto-generated, please modify it to your needs
    }

}
