<?php
$ruta=dirname(__FILE__);
include_once($ruta."/librerias.php");
include_once($ruta."/../../db.php");
if($_REQUEST["iddoc"]){
  $iddoc=$_REQUEST["iddoc"]; 
  $texto=barra_adicional_documento($iddoc);
  echo($texto);
}
?>