<html><title>.:ADICIONAR HIJO_PRUEBA:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">HIJO_PRUEBA</td></tr><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5144)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5143)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(415,5142);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5141)); ?>"><input type="hidden" name="idft_hijo_prueba" value="<?php echo(validar_valor_campo(5140)); ?>"><tr id="tr_mi_campo">
                     <td class="encabezado" width="20%" title="">MI_CAMPO*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='1'  type="text" size="100" id="mi_campo" name="mi_campo"  value="<?php echo(validar_valor_campo(5139)); ?>"></td>
                    </tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5138)); ?>"><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5137)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_prueba_confir_apru"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_prueba_confir_apru"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_prueba_confir_apru);} ?><tr><td colspan='2'><?php submit_formato(415);?></td></tr></table></form></body></html>