<html><title>.:ADICIONAR MANTENIMIENTO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">MANTENIMIENTO</td></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_activo_fijo"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_activo_fijo"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_activo_fijo);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(2580)); ?>"><tr>
                    <td class="encabezado" width="20%" title="">FECHA DE LA SOLICITUD*</td><td colspan="2" bgcolor="#F5F5F5"><font size="1,5" face="Verdana, Arial, Helvetica, sans-serif"><span ><input  tabindex='1'  type="text" readonly="true" name="fecha_solicitud"  class="required dateISO"  id="fecha_solicitud" value="<?php echo(date("0000-00-00 00:00")); ?>"><?php selector_fecha("fecha_solicitud","formulario_formatos","Y-m-d H:i",date("m"),date("Y"),"default.css","../../","AD:VALOR"); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">DESCRIPCI&Oacute;N*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="descripcion" id="descripcion" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(2582)); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">CATEGOR&Iacute;A*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(232,2606,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="">PRIORIDAD*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(232,2583,$_REQUEST['iddoc']);?></td></tr><tr>
                     <td class="encabezado" width="20%" title="">SOLICITANTE*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='3'  type="text" size="100" id="solicitante" name="solicitante"  value="<?php echo(validar_valor_campo(2584)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">RESPONSABLE*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='4'  type="text" size="100" id="responsable" name="responsable"  value="<?php echo(validar_valor_campo(2585)); ?>"></td>
                    </tr><input type="hidden" name="idft_solicid_matenimiento" value="<?php echo(validar_valor_campo(2586)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(2587)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(232,2588);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(2589)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(2590)); ?>"><input type="hidden" name="campo_descripcion" value="2582"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(232);?></td></tr></table></form></body></html>