<html><title>.:ADICIONAR TECNICO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">TECNICO</td></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_acta_evaluacion"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_acta_evaluacion"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_acta_evaluacion);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(1029)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">ASPECTOS TECNICOS*</td>
                     <td class="celda_transparente"><textarea  tabindex='1'  name="aspectos_tecnicos" id="aspectos_tecnicos" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(1052)); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">CONCLUSION TECNICA*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="conclusion_tecnica" id="conclusion_tecnica" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(1053)); ?></textarea></td>
                    </tr><input type="hidden" name="idft_tecnico" value="<?php echo(validar_valor_campo(1054)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(1055)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(84,1056);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(1057)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(1058)); ?>"><input type="hidden" name="campo_descripcion" value="1053"><tr><td colspan='2'><?php submit_formato(84);?></td></tr></table></form></body></html>