<html><title>.:ADICIONAR 2A. AVANCE DE NOVEDAD:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">2A. AVANCE DE NOVEDAD</td></tr><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(321,3761);?></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_novedades"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_novedades"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_novedades);} ?><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3755)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">FECHA DE AVANCE*</td>
                     <?php fecha_formato(321,3756);?></tr><tr>
                     <td class="encabezado" width="20%" title="">DESCRIPCI&Oacute;N*</td>
                     <td class="celda_transparente"><textarea  tabindex='1'  name="descripcion_avance" id="descripcion_avance" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(3757)); ?></textarea></td>
                    </tr><tr id="tr_estado_avance" >
                     <td class="encabezado" width="20%" title="">ESTADO*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(321,3758,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="idft_avance_novedad" value="<?php echo(validar_valor_campo(3759)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3760)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3762)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3763)); ?>"><input type="hidden" name="campo_descripcion" value="3758"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(321);?></td></tr></table></form></body></html>