INSERT INTO campos_formato (formato_idformato,nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible) VALUES 
(348,'serie_idserie','SERIE DOCUMENTAL','INT','11',1,'11','a','Correo SAIA','11','fk','hidden',7,NULL,NULL,0,1)
,(348,'asunto','Asunto','VARCHAR','255',1,NULL,'a,e,p,b','Asunto del correo',NULL,NULL,'text',8,NULL,NULL,0,1)
,(348,'de','De','VARCHAR','255',1,NULL,'a,e,b','Remitente del correo',NULL,NULL,'text',10,NULL,NULL,0,1)
,(348,'para','Para','TEXT',NULL,1,NULL,'a,e,b',NULL,NULL,NULL,'text',11,NULL,NULL,0,1)
,(348,'anexos','Anexos','TEXT',NULL,0,NULL,'a,e,b','Anexos del correo',NULL,NULL,'hidden',15,NULL,NULL,0,1)
,(348,'idft_correo_saia','CORREO_SAIA','INT','11',1,NULL,'a,e',NULL,NULL,'ai,pk','hidden',2,NULL,NULL,0,1)
,(348,'documento_iddocumento','DOCUMENTO ASOCIADO','INT','11',1,NULL,'a,e',NULL,NULL,'i','hidden',3,NULL,NULL,0,1)
,(348,'dependencia','DEPENDENCIA DEL CREADOR DEL DOCUMENTO','INT','11',1,'{*buscar_dependencia*}','a,e',NULL,NULL,'i','hidden',6,NULL,NULL,0,1)
,(348,'encabezado','ENCABEZADO','INT','11',1,NULL,'a,e',NULL,'1',NULL,'hidden',4,NULL,NULL,0,1)
,(348,'firma','FIRMAS DIGITALES','INT','11',1,NULL,'a,e',NULL,'1','','hidden',5,NULL,NULL,0,1)
;
INSERT INTO campos_formato (formato_idformato,nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible) VALUES 
(348,'fecha_oficio_entrada','Fecha Oficio Entrada','DATETIME',NULL,1,NULL,'a,e,b','Fecha de entrada del oficio',NULL,NULL,'fecha',9,NULL,NULL,0,1)
,(348,'comentario','Comentario','VARCHAR','255',0,NULL,'a,e,b','Comentario del correo',NULL,NULL,'textarea',14,NULL,NULL,0,1)
,(348,'transferencia_correo','Transferir','TEXT',NULL,0,'1;pantallas/funcionario/carga_campo_autocompletar.php','a,e,b',NULL,NULL,NULL,'autocompletar',12,NULL,NULL,0,1)
,(348,'copia_correo','Con Copia','VARCHAR','255',0,'../../test_funcionario.php?rol=1;1;0;0;1;0;5','a,e,b',NULL,NULL,NULL,'arbol',13,NULL,NULL,0,1)
,(348,'estado_documento','ESTADO DEL DOCUMENTO','INT','11',1,NULL,'a,e',NULL,'1','','hidden',1,NULL,NULL,0,1)
,(348,'no_factura','No. de Factura','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',16,NULL,NULL,0,1)
,(348,'nit_proveedor','No. Nit Proveedor','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',17,NULL,NULL,0,1)
,(348,'centro_costo','Centro de Costos','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',18,NULL,NULL,0,1)
,(348,'adjunto_imagen','Adjunto Imagen','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',19,NULL,NULL,0,1)
,(348,'ingresar_datos_factu','ingresar_datos_factu','INT','11',0,NULL,'a,e,b',NULL,'1',NULL,'hidden',0,NULL,NULL,0,1)
;
INSERT INTO campos_formato (formato_idformato,nombre,etiqueta,tipo_dato,longitud,obligatoriedad,valor,acciones,ayuda,predeterminado,banderas,etiqueta_html,orden,mascara,adicionales,autoguardado,fila_visible) VALUES 
(348,'fecha_datos','fecha_datos','DATETIME',NULL,0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'responsable_datos_fa','responsable_datos_fa','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'uid_correo','Uid Correo','VARCHAR','255',0,NULL,'a',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'buzon_correo','Buzon Origen','VARCHAR','255',0,NULL,'a',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'fecha_factura','Fecha factura','DATE',NULL,0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'cant_dias','Cantidad d&iacute;as de pago','INT','11',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'fecha_venc_fact','Fecha vencimiento factura','DATE',NULL,0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'concepto_fact','Concepto de la factura','TEXT',NULL,0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'valor_factura','Valor de la Factura','VARCHAR','255',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
,(348,'pago_desde','Fecha de pago desde','INT','11',0,NULL,'a,e,b',NULL,NULL,NULL,'hidden',0,NULL,NULL,0,1)
;