<?php
$funciones_factura = array(
array("nombre" => '{*mostrar_estado_proceso*}', "nombre_funcion" => 'mostrar_estado_proceso', "parametros" => null, "etiqueta" => 'mostrar_estado_proceso', "descripcion" => 'mostrar_estado_proceso', "ruta" => 'funciones.php', "formato" => '1,2,3,404,194,272,305,306,307,312,313,324,343,348,359,375,387,388,390,391,395,396,400,412,413,383,411,420,421,422,423,424', "acciones" => 'm')
, array("nombre" => '{*formato_numero*}', "nombre_funcion" => 'formato_numero', "parametros" => null, "etiqueta" => 'formato_numero', "descripcion" => 'formato_numero', "ruta" => 'funciones.php', "formato" => '1,2,3,207,272,305,312,324,342,348,379,387,388,343,392,393,395,396,404,408,411,412,413,420,421,422,423,424,425,426,427,428,429', "acciones" => 'm')
, array("nombre" => '{*logo_empresa*}', "nombre_funcion" => 'logo_empresa', "parametros" => null, "etiqueta" => 'logo_empresa', "descripcion" => 'logo_empresa', "ruta" => 'funciones.php', "formato" => '1,2,3,194,207,272,305,306,312,313,314,307,324,342,343,348,359,364,379,381,382,383,385,387,388,393,394,404,408,409,411,412,413,395,396,353,420,421,422,423,424,425,426,427,428,429', "acciones" => 'm')
, array("nombre" => '{*fecha_formato*}', "nombre_funcion" => 'fecha_formato', "parametros" => null, "etiqueta" => 'fecha_formato', "descripcion" => 'fecha_formato', "ruta" => 'funciones.php', "formato" => '1,2,3,207,272,305,306,312,324,379,412,411,406,421,422,427', "acciones" => 'a,e')
, array("nombre" => '{*nombre_formato*}', "nombre_funcion" => 'nombre_formato', "parametros" => null, "etiqueta" => 'nombre_formato', "descripcion" => null, "ruta" => '../librerias/encabezado_pie_pagina.php', "formato" => '1,2,3,207,272,305,306,307,312,313,314,324,342,348,359,381,382,383,385,387,388,343,391,394,404,408,409,411,412,413,420,421,422,423,424,425,426,427,428,429', "acciones" => 'm')
, array("nombre" => '{*digitalizar_formato*}', "nombre_funcion" => 'digitalizar_formato', "parametros" => null, "etiqueta" => 'digitalizar_formato', "descripcion" => 'digitalizar_formato', "ruta" => '../librerias/funciones_formatos_generales.php', "formato" => '3,421,422', "acciones" => 'a,e')
, array("nombre" => '{*validar_digitalizacion_formato*}', "nombre_funcion" => 'validar_digitalizacion_formato', "parametros" => null, "etiqueta" => 'validar_digitalizacion_formato', "descripcion" => 'validar_digitalizacion_formato', "ruta" => '../librerias/funciones_formatos_generales.php', "formato" => '421,422', "acciones" => null)
, array("nombre" => '{*cargar_datos_rad_obras*}', "nombre_funcion" => 'cargar_datos_rad_obras', "parametros" => null, "etiqueta" => 'cargar_datos_rad_obras', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*add_edit_rad_obras*}', "nombre_funcion" => 'add_edit_rad_obras', "parametros" => null, "etiqueta" => 'add_edit_rad_obras', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'a,e')
, array("nombre" => '{*post_edit_rad_obras*}', "nombre_funcion" => 'post_edit_rad_obras', "parametros" => null, "etiqueta" => 'post_edit_rad_obras', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => null)
, array("nombre" => '{*post_aprob_rad_obras*}', "nombre_funcion" => 'post_aprob_rad_obras', "parametros" => null, "etiqueta" => 'post_aprob_rad_obras', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => null)
, array("nombre" => '{*ver_qr_rad_obras*}', "nombre_funcion" => 'ver_qr_rad_obras', "parametros" => null, "etiqueta" => 'ver_qr_rad_obras', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*ver_fecha_pago*}', "nombre_funcion" => 'ver_fecha_pago', "parametros" => null, "etiqueta" => 'ver_fecha_pago', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*ver_tipo_doc*}', "nombre_funcion" => 'ver_tipo_doc', "parametros" => null, "etiqueta" => 'ver_tipo_doc', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*color_vence_factura*}', "nombre_funcion" => 'color_vence_factura', "parametros" => null, "etiqueta" => 'color_vence_factura', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*mostrar_radicado_obra*}', "nombre_funcion" => 'mostrar_radicado_obra', "parametros" => null, "etiqueta" => 'mostrar_radicado_obra', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'a,e')
, array("nombre" => '{*mostrar_valor_factura*}', "nombre_funcion" => 'mostrar_valor_factura', "parametros" => null, "etiqueta" => 'mostrar_valor_factura', "descripcion" => null, "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
, array("nombre" => '{*mostrar_listado_distribucion_documento*}', "nombre_funcion" => 'mostrar_listado_distribucion_documento', "parametros" => null, "etiqueta" => 'mostrar_listado_distribucion_documento', "descripcion" => null, "ruta" => '../../distribucion/funciones_distribucion.php', "formato" => '1,422,421,420', "acciones" => 'm')
, array("nombre" => '{*mostrar_destino_facturas_obras*}', "nombre_funcion" => 'mostrar_destino_facturas_obras', "parametros" => null, "etiqueta" => 'mostrar_destino_facturas_obras', "descripcion" => 'mostrar_destino_facturas_obras', "ruta" => 'funciones.php', "formato" => '421', "acciones" => 'm')
);

