<html><title>.:ADICIONAR INFORME SEGUIMIENTO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">INFORME SEGUIMIENTO</td></tr><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5338)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(431,5339);?></tr><input type="hidden" name="municipio_informe" value="<?php echo(validar_valor_campo(5340)); ?>"><tr>
                       <td class="encabezado" width="20%" title="">FECHA DE SEGUIMIENTO A COMPROMISOS*</td><td colspan="2" bgcolor="#F5F5F5"><span class="phpmaker"><input  tabindex='1'  type="text" readonly="true"  class="required dateISO"  name="fecha_compromisos" id="fecha_compromisos" tipo="fecha" value="<?php echo(date("0000-00-00")); ?>"><?php selector_fecha("fecha_compromisos","formulario_formatos","Y-m-d",date("m"),date("Y"),"default.css","../../","AD:VALOR","VENTANA",FALSE,FALSE); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">PROCESO AUDITADO</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="proceso_auditado" id="proceso_auditado" cols="53" rows="3" class="tiny_basico"><?php echo(validar_valor_campo(5342)); ?></textarea></td>
                    </tr><input type="hidden" name="observaciones" value="<?php echo(validar_valor_campo(5345)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">PORCENTAJE DE CUMPLIMIENTO DEL PLAN*</td>
                     <?php porcentaje_plan(431,5346);?></tr><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5349)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">JEFE DE CONTROL INTERNO*</td>
                     <?php buscar_jefe_control(431,5350);?></tr><input type="hidden" name="idft_informe_contraloria" value="<?php echo(validar_valor_campo(5351)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5352)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5353)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5354)); ?>"><?php validar_adicion_funcionario_contraloria(431,NULL);?><input type="hidden" name="campo_descripcion" value="5341"><tr><td colspan='2'><?php submit_formato(431);?></td></tr></table></form></body></html>