<html><title>.:ADICIONAR PLANEACION - ANALISIS DE CAUSAS:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">PLANEACION - ANALISIS DE CAUSAS</td></tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_clasificacion_pqrsf"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_clasificacion_pqrsf"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_clasificacion_pqrsf);} ?><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3669)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_pqrsf"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_pqrsf"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_pqrsf);} ?><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3671)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3672)); ?>"><input type="hidden" name="idft_analisis_pqrsf" value="<?php echo(validar_valor_campo(3668)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3667)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(313,3670);?></tr><tr>
                     <td class="encabezado" width="20%" title="">ANALISIS DE CAUSAS*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='1'  type="text" size="100" id="analisis_causas" name="analisis_causas"  value="<?php echo(validar_valor_campo(3673)); ?>"></td>
                    </tr><input type="hidden" name="campo_descripcion" value="3673"><tr><td colspan='2'><?php submit_formato(313);?></td></tr></table></form></body></html>