<html><title>.:ADICIONAR FLUJOS HIJO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">FLUJOS HIJO</td></tr><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(4963)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(4962)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(402,4961);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(4960)); ?>"><input type="hidden" name="idft_flujos_hijo" value="<?php echo(validar_valor_campo(4959)); ?>"><tr id="tr_campo_tezxt">
                     <td class="encabezado" width="20%" title="">CAMPO TEXT*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='1'  type="text" size="100" id="campo_tezxt" name="campo_tezxt"  value="<?php echo(validar_valor_campo(4958)); ?>"></td>
                    </tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(4957)); ?>"><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(4956)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_flujos_padre"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_flujos_padre"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_flujos_padre);} ?><tr><td colspan='2'><?php submit_formato(402);?></td></tr></table></form></body></html>