<html><title>.:EDITAR FLUJOS HIJO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">FLUJOS HIJO</td></tr><input type="hidden" name="firma" value="<?php echo(mostrar_valor_campo('firma',402,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="encabezado" value="<?php echo(mostrar_valor_campo('encabezado',402,$_REQUEST['iddoc'])); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(402,4961,$_REQUEST['iddoc']);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(mostrar_valor_campo('documento_iddocumento',402,$_REQUEST['iddoc'])); ?>"><input type="hidden" name="idft_flujos_hijo" value="<?php echo(mostrar_valor_campo('idft_flujos_hijo',402,$_REQUEST['iddoc'])); ?>"><tr id="tr_campo_tezxt">
                     <td class="encabezado" width="20%" title="">CAMPO TEXT*</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"  class="required"   tabindex='1'  type="text" size="100" id="campo_tezxt" name="campo_tezxt"  value="<?php echo(mostrar_valor_campo('campo_tezxt',402,$_REQUEST['iddoc'])); ?>"></td>
                    </tr><input type="hidden" name="formato" value="402"><tr><td colspan='2'><?php submit_formato(402,$_REQUEST['iddoc']);?></td></tr></table></form></body></html><?php include_once("../librerias/footer_plantilla.php");?>