<html><title>.:ADICIONAR TEJIDOS PERIODONTALES:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">TEJIDOS PERIODONTALES</td></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(3349)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(290,3348);?></tr><tr>
                       <td class="encabezado" width="20%" title="">FECHA*</td><td colspan="2" bgcolor="#F5F5F5"><span class="phpmaker"><input  tabindex='1'  type="text" readonly="true"  class="required dateISO"  name="fecha_periodontal" id="fecha_periodontal" tipo="fecha" value="<?php echo(date("Y-m-d")); ?>"><?php selector_fecha("fecha_periodontal","formulario_formatos","Y-m-d",date("m"),date("Y"),"default.css","../../","AD:VALOR","VENTANA",FALSE,FALSE); ?></span></font></td><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(3345)); ?>"><input type="hidden" name="idft_tejidos_periodontales" value="<?php echo(validar_valor_campo(3346)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(3347)); ?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(3350)); ?>"><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_solicitud_cita"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_solicitud_cita"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_solicitud_cita);} ?><tr>
                     <td class="encabezado" width="20%" title="">CAJA1</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='2'  type="text" size="100" id="caja_uno" name="caja_uno"  value="<?php echo(validar_valor_campo(3448)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">CAJA2</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='3'  type="text" size="100" id="caja_dos" name="caja_dos"  value="<?php echo(validar_valor_campo(3449)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">CAJA3</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='4'  type="text" size="100" id="caja_tres" name="caja_tres"  value="<?php echo(validar_valor_campo(3450)); ?>"></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">CAJA4</td>
                     <td bgcolor="#F5F5F5"><input  maxlength="255"   tabindex='5'  type="text" size="100" id="caja_cuatro" name="caja_cuatro"  value="<?php echo(validar_valor_campo(3451)); ?>"></td>
                    </tr><?php if($_REQUEST["padre"]) {?><input type="hidden"  name="ft_clinica_ortodoncia"  value="<?php echo $_REQUEST["padre"]; ?>"><?php } ?><?php if($_REQUEST["anterior"]) {?><input type="hidden"  name="ft_clinica_ortodoncia"  value="<?php echo $_REQUEST["anterior"]; ?>"><?php }  else {listar_select_padres(ft_clinica_ortodoncia);} ?><?php ocultar_cajas(290,NULL);?><input type="hidden" name="campo_descripcion" value="3453"><tr><td colspan='2'><?php submit_formato(290);?></td></tr></table></form></body></html>