<html><title>.:ADICIONAR PRUEBA MAURO1:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">PRUEBA MAURO1</td></tr><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(5162)); ?>"><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(5161)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(417,5160);?></tr><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(5159)); ?>"><input type="hidden" name="idft_prueba_mauro1" value="<?php echo(validar_valor_campo(5158)); ?>"><tr id="tr_tipo" >
                     <td class="encabezado" width="20%" title="">TIPO*</td><td bgcolor="#F5F5F5"><?php genera_campo_listados_editar(417,5157,$_REQUEST['iddoc']);?></td></tr><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(5156)); ?>"><input type="hidden" name="estado_documento" value="<?php echo(validar_valor_campo(5155)); ?>"><input type="hidden" name="campo_descripcion" value="5157"><tr><td colspan='2'><?php submit_formato(417);?></td></tr></table></form></body></html>