<html><title>.:ADICIONAR 3. SEGUIMIENTO:.</title><head><script type="text/javascript" src="../librerias/funciones_formatos.js"></script><script type="text/javascript" src="../../js/cmxforms.js"></script><?php include_once("funciones.php"); ?><?php include_once("../librerias/funciones_generales.php"); ?><?php include_once("../librerias/funciones_acciones.php"); ?><?php include_once("../librerias/estilo_formulario.php"); ?><?php include_once("../librerias/header_formato.php"); ?><?php include_once("../../calendario/calendario.php"); ?><script type="text/javascript" src="../../js/jquery.js"></script><script type="text/javascript" src="../../js/jquery.validate.js"></script><script type="text/javascript" src="../../js/title2note.js"></script><script type="text/javascript" src="../../anexosdigitales/multiple-file-upload/jquery.MultiFile.js"></script><?php include_once("../../anexosdigitales/funciones_archivo.php"); ?><script type="text/javascript" src="../../anexosdigitales/highslide-4.0.10/highslide/highslide-with-html.js"></script><link rel="stylesheet" type="text/css" href="../../anexosdigitales/highslide-4.0.10/highslide/highslide.css" />
    </style><script type='text/javascript'>
    hs.graphicsDir = '../../anexosdigitales/highslide-4.0.10/highslide/graphics/';
    hs.outlineType = 'rounded-white';
</script><script type='text/javascript'>
  $().ready(function() {
	// validar los campos del formato
	$('#formulario_formatos').validate();
	
});
</script> </head><body bgcolor="#F5F5F5"><?php llama_funcion_accion(@$_REQUEST["iddoc"],@$_REQUEST["idformato"],"ingresar","ANTERIOR");?><form name="formulario_formatos" id="formulario_formatos" method="post" action="../../class_transferencia.php" enctype="multipart/form-data"><table width="100%" cellspacing="1" cellpadding="4"><tr><td colspan="2" class="encabezado_list">3. SEGUIMIENTO</td></tr><input type="hidden" name="seguimiento_antiguo" value="<?php echo(validar_valor_campo(4766)); ?>"><input type="hidden" name="idft_seguimiento_riesgo" value="<?php echo(validar_valor_campo(4768)); ?>"><input type="hidden" name="documento_iddocumento" value="<?php echo(validar_valor_campo(4770)); ?>"><input type="hidden" name="serie_idserie" value="<?php echo(validar_valor_campo(4771)); ?>"><tr>
                     <td class="encabezado" width="20%" title="">DEPENDENCIA DEL CREADOR DEL DOCUMENTO*</td>
                     <?php buscar_dependencia(397,4772);?></tr><input type="hidden" name="encabezado" value="<?php echo(validar_valor_campo(4773)); ?>"><tr>
                       <td class="encabezado" width="20%" title="Fecha">FECHA*</td><td colspan="2" bgcolor="#F5F5F5"><span class="phpmaker"><input  tabindex='1'  type="text" readonly="true"  class="required dateISO"  name="fecha_seguimiento" id="fecha_seguimiento" tipo="fecha" value="<?php echo(date("Y-m-d")); ?>"><?php selector_fecha("fecha_seguimiento","formulario_formatos","Y-m-d",date("m"),date("Y"),"default.css","../../","AD:VALOR","VENTANA",FALSE,FALSE); ?></span></font></td><tr>
                     <td class="encabezado" width="20%" title="">ACCION*</td>
                     <?php listar_acciones_riesgo(397,4776);?></tr><tr>
                     <td class="encabezado" width="20%" title="Logro alcanzado">LOGRO*</td>
                     <td class="celda_transparente"><textarea  tabindex='2'  name="logro" id="logro" cols="53" rows="3" class="tiny_basico required"><?php echo(validar_valor_campo(4777)); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="observaciones">OBSERVACIONES (LIMITANTES EN EL CUMPLIMIENTO DE LA ACCI&Oacute;N, DIFICULTADES)</td>
                     <td class="celda_transparente"><textarea  tabindex='3'  name="observaciones" id="observaciones" cols="53" rows="3" class="tiny_basico"><?php echo(validar_valor_campo(4778)); ?></textarea></td>
                    </tr><tr>
                     <td class="encabezado" width="20%" title="">ADJUNTAR EVIDENCIA DOCUMENTAL</td>
                     <td class="celda_transparente"><input  tabindex='4'  type="file" maxlength="255"  class='multi'  name="evidencia_documental[]" accept="<?php echo $extensiones;?>"><input type="hidden" name="firma" value="<?php echo(validar_valor_campo(4780)); ?>"><?php opciones_control(397,NULL);?><?php opciones_valoracion(397,NULL);?><input type="hidden" name="campo_descripcion" value="4775"><input type="hidden" name="padre" value="<?php echo $_REQUEST["padre"]; ?>"><input type="hidden" name="anterior" value="<?php echo $_REQUEST["anterior"]; ?>"><input type="hidden" name="accion" value="guardar_detalle" ><tr><td colspan='2'><?php submit_formato(397);?></td></tr></table><input type='hidden' name='permisos_anexos' id='permisos_anexos' value=''></form></body></html>